### ISSUE TITLE
Root support

### ISSUE THREAD

**Issue by upintheairsheep** [microsoft/WSA#100]
### Describe the solution you'd like

Please add a setting to add root support to the emulator via a setting, and when it is on and something attempts to use SU, a diologe that kinda is like UAC pops up asking for root.

### Please specify the version of Windows Subsystem for Android

1.0

**Comment by nieubank** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap. Could you please provide specifics about how enabling root access would help in your development efforts?

**Comment by upintheairsheep** [comment]
> Hi, thank you for this feature request. Currently this isn't on our immediate roadmap. Could you please provide specifics about how enabling root access would help in your development efforts?

It would make development of rooted apps easier.

**Comment by yonggamer** [comment]
I want suport for twrp [https://twrp.me/](url)

**Comment by upintheairsheep** [comment]
> I want suport for twrp https://twrp.me/

TWRP is not an android app, it is a recovery mode partition.

**Comment by yonggamer** [comment]
I want to install [Magisk](https://github.com/topjohnwu/Magisk)

**Comment by upintheairsheep** [comment]
I believe it should be an option to make the su binary/ies visible to the app, otherwise apps that detect root will fail to function.
