### ISSUE TITLE
Can Apps run as Landscape mode as default?

### ISSUE THREAD

**Issue by whwdzg** [microsoft/WSA#102]
### Describe the solution you'd like

Apps run as Landscape mode as default

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by nieubank** [comment]
WSA does run apps by default in a landscape window on a landscape oriented display. If the developer specifies a portrait app orientation in their manifest however, it respects that first. 

Do you specific apps that should be launching landscape but are not based on the above?

**Comment by whwdzg** [comment]
Emm, when I am using my apps(like wechat,rotation), it is supposed to have a list on the right side(like android pad), instead of whole list.

**Comment by andrewleader** [comment]
@whwdzg are you the developer of those apps? If not, I would recommend you share that feedback with the developers of WeChat and Rotation, as they control the orientation and display settings of their apps.
