### ISSUE TITLE
Can we just double click the .apk file to install app to WSA?

### ISSUE THREAD

**Issue by whwdzg** [microsoft/WSA#104]
### Describe the solution you'd like

 Double click the .apk file to install app.

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by dabhattimsft** [comment]
Hi, this is something on our radar already for new feature requests, we appreciate the feedback here!

**Comment by jake-brown-maps** [comment]
Great to hear this feature is on the radar.  The ability to easily install an APK outside of the Amazon Appstore would be a useful for evaluating new features and working with beta testers.  

Jake Brown 
Product Engineer
 Esri

**Comment by nieubank** [comment]
We're monitoring this feedback but there's nothing on the immediate roadmap in this space.

**Comment by jake-brown-maps** [comment]
@nieubank is there an alternative plan for an WSA/App install solution that does not rely on the app stores?

**Comment by nieubank** [comment]
> @nieubank is there an alternative plan for an WSA/App install solution that does not rely on the app stores?

We have nothing to share at this time. Today the recommend way to sideload apps is via "adb install" in developer mode.

**Comment by infinitepower18** [comment]
The latest WSA preview update has support for browsing files stored in Windows via the files app and other Android apps, so you will be able to install an APK via the files app.
