### ISSUE TITLE
Multiple calls to onFling in GestureDetector with two finger swipe

### ISSUE THREAD

**Issue by massimobio** [microsoft/WSA#108]
### Steps to reproduce

A two finger swipe generates multiple calls.
In my book-type app I use a finger swipe to go to the next/previous page. 
This works on Android Tablets and on Chromebooks but on Windows it always jumps by several pages.

### ✔️ Expected Behavior

A single finger swipe on a touch screen or a two finger swipe on a Chromebook generate a single onFling call

### ❌ Actual Behavior

A two finger swipe generates multiple calls to onFling in a GestureDetector.SimpleOnGestureListener including extra ones even after the fingers have been lifted from the track pad. (Maybe to simulate inertia?)

I couldn't come up with a workaround. Each MotionEven is distinct but identical (except for the ID) so it's not possible to distinguish the system generated ones from the ones generated by the user.

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by hgourvest** [comment]
I think it is the same issue as #98
