### ISSUE TITLE
maximumWindowMetrics returns the window size instead of the screen size

### ISSUE THREAD

**Issue by arlomedia** [microsoft/WSA#109]
### Steps to reproduce

Run this code:

`
val wm = context.getSystemService(Context.WINDOW_SERVICE) as WindowManager
val rect = wm.maximumWindowMetrics.bounds
`

### ✔️ Expected Behavior

rect contains the width and height of the screen, even if the app window is sized smaller than the screen. This is how it behaves on an Android device in multi-window mode.

### ❌ Actual Behavior

rect contains the width and height of the window.

I haven't found another way to get the screen size while in multi-window mode on Android devices. If there is another way in WSA, I'll use that. But it would probably be best if this function behaves the same way in WSA as it does on Android devices.

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by nieubank** [comment]
Thanks for reporting this. Currently, this is expected in WSA because we've found that a significant percentage of apps incorrectly handle display vs. window bounds. To mitigate this, we currently apply the [always sandbox display apis compat shim](https://developer.android.com/about/versions/12/reference/compat-framework-changes) to all applications. 

We're continually working on improving the balance between making the user experience great for apps that aren't written properly vs. compromising the developer experience for those apps doing things correctly.

It would be great if you could give a bit more detail explaining why maximumWindowMetrics or querying the absolute screen size is important for your app's multi-window scenarios so we can have more data when making these decisions.

**Comment by arlomedia** [comment]
I develop two apps for musicians that let them design their own screen layouts to optimize their access to the functions they need while performing. The layouts are saved and displayed per the window size, so bands can design the ideal layout for each device they use. Layouts are also are synced across devices, but only layouts that match the app window size are displayed as options on a given device, so bands can use a mixture of device sizes while avoiding the clutter of seeing every device's layouts. With free-form windows, this becomes confusing because changing the app window size on a device makes it look like no layouts are available for that device. So the apps use the screen size to determine which layouts were originally designed for that device and show those layouts as options, automatically scaled to the window size. In short, I'm using the screen size to identify which layouts to display on a given device, and the window size to scale them down if needed.

Users can also create layouts specific to a smaller window size, but since it's difficult to return to the same window size after resizing, this is less common. It's more common for users to temporarily reduce their window size while doing some multi-tasking operation, then maximize the window again when they're done. In that situation, continuing to show the same layouts designed for that device, but scaling them while multi-windowed, is a simple and intuitive alternative.

Sorry, I couldn't think of a simpler way to explain it. :-) As for other developers, the distinction between `getCurrentWindowMetrics()` and `getMaximumWindowMetrics()` seems pretty clear. I wonder what other functions they would be using incorrectly, since most functions I've tried return the window size in multi-window mode without the WSA override. Anyway, thanks for considering.

**Comment by nieubank** [comment]
In future builds (2211+) the plan is to only apply the display api sandbox only to apps that also have the force non-resizable shim applied. These apps are selected based on one or more of the following heuristics - 

- Target SDK version < Android N (24) or Build.VERSION.MIN_SUPPORTED_TARGET_SDK_INT
- Apps that are resizable via SDK version (ApplicationInfo.PRIVATE_FLAG_ACTIVITIES_RESIZE_MODE_RESIZEABLE_VIA_SDK_VERSION) that have a fixed orientation main activity.
- Manifest explicitly declares the app to be not resizable (resizable=false).

Today, these are only applied to apps with the Amazon App Store as the install source. This means that from 2211 onwards, sideloaded apps will not have the display sandbox enabled by default.

Let me know if this will work for the cases that you have identified.

**Comment by arlomedia** [comment]
Great, I look forward to trying this update when it's available.

**Comment by arlomedia** [comment]
I'm finally coming back to look at this again. I don't see any change in the current WSA version 2311 -- wm.maximumWindowMetrics.bounds still returns the window size instead of the screen size. My app doesn't meet any of the criteria in your three bullet points above, but it is installed via the Amazon App Store. Is there something else I need to do to remove the "always sandbox display apis" shim from my app?
