### ISSUE TITLE
Failed device discovery and socket connections

### ISSUE THREAD

**Issue by arlomedia** [microsoft/WSA#112]
### Steps to reproduce

My app uses `NsdManager.discoverServices` to find the same app running on other devices and `Socket.connect` to connect to the devices it finds. This is used to link the app on multiple devices for live music performance.

I'm trying this functionality between an Android device and a Windows device with WSA. I have Advanced Networking turned on in my WSA settings. I temporarily turned off the Windows (McAfee) firewall.

I'm seeing a similar problem when trying to use my app's MIDI functions with an RTP-MIDI connection from the Audio MIDI Setup app on a Mac to the third-party MIDI library in my app: the device scanner sees "Subsystem for Android," but all connection attempts result in an error "10.0.1.6:6600 didn’t respond to the connection request."

I see that "Local network access by default" is included on the Future Roadmap ... not sure if that's related.

### ✔️ Expected Behavior

Existing Android functionality working in WSA.

### ❌ Actual Behavior

When I try to connect from WSA to an Android device, `discoverServices` doesn't find any other devices. When I try to connect from an Android device to WSA, it finds a "Subsystem for Android" device, but then `connect` fails with "java.net.ConnectException: failed to connect to /10.0.1.6 (port 60769) from /10.0.1.17 (port 34060) after 10000ms: isConnected failed: EHOSTUNREACH (No route to host)."

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by hamza-usmani** [comment]
@keith-horton @nieubank, please review!

**Comment by nieubank** [comment]
This is not currently a supported scenario. Advanced networking is a preview of functionality intended to address some of these networking scenarios, but we can't offer any guarantees regarding local network access at this time. Stay tuned for updates as we make progress on the roadmap. 

The details you provided here will definitely help us as we improve our networking functionality.

**Comment by omghb** [comment]
(+1) We have the same issue.
