### ISSUE TITLE
Open file from File Explorer in Android App

### ISSUE THREAD

**Issue by massimobio** [microsoft/WSA#114]
### Is your feature request related to a problem? Please describe

I have registered my app to open `.html` files with an intent in the manifest:
```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:host="*" />
    <data android:mimeType="text/html" />
    <data android:scheme="file" />
    <data android:scheme="content" />
</intent-filter>
```

This works correctly on Android and it allows my app to open `.html` files form the file system, email attachments, Dropbox, Google Drive...

### Describe the solution you'd like

It would be great if having this intent in the manifest would expose the app to Windows so that from File Explorer one could use `Open With >` to open a file with the Android app.

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by mattkopec** [comment]
Hey, thanks for the feature. We currently have related features on our roadmap ( such as #111 ) which this feature would depend on. This feature would follow thereafter.

**Comment by massimobio** [comment]
Very glad to hear this, thank you.

**Comment by massimobio** [comment]
#111 has been marked as fixed but I'm not sure I understand how.
I have WSA 2306 installed.
Exporting files from the Android environment to Windows with Intent ACTION_SEND works and they get saved in the Windows Downloads folder, but I'm still not able to open files from Windows into my Android app.
I tried ACTION_VIEW and ACTION_GET_CONTENT to show a file selection dialog but I'm only shown the Android internal file system to select from.
@kevinkieselbach [mentioned](https://github.com/microsoft/WSA/issues/111#issuecomment-1644428253) that drag and drop should work now, but when I try to drag a file on top of my android app I get a not allowed symbol 🚫 even though I have registered the file type in my manifest (see first post). I even tried to change the mimeType to "*/*" with the same results.
Is there anything else I need to do to enable Drag and Drop and/or to access the Windows file system? Thank you

**Comment by massimobio** [comment]
Thank you! Got it to work. 
I missed that one has to go through the WSA app > System > Files > Subsystem for Android > Windows > ... in order to open a file in the Android app.
Good work, thank you.
