### ISSUE TITLE
home screen

### ISSUE THREAD

**Issue by yonggamer** [microsoft/WSA#115]
### Describe the solution you'd like

please add Microsoft Launcher (https://play.google.com/store/apps/details?id=com.microsoft.launcher&hl=nl&gl=US)

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by mattkopec** [comment]
Hey, thanks for the feedback. This isn't something we're currently considering but we're always evaluating features to prioritize.

**Comment by nieubank** [comment]
Our GitHub bugs are for developer-facing issues, and this looks like an issue with an app or feature. Please use the Windows Feedback Hub for end-user app issues. If you have a particular developer scenario or issue with an app you're developing that relies on certain home screen functionalities that aren't present in WSA please follow up with additional details.
