### ISSUE TITLE
Display Toast messages within App Window

### ISSUE THREAD

**Issue by itanium99** [microsoft/WSA#116]
### Is your feature request related to a problem? Please describe

The toast messages are displayed outside the app window and in a multi monitor setup, always at the same monitor regardless of where the app window is located.

### Describe the solution you'd like

Toast message within app window like it is on real devices

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by nieubank** [comment]
Thanks for this feedback. Being on the wrong display is definitely not the ideal experience. 

For some background, we foreword toasts to Windows notifications with the goal of a seamless user experience and many older apps still use global toasts that don't appear over the app window in multi-window mode, instead appearing at the bottom of the primary display which is easier to miss, and Android doesn't render those well on high dpi displays. We'll consider some options internally and see what we can do.

**Comment by andrewleader** [comment]
Hi @itanium99, thanks for the great feedback! Can you share the name(s) of the apps you develop that use toasts and are impacted by this? Also, have you looked into using [Google's Snackbar UI](https://developer.android.com/reference/com/google/android/material/snackbar/Snackbar) within your apps to display these contextual lightweight messages? Thanks!

**Comment by itanium99** [comment]
Hello and thank you for this fast reaction,

the toast message i use in my company's app has a custom layout (setView, setGravity) with variable image (info/warning/error) which i set per parameter in a custom function. I prefer toast because it's independent from a view (but snackbar needs that) and just needs context as argument. No user action is necessary, message disappears after a given duration (Toast.LENGTH_LONG) and the user simply gets a short informative feedback.

Best regards

**Comment by Mids9** [comment]
https://github.com/microsoft/WSA/issues/116#issuecomment-1311831662
