### ISSUE TITLE
apps aren't able to maintain playback of 2 media files simultaneously

### ISSUE THREAD

**Issue by ghost** [microsoft/WSA#117]
### Steps to reproduce

play 2 media files in 2 different apps in WSA, such as:

- 2 browsers (each browser playing a different YouTube video)

- a browser and Twitter app (browser playing YouTube video and Twitter playing a video from timeline)

- a browser and VLC app (browser playing YouTube video and VLC media player playing an audio/video file)

### ✔️ Expected Behavior

Just like Windows programs, none of their playbacks should be paused based on window focus loss and should keep playing.

### ❌ Actual Behavior

one of them loses focus and even pauses when the window focus is on the other app.

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by andrewleader** [comment]
Hi lul, thanks for the feedback! Are you developing an Android media app? If so, can you tell us more about your app (name of it, or a short summary of what it does)?
