### ISSUE TITLE
cpu and ram settings

### ISSUE THREAD

**Issue by yonggamer** [microsoft/WSA#121]
### Describe the solution you'd like

please add cpu and ram settngs

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by nieubank** [comment]
WSA uses up to 4GB RAM for devices that have 8GB or less physical RAM, 6GB otherwise.

**Comment by yonggamer** [comment]
yes i want more than 6GB of ram
I also want screen resolution settings

**Comment by nieubank** [comment]
Can you provide more details about why screen resolution is interesting? You can change the screen resolution on the Windows monitor itself and Android will reflect those changes.

**Comment by yonggamer** [comment]
nox and bluestacks have it
![1](https://user-images.githubusercontent.com/24843208/202683074-8a0e2e0d-e0b6-4b17-8ed8-b3f5a087cb71.JPG)
![2](https://user-images.githubusercontent.com/24843208/202683080-5d8704a2-ad3c-4c44-a387-25bb0fb28b21.JPG)

**Comment by yonggamer** [comment]
does it add HDR support?

**Comment by nieubank** [comment]
We've added ram settings to the WSA Settings app, we'll continue to evaluate other options but there are none on the immedaite roadmap.
