### ISSUE TITLE
fullscreen

### ISSUE THREAD

**Issue by yonggamer** [microsoft/WSA#122]
### Describe the solution you'd like

please add a open always in fullscreen option

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by AhmedZero** [comment]
there is already a Full-screen option, press F11.

**Comment by yonggamer** [comment]
open always in fullscreen option

**Comment by hamza-usmani** [comment]
This is currently supported, as @AhmedZero has commented. You can see all of our supported inputs and [keyboard shortcuts here](https://support.microsoft.com/en-us/windows/supported-inputs-for-mobile-apps-on-windows-e5592a58-9a77-4b03-9f6d-5f57c01516a6)!

**Comment by yonggamer** [comment]
#133
