### ISSUE TITLE
external drive

### ISSUE THREAD

**Issue by yonggamer** [microsoft/WSA#123]
### Describe the solution you'd like

please add app instalation  and app data on external drive
and full data export to external drive

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by Mids9** [comment]
> ### Is your feature request related to a problem? Please describe
> 
> _No response_
> 
> ### Describe the solution you'd like
> 
> please add app instalation  and app data on external drive
> and full data export to external drive
> 
> ### Describe alternatives you've considered
> 
> _No response_
> 
> ### Please specify the version of Windows Subsystem for Android
> 
> 2209.40000.26.0
[]()
```
- [ ] ``
```

**Comment by yonggamer** [comment]
yes

**Comment by nieubank** [comment]
Hi, thank you for this feedback. However, our GitHub bugs are for developer-facing issues, and this looks like an issue with an app or feature. Please use the Windows Feedback Hub for end-user app issues.
