### ISSUE TITLE
Microsoft Edge browser hasn't been working in WSA

### ISSUE THREAD

**Issue by lulMeow** [microsoft/WSA#127]
### Steps to reproduce

Install the official Microsoft Edge browser for Android (any channel) either by APK or through Aurora store

### ✔️ Expected Behavior

I expect the browser to work

### ❌ Actual Behavior

The browser installs but doesn't work, this app is something I've always been testing right after installing every new WSA version in the past few months. it's never worked as far as I remember and still doesn't.

this is all I get when I type anything in the address bar, even the built-in pages such as Edge://flags or Edge://about or Edge://gpu/ don't load.

![image](https://user-images.githubusercontent.com/72892766/201627868-21febdbd-0131-4cb2-96d3-2727196341e0.png)

![image](https://user-images.githubusercontent.com/72892766/201627933-6a6664eb-7dd9-4766-9a07-9ee8c050c002.png)

I've tried a bunch of other browsers that do work, such as Brave, Firefox, Firefox focus, Duckduckgo, Opera. some are based on Chromium, some based on Firefox, some based on the built-in WebView.

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by hamza-usmani** [comment]
Hi, thank you for this feedback. However, our GitHub bugs are for developer-facing issues, and this looks like an issue with an app or feature. Please use the Windows Feedback Hub for end-user app issues.
