### ISSUE TITLE
Can't connect to local share when Advanced Networking option is enabled.

### ISSUE THREAD

**Issue by hgourvest** [microsoft/WSA#135]
### Steps to reproduce

- Enable "Advanced Networking" option
- Restart WSA to apply changes if necessary.
- Install a port scanner and search for ports 139 and 445 on your local machine's public ip address.

### ✔️ Expected Behavior

Port 139 and 445 should be open.

### ❌ Actual Behavior

You should see that there is no open port.
But if you disable the option then the ports become visible.

### Other Software

The port scanner I used.
https://play.google.com/store/apps/details?id=com.twistandroid.portscan&gl=US

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by nieubank** [comment]
We'll investigate and follow up on this. Thank you for bringing this to our attention.

**Comment by nieubank** [comment]
Tracking this under #213
