### ISSUE TITLE
com ports

### ISSUE THREAD

**Issue by yonggamer** [microsoft/WSA#138]
### Describe the solution you'd like

please add support for com ports

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by nieubank** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community!  It would be great if you could provide details about what developer scenarios are blocked for you without com port access. This isn't a common feature on Android devices.

**Comment by yonggamer** [comment]
https://en.wikipedia.org/wiki/COM_(hardware_interface)

**Comment by nieubank** [comment]
We're looking for more information about how your apps use COM ports and why WSA supporting them can unblock your development scenarios?
