### ISSUE TITLE
lock screen

### ISSUE THREAD

**Issue by yonggamer** [microsoft/WSA#139]
### Describe the solution you'd like

please add a lock screen

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by hamza-usmani** [comment]
Hi, could you add more detail to this feature request? If not, we'll be closing this out since we don't have enough information for this to be actionable.

**Comment by yonggamer** [comment]
I want this
![Screenshot_20221122-001945_Settings](https://user-images.githubusercontent.com/24843208/203180479-7cdc7b6b-ed24-454d-b330-583e7c01ff19.png)

**Comment by nieubank** [comment]
Our GitHub bugs are for developer-facing issues, and this looks like an issue with an app or feature. Please use the Windows Feedback Hub for end-user app issues. If this is related to a developer scenario, please include more details about your app and how it depends on the lock screen.
