### ISSUE TITLE
Web browser

### ISSUE THREAD

**Issue by yonggamer** [microsoft/WSA#151]
### Describe the solution you'd like

please add Microsoft Edge https://play.google.com/store/apps/details?id=com.microsoft.emmx

### Please specify the version of Windows Subsystem for Android

2210.40000.7.0

**Comment by nieubank** [comment]
Hi, thank you for this feedback. However, our GitHub bugs are for developer-facing issues, and this looks like an issue with an app or feature. Please use the Windows Feedback Hub for end-user app issues.

**Comment by upintheairsheep** [comment]
Use an apk file
