### ISSUE TITLE
WSA audio input device stuck at 8000Hz sample rate

### ISSUE THREAD

**Issue by aleksstevcic** [microsoft/WSA#157]
### Steps to reproduce

No steps to reproduce. This seems to be the default behaviour for WSA.

Editing sampling rates under
-vendor/etc/audio_policy_configuration.xml
-vendor/etc/primary_audio_policy_configuration.xml
both seem to adjust the sampling rates for audio output, but all microphone input still is very low quality (as if it is at 8000Hz).

See files.zip for the two edited files, taken directly from my live WSA instance.

### ✔️ Expected Behavior

WSA should default to 44.1kHz or 48kHz sample rates for input devices.
As a workaround, Input sample rate should be at whatever I decide to set it to under those files.

### ❌ Actual Behavior

Audio input sample rate stays at 8000Hz, even after editing it manually.

### Other Software

[files.zip](https://github.com/microsoft/WSA/files/10096724/files.zip)

### Please specify the version of Windows Subsystem for Android

Windows 11 22H2 / 22623.891

**Comment by nieubank** [comment]
What version of WSA are you using? We've done some tweaking here lately.

**Comment by aleksstevcic** [comment]
Not sure if this is the right version number, but: **2209.40000.26.0**

**Comment by jaholme** [comment]
This is expected to be fixed in the 2210 build available to Windows Insiders on the dev/beta channel.
