### ISSUE TITLE
app UI size problem

### ISSUE THREAD

**Issue by tonycody** [microsoft/WSA#160]
### Is your feature request related to a problem? Please describe

UI font image display problem

The ICONS and fonts are too large to adjust
Tencent Wechat
![image](https://user-images.githubusercontent.com/6773121/205193266-e7440b99-ac6d-439e-826f-d364fca51c9b.png)

Microsoft desktop
![image](https://user-images.githubusercontent.com/6773121/205193353-3a85842b-08b4-4503-922b-528e1f84d3d5.png)

![image](https://user-images.githubusercontent.com/6773121/205193764-5a45e6f5-0b82-4175-a78f-dbf3de04ac21.png)

### Please specify the version of Windows Subsystem for Android

2210.40000.7.0

**Comment by hamza-usmani** [comment]
Hi, this doesn't appear to be a developer-issue, but rather an end-user issue. Please use the Windows Feedback Hub for end-user app issues (Windows key + F)!
