### ISSUE TITLE
Social software Pictures

### ISSUE THREAD

**Issue by tonycody** [microsoft/WSA#161]
### Provide a description of requested docs changes

You cannot select an image from the Windows operating system folder to send in social software. Images can only be found on WSA's own local file system.

![image](https://user-images.githubusercontent.com/6773121/205194078-bfe8357a-c2c0-4095-b9d4-f6e9500c8332.png)

**Comment by jaholme** [comment]
Thanks for the feedback we're tracking filesystem integration with #111
