### ISSUE TITLE
Can't Install WSA from MS Store!

### ISSUE THREAD

**Issue by AbrahimZaman360** [microsoft/WSA#170]
### Steps to reproduce

Showing App Can't Install due to Requirement doesn't meet but My Laptop is latest one everything is ticked green.

### ✔️ Expected Behavior

Installing WSA Application from Store Bug

### ❌ Actual Behavior

Showing Application Can't Install due to requirements not met.
which is totally a bug.

### Other Software

Following:
![image](https://user-images.githubusercontent.com/46282325/206634758-fb682583-d453-4733-b645-807c16326b68.png)

### Please specify the version of Windows Subsystem for Android

latest

**Comment by jaholme** [comment]
What region is your PC set to under Settings > Time & Language > Language & Region?
<img width="706" alt="image" src="https://user-images.githubusercontent.com/27746781/206749037-6a26c8bc-874a-4d8b-9fdb-e215f2fc9986.png">

**Comment by Boing57** [comment]
> 

What region are you using? Currently Windows Subsystem for Android only support certain regions. The only way is just change the region to support region, install WSA and change back to your region you want.

**Comment by AbrahimZaman360** [comment]
From Pakistan.

Ibrahim Zaman,
Programmer.

Web: linktr.ee/AbrahimZaman360
Phone: +923434759529

**Comment by Boing57** [comment]
> 

As I look from regions support, look like Pakistan still not available to download WSA. But I think you can change region to USA on your PC and download Amazon Appstore from Microsoft Store, after that you can change back to your region back.

**Comment by AbrahimZaman360** [comment]
@Boing57 lol, my friend downloaded in same region.

**Comment by AbrahimZaman360** [comment]
Although, I've left #Windows OS.
I'm now """ ubuntu """ user.

**Comment by ShadowOfPripyat** [comment]
well congratulations man, you'll have to use "Waydroid" or "Anbox" to have Android on pc lol

**Comment by Darkhost1999** [comment]
I had this ongoing for a while. Eventually I saw that WSA was removed from the store and is now installed when you install the Amazon appstore.

I do believe this is to be resolved. Don't know how you guys decide to close issues or not.
Can anyone confirm if the issue is still ongoing for them?
