### ISSUE TITLE
Configuration Options, add a button to reverse the swipe direction

### ISSUE THREAD

**Issue by ArthurKun21** [microsoft/WSA#175]
### Is your feature request related to a problem? Please describe

I got a epub reader as an android application on wsa, and uses direction keys via Configuration Options > Swipe arrow keys to control the page. 

But if you want to reader further naturally you have to click the arrow down but the current configuration of the swipe keys for the arrow down is swipe from top to down and that results into going back

while the current configuration feels natural on the touch screen it doesn't feel natural when using keyboard arrows

The android application is Moon+ Reader

Also P.S. please add the ability to copy the version of the WSA for easier reporting

### Describe the solution you'd like

Add a button with an ability to reverse the swipe in the Configuration Options > Swipe with arrow keys

### Please specify the version of Windows Subsystem for Android

2211.40000.7.0

**Comment by jaholme** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community!
