### ISSUE TITLE
Manage developer settings does not appear

### ISSUE THREAD

**Issue by mycall** [microsoft/WSA#176]
### Steps to reproduce

1. Install Amazon Store from Microsoft Store.   Installs WSA as well.
2. Open Windows Subsystem for Android Settings
3. Go to Developer view, switch ON Developer mode and press Manage developer settings

Turning off WSA first doesn't help.

Note I have uninstalled and reinstalled Amazon Store + WSA multiple times without fixing anything.

### ✔️ Expected Behavior

Developer option window should display when working correctly.

### ❌ Actual Behavior

Starting WSA modal window is displayed, then goes away.
Developer options window does not display.

### Other Software

[diagnostics.zip](https://github.com/microsoft/WSA/files/10203574/diagnostics.zip)

### Please specify the version of Windows Subsystem for Android

2209.40000.28.0

**Comment by bansalsushant** [comment]
Hi,

Can you update WSA to the latest version (2302) and let us know if this still repros?

**Comment by nieubank** [comment]
Please file a feedback hub report for this if it still reproduces on 2304

**Comment by MayMih** [comment]
Got that bug again in 2309.
2305 works normal.
