### ISSUE TITLE
Incorrect elevation(shadow) render

### ISSUE THREAD

**Issue by Sanlorng** [microsoft/WSA#178]
### Steps to reproduce

**Hardware:** Nvidia GTX 1660 SUPER
**Windows:**  25262 (DEV)
**WSA Version:** 2211.40000.7.0
in the WSA, the elevation render behavior is diffrent from Android
For example
 Open Files，and click More options
**this is WSA Files Popup**
![WSA Files Popup](https://user-images.githubusercontent.com/26089739/207755258-5511454b-4702-4fe5-8161-4da3435b48b1.png)
**this is Android Phone Popup**
![Android Phone Popup](https://user-images.githubusercontent.com/26089739/207755501-2a25852a-a78b-4338-a25c-3a05156efbe5.jpg)

### ✔️ Expected Behavior

**Expect Popup**
![Android Phone Popup](https://user-images.githubusercontent.com/26089739/207755501-2a25852a-a78b-4338-a25c-3a05156efbe5.jpg)

### ❌ Actual Behavior

![WSA Files Popup](https://user-images.githubusercontent.com/26089739/207755258-5511454b-4702-4fe5-8161-4da3435b48b1.png)

### Please specify the version of Windows Subsystem for Android

2211.40000.7.0

**Comment by nieubank** [comment]
What issue does this cause in your app? After double checking, WSA implements this to spec for freeform tasks and looks comparable on other AOSP 13 devices accounting for screen resolution and dpi scaling.

**Comment by Sanlorng** [comment]
> What issue does this cause in your app? After double checking, WSA implements this to spec for freeform tasks and looks comparable on other AOSP 13 devices accounting for screen resolution and dpi scaling.

cause in my apps, and this issue reproduced in WSA 2210 Version which is running Android 12

**Comment by nieubank** [comment]
If possible it would be helpful if you could provide a min repro with the layout and associated view code that you're using. In addition an "adb bugreport" from both WSA and the Android device you're comparing against would help narrow down what is expected here.

**Comment by Sanlorng** [comment]
> If possible it would be helpful if you could provide a min repro with the layout and associated view code that you're using. In addition an "adb bugreport" from both WSA and the Android device you're comparing against would help narrow down what is expected here.

Ok, i will write a demo and upload source code

**Comment by Sanlorng** [comment]
> If possible it would be helpful if you could provide a min repro with the layout and associated view code that you're using. In addition an "adb bugreport" from both WSA and the Android device you're comparing against would help narrow down what is expected here.

the demo , bugreport, screenshot  link [demo](https://1drv.ms/u/s!AnUe2rLX6jP6gck_RY60EatBFKTX3w?e=rdaAmR) @nieubank

**Comment by nieubank** [comment]
I've investigated this with the repro you've provided. Given two devices with equivalent display specs and app window size and position I'm not seeing a discrepancy between a stock Android device (in this case the Android Emulator built against AOSP 13_1r8) and WSA (also based on 13_r18). 

Based on the bug reports you provided, WSA is at 2560x1440 with 160dpi compared to OnePlus at 1440x3120 with 515dpi. The massive difference in density is potential one explanation for what you're observing (that said, at 2560x1440 160dpi on my setup I'm not seeing the same output, so it is possible that internal versions of WSA have resolved a previous issue here, in which I would encourage you to try this out in the 2301 build once it goes out to preview.


Here are the specs in my repro environment, I'd be curious to see if you observe the same -
**Android 13 Emulator:**
  Display 0:
   **mBaseDisplayInfo**=DisplayInfo{"Built-in Screen", displayId 0", displayGroupId 0, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, FLAG_TRUSTED, real 2560 x 1440, largest app 2560 x 1440, smallest app 2560 x 1440, appVsyncOff 1000000, presDeadline 16666666, mode 1, defaultMode 1, modes [{id=1, width=2560, height=1440, fps=60.000004, alternativeRefreshRates=[]}], hdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON, type INTERNAL, uniqueId "local:4619827259835644672", app 2560 x 1440, density 240 (240.0 x 240.0) dpi, layerStack 0, colorMode 0, supportedColorModes [0], address {port=0, model=0x401cec6a7a2b7b}, deviceProductInfo DeviceProductInfo{name=EMU_display_0, manufacturerPnpId=GGL, productId=1, modelYear=null, manufactureDate=ManufactureDate{week=27, year=2006}, connectionToSinkType=0}, removeMode 0, refreshRateOverride 0.0, brightnessMinimum 0.0, brightnessMaximum 1.0, brightnessDefault 0.39763778, installOrientation ROTATION_0}
    **mOverrideDisplayInfo**=DisplayInfo{"Built-in Screen", displayId 0", displayGroupId 0, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, FLAG_TRUSTED, real 2560 x 1440, largest app 2560 x 2560, smallest app 1440 x 1440, appVsyncOff 1000000, presDeadline 16666666, mode 1, defaultMode 1, modes [{id=1, width=2560, height=1440, fps=60.000004, alternativeRefreshRates=[]}], hdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON, type INTERNAL, uniqueId "local:4619827259835644672", app 2560 x 1440, density 240 (240.0 x 240.0) dpi, layerStack 0, colorMode 0, supportedColorModes [0], address {port=0, model=0x401cec6a7a2b7b}, deviceProductInfo DeviceProductInfo{name=EMU_display_0, manufacturerPnpId=GGL, productId=1, modelYear=null, manufactureDate=ManufactureDate{week=27, year=2006}, connectionToSinkType=0}, removeMode 0, refreshRateOverride 0.0, brightnessMinimum 0.0, brightnessMaximum 1.0, brightnessDefault 0.39763778, installOrientation ROTATION_0}

**RootTask** id=15 bounds=[971,144][1589,1242] displayId=0 userId=0
 configuration={1.0 310mcc260mnc [en_US] ldltr sw412dp w412dp h732dp 240dpi nrml long port finger qwerty/v/v dpad/v winConfig={ mBounds=Rect(971, 144 - 1589, 1242) mAppBounds=Rect(971, 144 - 1589, 1242) mMaxBounds=Rect(0, 0 - 2560, 1440) mDisplayRotation=ROTATION_0 mWindowingMode=freeform mDisplayWindowingMode=freeform mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0} s.10 fontWeightAdjustment=0}
  taskId=15: com.sanlorng.elevationdemo/com.sanlorng.elevationdemo.MainActivity bounds=[971,144][1589,1242] userId=0 visible=true topActivity=ComponentInfo{com.sanlorng.elevationdemo/com.sanlorng.elevationdemo.MainActivity}

**Android 13 WSA:**
Display 0:
    **mBaseDisplayInfo**=DisplayInfo{"Built-in Screen", displayId 0", displayGroupId 0, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, FLAG_TRUSTED, real 2560 x 1440, largest app 2560 x 1440, smallest app 2560 x 1440, appVsyncOff 2000000, presDeadline 6944444, mode 1, defaultMode 1, modes [{id=1, width=2560, height=1440, fps=144.00002, alternativeRefreshRates=[]}], hdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON, type INTERNAL, uniqueId "local:100", app 2560 x 1440, density 240 (240.0 x 240.0) dpi, layerStack 0, colorMode 0, supportedColorModes [0], address {port=100}, deviceProductInfo null, removeMode 0, refreshRateOverride 0.0, brightnessMinimum 0.0, brightnessMaximum 1.0, brightnessDefault 0.39763778, installOrientation ROTATION_0}
    **mOverrideDisplayInfo**=DisplayInfo{"Built-in Screen", displayId 0", displayGroupId 0, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, FLAG_TRUSTED, real 2560 x 1440, largest app 2560 x 2560, smallest app 1440 x 1440, appVsyncOff 2000000, presDeadline 6944444, mode 1, defaultMode 1, modes [{id=1, width=2560, height=1440, fps=144.00002, alternativeRefreshRates=[]}], hdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON, type INTERNAL, uniqueId "local:100", app 2560 x 1440, density 240 (240.0 x 240.0) dpi, layerStack 0, colorMode 0, supportedColorModes [0], address {port=100}, deviceProductInfo null, removeMode 0, refreshRateOverride 0.0, brightnessMinimum 0.0, brightnessMaximum 1.0, brightnessDefault 0.39763778, installOrientation ROTATION_0}

**RootTask** id=71 bounds=[974,144][1589,1242] displayId=0 userId=0
 configuration={1.0 ?mcc?mnc [en_US] ldltr sw410dp w410dp h732dp 240dpi nrml long port finger qwerty/v/v -nav/h winConfig={ mBounds=Rect(974, 144 - 1589, 1242) mAppBounds=Rect(974, 144 - 1589, 1242) mMaxBounds=Rect(0, 0 - 2560, 1440) mDisplayRotation=ROTATION_0 mWindowingMode=freeform mDisplayWindowingMode=freeform mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0} s.15 fontWeightAdjustment=0}
  taskId=71: com.sanlorng.elevationdemo/com.sanlorng.elevationdemo.MainActivity bounds=[974,144][1589,1242] userId=0 visible=true topActivity=ComponentInfo{com.sanlorng.elevationdemo/com.sanlorng.elevationdemo.MainActivity}

![WSA](https://user-images.githubusercontent.com/7259210/207911346-da5d09e9-a7f4-4dad-9dfc-8b472c7ae30f.png)
![Emulator](https://user-images.githubusercontent.com/7259210/207911350-f00cd00d-7c2f-4b5b-ab61-266ac3cbea0c.png)

**Comment by Sanlorng** [comment]
> I've investigated this with the repro you've provided. Given two devices with equivalent display specs and app window size and position I'm not seeing a discrepancy between a stock Android device (in this case the Android Emulator built against AOSP 13_1r8) and WSA (also based on 13_r18). 
> 
> Based on the bug reports you provided, WSA is at 2560x1440 with 160dpi compared to OnePlus at 1440x3120 with 515dpi. The massive difference in density is potential one explanation for what you're observing (that said, at 2560x1440 160dpi on my setup I'm not seeing the same output, so it is possible that internal versions of WSA have resolved a previous issue here, in which I would encourage you to try this out in the 2301 build once it goes out to preview.
> 
> 
> Here are the specs in my repro environment, I'd be curious to see if you observe the same -
> **Android 13 Emulator:**
>   Display 0:
>    **mBaseDisplayInfo**=DisplayInfo{"Built-in Screen", displayId 0", displayGroupId 0, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, FLAG_TRUSTED, real 2560 x 1440, largest app 2560 x 1440, smallest app 2560 x 1440, appVsyncOff 1000000, presDeadline 16666666, mode 1, defaultMode 1, modes [{id=1, width=2560, height=1440, fps=60.000004, alternativeRefreshRates=[]}], hdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON, type INTERNAL, uniqueId "local:4619827259835644672", app 2560 x 1440, density 240 (240.0 x 240.0) dpi, layerStack 0, colorMode 0, supportedColorModes [0], address {port=0, model=0x401cec6a7a2b7b}, deviceProductInfo DeviceProductInfo{name=EMU_display_0, manufacturerPnpId=GGL, productId=1, modelYear=null, manufactureDate=ManufactureDate{week=27, year=2006}, connectionToSinkType=0}, removeMode 0, refreshRateOverride 0.0, brightnessMinimum 0.0, brightnessMaximum 1.0, brightnessDefault 0.39763778, installOrientation ROTATION_0}
>     **mOverrideDisplayInfo**=DisplayInfo{"Built-in Screen", displayId 0", displayGroupId 0, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, FLAG_TRUSTED, real 2560 x 1440, largest app 2560 x 2560, smallest app 1440 x 1440, appVsyncOff 1000000, presDeadline 16666666, mode 1, defaultMode 1, modes [{id=1, width=2560, height=1440, fps=60.000004, alternativeRefreshRates=[]}], hdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON, type INTERNAL, uniqueId "local:4619827259835644672", app 2560 x 1440, density 240 (240.0 x 240.0) dpi, layerStack 0, colorMode 0, supportedColorModes [0], address {port=0, model=0x401cec6a7a2b7b}, deviceProductInfo DeviceProductInfo{name=EMU_display_0, manufacturerPnpId=GGL, productId=1, modelYear=null, manufactureDate=ManufactureDate{week=27, year=2006}, connectionToSinkType=0}, removeMode 0, refreshRateOverride 0.0, brightnessMinimum 0.0, brightnessMaximum 1.0, brightnessDefault 0.39763778, installOrientation ROTATION_0}
> 
> **RootTask** id=15 bounds=[971,144][1589,1242] displayId=0 userId=0
>  configuration={1.0 310mcc260mnc [en_US] ldltr sw412dp w412dp h732dp 240dpi nrml long port finger qwerty/v/v dpad/v winConfig={ mBounds=Rect(971, 144 - 1589, 1242) mAppBounds=Rect(971, 144 - 1589, 1242) mMaxBounds=Rect(0, 0 - 2560, 1440) mDisplayRotation=ROTATION_0 mWindowingMode=freeform mDisplayWindowingMode=freeform mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0} s.10 fontWeightAdjustment=0}
>   taskId=15: com.sanlorng.elevationdemo/com.sanlorng.elevationdemo.MainActivity bounds=[971,144][1589,1242] userId=0 visible=true topActivity=ComponentInfo{com.sanlorng.elevationdemo/com.sanlorng.elevationdemo.MainActivity}
> 
> **Android 13 WSA:**
> Display 0:
>     **mBaseDisplayInfo**=DisplayInfo{"Built-in Screen", displayId 0", displayGroupId 0, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, FLAG_TRUSTED, real 2560 x 1440, largest app 2560 x 1440, smallest app 2560 x 1440, appVsyncOff 2000000, presDeadline 6944444, mode 1, defaultMode 1, modes [{id=1, width=2560, height=1440, fps=144.00002, alternativeRefreshRates=[]}], hdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON, type INTERNAL, uniqueId "local:100", app 2560 x 1440, density 240 (240.0 x 240.0) dpi, layerStack 0, colorMode 0, supportedColorModes [0], address {port=100}, deviceProductInfo null, removeMode 0, refreshRateOverride 0.0, brightnessMinimum 0.0, brightnessMaximum 1.0, brightnessDefault 0.39763778, installOrientation ROTATION_0}
>     **mOverrideDisplayInfo**=DisplayInfo{"Built-in Screen", displayId 0", displayGroupId 0, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, FLAG_TRUSTED, real 2560 x 1440, largest app 2560 x 2560, smallest app 1440 x 1440, appVsyncOff 2000000, presDeadline 6944444, mode 1, defaultMode 1, modes [{id=1, width=2560, height=1440, fps=144.00002, alternativeRefreshRates=[]}], hdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON, type INTERNAL, uniqueId "local:100", app 2560 x 1440, density 240 (240.0 x 240.0) dpi, layerStack 0, colorMode 0, supportedColorModes [0], address {port=100}, deviceProductInfo null, removeMode 0, refreshRateOverride 0.0, brightnessMinimum 0.0, brightnessMaximum 1.0, brightnessDefault 0.39763778, installOrientation ROTATION_0}
> 
> **RootTask** id=71 bounds=[974,144][1589,1242] displayId=0 userId=0
>  configuration={1.0 ?mcc?mnc [en_US] ldltr sw410dp w410dp h732dp 240dpi nrml long port finger qwerty/v/v -nav/h winConfig={ mBounds=Rect(974, 144 - 1589, 1242) mAppBounds=Rect(974, 144 - 1589, 1242) mMaxBounds=Rect(0, 0 - 2560, 1440) mDisplayRotation=ROTATION_0 mWindowingMode=freeform mDisplayWindowingMode=freeform mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0} s.15 fontWeightAdjustment=0}
>   taskId=71: com.sanlorng.elevationdemo/com.sanlorng.elevationdemo.MainActivity bounds=[974,144][1589,1242] userId=0 visible=true topActivity=ComponentInfo{com.sanlorng.elevationdemo/com.sanlorng.elevationdemo.MainActivity}
> 
> ![WSA](https://user-images.githubusercontent.com/7259210/207911346-da5d09e9-a7f4-4dad-9dfc-8b472c7ae30f.png)
> ![Emulator](https://user-images.githubusercontent.com/7259210/207911350-f00cd00d-7c2f-4b5b-ab61-266ac3cbea0c.png)
> 

Thanks ，i will wait the 2301 preview version

**Comment by Sanlorng** [comment]
@nieubank this issue repro in **2309.4000.10.0**

![image](https://github.com/microsoft/WSA/assets/26089739/c18855f8-e055-4409-97e7-067d26f7c475)
