### ISSUE TITLE
Any chance to run passcode protected apps like Revolut?

### ISSUE THREAD

**Issue by patrik-martinko** [microsoft/WSA#187]
### Is your feature request related to a problem? Please describe

I installed Revolut via adb.
![image](https://user-images.githubusercontent.com/12855743/209430529-35410643-207f-462f-93d3-ecd6c1a0d2f7.png)

### Describe the solution you'd like

Able to use passcode protected apps.

### Please specify the version of Windows Subsystem for Android

2209.40000.28.0

**Comment by yonggamer** [comment]
#139

**Comment by hamza-usmani** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community!
