### ISSUE TITLE
React Native perf monitor overlay window covers the whole screen

### ISSUE THREAD

**Issue by yume-chan** [microsoft/WSA#188]
### Steps to reproduce

2. Enable "Support single machine UI automation..." in "Developer" page of "Windows Subsystem for Android Settings" app.
1. Connect ADB to WSA `adb connect 127.0.0.1:58526`

## Create an Expo app

```sh
yarn create expo-app my-app
cd my-app
yarn android
```

Expo is a framework for quickly create, develop and debug React Native apps, and doesn't require Android SDK when used with the Expo Go app already installed on device. The performance monitor function in Expo Go is exactly same as the one from React Native developer menu.

## Open React Native performance monitor

6. Execute `adb shell input keyevent 82` in Windows Terminal
7. In the opened Expo Go window, click "Show Performance Monitor"

When opening this the first time, it may request the display over other apps permission, grant it to Expo Go, then minimize or close the Android settings app.

### ✔️ Expected Behavior

I can still interact with windows on my screen.

### ❌ Actual Behavior

I can't use mouse to interact with any Windows apps. Android apps has some reaction to mouse input, but the cursor position is incorrect.

I can switch to other windows using <kbd>Alt</kbd> + <kbd>Tab</kbd>, then I can use my mouse in that window.

https://user-images.githubusercontent.com/1330321/209565696-abf6ef51-8b67-42d6-9dff-c24fa3a83369.mp4

### Other Software

Node.js v18.12.1 on Windows (https://nodejs.org)
Yarn 1.22.19 on Windows (`npm i -g yarn`)
Expo Go in WSA  (https://expo.dev/tools, APK can be found on the page)

### Please specify the version of Windows Subsystem for Android

2210.40000.7.0

**Comment by bansalsushant** [comment]
Hi,

You seem to be on WSA version 2210, which is an older version. The latest version currently available is 2301, it with a lot of optimizations and fixes. Can you update and check if the issue still exists?
Please let us know if the issue still exists, we will investigate.

**Comment by yume-chan** [comment]
It's still reproducible in version 2301.40000.4.0
