### ISSUE TITLE
The text box is highlighted and disappears on mouse over.

### ISSUE THREAD

**Issue by TheGod05** [microsoft/WSA#189]
### Steps to reproduce

The text box in which the texts are clicked is automatically highlighted and disappears on mouseover. It comes back when the mouse is hovered away

![image](https://user-images.githubusercontent.com/92083430/209798006-0aa7b4f8-6178-495c-9301-2586b4900dba.png)

### ✔️ Expected Behavior

The text box should not be highlighted

### ❌ Actual Behavior

The text boxes are highlighted

### Other Software

WSA settings app.

### Please specify the version of Windows Subsystem for Android

2210.40000.7.0

**Comment by hamza-usmani** [comment]
Hi, are you seeing this behavior only in the WSA Settings app when Windows is in high contrast mode?

**Comment by TheGod05** [comment]
> Hi, are you seeing this behavior only in the WSA Settings app when Windows is in high contrast mode?

No, it happens on other installed apps as well.

**Comment by nieubank** [comment]
This appears to be an app issue. We'll need a feedback hub report in order to properly investigate.
