### ISSUE TITLE
Support OTA

### ISSUE THREAD

**Issue by AnswerZhao** [microsoft/WSA#191]
### Is your feature request related to a problem? Please describe

WSA supports OTA, such as update Android 12 to Android 13 with keeping user data

### Describe the solution you'd like

WSA supports OTA, such as update Android 12 to Android 13 with keeping user data

### Please specify the version of Windows Subsystem for Android

2207

**Comment by nieubank** [comment]
User data is persisted across all WSA updates. If you've encountered an issue where this was not the case, please file a feedback hub report so we can investigate.

**Comment by nieubank** [comment]
Closing with no actionable repro.
