### ISSUE TITLE
Kernel Source Branch No Longer Available

### ISSUE THREAD

**Issue by nbetcher** [microsoft/WSA#192]
### Steps to reproduce

The source branch of the WSA repository is no longer available, and as such, there is no public version of the WSA kernel source code. Looking at https://github.com/WSA-Community/WSA-Linux-Kernel/tree/source you can see that their most recent synchronized version is only from March, 2022 -- version `5.10.66-windows-subsystem-for-android-20220323` and the kernel in the most current WSA release is `5.10.117-windows-subsystem-for-android-20220804`.

For some reason, the WSA kernel doesn't include Netfilter NAT table support, despite most physical/dedicated Android devices having support for it built in (and many applications, most root, expecting it). In an attempt to recompile the kernel with NF NAT table support, I came across this issue. Without knowing more about the specific changes between `.66` and `.117` (including Microsoft patches), there might be consequences to compiling and rolling back a `5.10.117`-based full system image to a contain a `5.10.66` kernel.

I'm not sure what the big fuss is all about (for the branch to have been wiped off the face of the internet), but I'm likely not the only one that would appreciate it being restored and updated to `.117`. Thanks.

### ✔️ Expected Behavior

Routine and timely disclosure of the GPL'ed WSA kernel source code on Microsoft's public WSA repository.

### ❌ Actual Behavior

No GPL source for Microsoft's Windows Subsystem for Android kernel on their public WSA repository. In fact, it was previously available here; now it is not, and I have not been able to find any other official source, including for previous releases.

### Other Software

Filed as bug report since GPL source disclosure isn't really a feature request and feature requests may not garnish the attention needed for a timely GPL source disclosure. Also, since the feedback hub appears to be a blackhole, I didn't feel that was appropriate either.

### Please specify the version of Windows Subsystem for Android

2208.40000.5.0

**Comment by nieubank** [comment]
> ### Steps to reproduce
> 
> 
> 
> The source branch of the WSA repository is no longer available, and as such, there is no public version of the WSA kernel source code. Looking at https://github.com/WSA-Community/WSA-Linux-Kernel/tree/source you can see that their most recent synchronized version is only from March, 2022 -- version `5.10.66-windows-subsystem-for-android-20220323` and the kernel in the most current WSA release is `5.10.117-windows-subsystem-for-android-20220804`.
> 
> 
> 
> For some reason, the WSA kernel doesn't include Netfilter NAT table support, despite most physical/dedicated Android devices having support for it built in (and many applications, most root, expecting it). In an attempt to recompile the kernel with NF NAT table support, I came across this issue. Without knowing more about the specific changes between `.66` and `.117` (including Microsoft patches), there might be consequences to compiling and rolling back a `5.10.117`-based full system image to a contain a `5.10.66` kernel.
> 
> 
> 
> I'm not sure what the big fuss is all about (for the branch to have been wiped off the face of the internet), but I'm likely not the only one that would appreciate it being restored and updated to `.117`. Thanks.
> 
> 
> 
> ### ✔️ Expected Behavior
> 
> 
> 
> Routine and timely disclosure of the GPL'ed WSA kernel source code on Microsoft's public WSA repository.
> 
> 
> 
> ### ❌ Actual Behavior
> 
> 
> 
> No GPL source for Microsoft's Windows Subsystem for Android kernel on their public WSA repository. In fact, it was previously available here; now it is not, and I have not been able to find any other official source, including for previous releases.
> 
> 
> 
> ### Other Software
> 
> 
> 
> Filed as bug report since GPL source disclosure isn't really a feature request and feature requests may not garnish the attention needed for a timely GPL source disclosure. Also, since the feedback hub appears to be a blackhole, I didn't feel that was appropriate either.
> 
> 
> 
> ### Please specify the version of Windows Subsystem for Android
> 
> 
> 
> 2208.40000.5.0

Thanks for reaching out regarding the WSA kernel source availability. Previous kernel sources are officially available at [https://3rdpartycode.microsoft.com](https://3rdpartycode.microsoft.com). We’ve been moving to publishing kernel source on GitHub and are aiming to push the latest version on GitHub next week.

**Comment by nieubank** [comment]
The latest kernel sources are now available on GitHub at [https://github.com/microsoft/WSA-Linux-Kernel](https://github.com/microsoft/WSA-Linux-Kernel)

Each version is tagged, e.g. [android-lts/latte/5.10.117.4](https://github.com/microsoft/WSA-Linux-Kernel/releases/tag/android-lts%2Flatte%2F5.10.117.4).
