### ISSUE TITLE
"Turn off" does no effect

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/WSA#193]
### Steps to reproduce

Clicking "Turn off" in WSA settings does no effect for me.

I click on it, a spinning wheel shows for a quick bit, but then the text on the button does not change. Repeating clicks does nothing as well.

Either it got off and then the status is not reported correctly, or there was some problem during turning off, but the error message was not reported.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/1041752/210089480-f24b59c2-c9dd-449c-a8bf-86cd0977d729.png">

### ✔️ Expected Behavior

No effect

(Unrelated: Version of WSA should also be selectable/copyable)

### ❌ Actual Behavior

Button text should change to "Turn on". There should be a clear status displayed (on or off), and there should be an error message/log if turning off failed for some reason.

### Other Software

Windows 11 build 22621.963

### Please specify the version of Windows Subsystem for Android

2209.40000.28.0

**Comment by hamza-usmani** [comment]
Hi, are Android apps on your device being terminated? Is the WSA process in task manager unchanged when you click "turn off"?

@jaholme for visibility.

**Comment by vadimkantorov** [comment]
I could not find WSA process at all. Win11 task manager doesn't have process/task filter text box. I checked all processes, did not find anything WSA-related, but I may have missed something.

It can be that WSA settings app can't communicate with WSA service to tell it so switch off because it's already switched off :) so switching off fails. But settings app must be consistent with process state.

If you tell me how to find logs of WSA settings app, I can look them up

**Comment by Darkhost1999** [comment]
> If you tell me how to find logs of WSA settings app, I can look them up

Inside the feedback hub is a special record option that'll record what is needed for this issue. Linking that issue here will improve visibility and will increase chances of successfully solving the issue.
From the sounds of things turn off works and the issue is purely cosmetic. Wanting the button to change to turn on when WSA is off.

**Comment by AJolly** [comment]
I'd agree - it's unclear if WSA has been turned off or not.  (It'd also be great if there was a command line flag to turn WSA on/off)

**Comment by nieubank** [comment]
Tracking under feedback hub.
