### ISSUE TITLE
Missing Google Play Services

### ISSUE THREAD

**Issue by vrsovin** [microsoft/WSA#197]
### Is your feature request related to a problem? Please describe

I think it is a usage problem, because a lot of useful apps requires Google Play Services to work, like Google Apps, bank apps, and others. I want WSA for useful things, not for random and questionable games and apps from Amazon Appstore.

### Describe the solution you'd like

Implemente Google Play Services and Google Play Store as default or as an option for downloading WSA, as it happens on WSL with more than one option for distros to choose from.

### Describe alternatives you've considered

I downloaded Aurora Store to test more useful apps, but the most of useful apps don't work without Play Services APIs. I tried some bank apps, some google apps and others, but they don't work without Play Services APIs. The only way to get it working is changing the kernel or using a custom unofficially WSA with preloaded Google Play Services, but it is not officially and I want to install WSA without doing nothing more than clicking on "Install" on MS Store.

### Please specify the version of Windows Subsystem for Android

2209.40000.28.0

**Comment by infinitepower18** [comment]
We all wish this but most likely it will never happen because Google never supports any of Microsoft's initiatives, that's why they went out of their way to make their own Play Games client instead of supporting WSA.

I agree that in its current state the Amazon Appstore is absolute garbage and I find very few notable apps on the store like Tiktok and BBC News. Let's see if the situation improves in the coming months as WSA was only opened up to more countries very recently.

Also, developers who officially release apps for WSA are making them with Amazon's services in mind. Changing this suddenly would probably create some backlash.

**Comment by infinitepower18** [comment]
Also, it's funny that their Windows 11 2022 update trailer from months ago features the Twitter app but isn't actually present in the store itself the last time I checked.

<img width="1041" alt="Screenshot 2023-01-02 at 5 52 13 pm" src="https://user-images.githubusercontent.com/44692189/210265079-53fdf5dd-a578-4741-98aa-56e4ae47e3b6.png">

<img width="1034" alt="Screenshot 2023-01-02 at 5 52 27 pm" src="https://user-images.githubusercontent.com/44692189/210265073-92157c15-f720-407a-8189-4ea0efad3479.png">

**Comment by Boing57** [comment]
Most of delivery apps also require Google Play Service to use Google Maps. Also, there are many games that require google play services to play. There are too many apps require Google Play Service.
![image](https://user-images.githubusercontent.com/78803559/210295518-98226726-f87c-48e3-9365-e329f4dc6428.png)
![image](https://user-images.githubusercontent.com/78803559/210295522-871b2a9e-818a-4bff-a087-eefa596619c4.png)

**Comment by infinitepower18** [comment]
You could probably contact the developers of those apps and request a an official WSA release on Amazon AppStore.

This reminds me of the situation with iOS apps on Mac, most of the developers opted out of this and have no interest in making their iOS apps available on Mac.

**Comment by Wavesolid** [comment]
Agree with this issue, I think Microsoft need to find the solution. Contacting each apps developer is wasting time, it's surely painful if I need to contact them one by one whenever I want to use their apps.

**Comment by hamza-usmani** [comment]
Duplicate feature request: #74
