### ISSUE TITLE
Google Play Store and Google Play Services

### ISSUE THREAD

**Issue by Ismail01Hub** [microsoft/WSA#201]
### Describe the solution you'd like

Some apps I installed require google play services to run. It will be helpful if the subsystem has Google play services and, hopefully, Google Play Store.

### Please specify the version of Windows Subsystem for Android

2211.40000.11.0

**Comment by Boing57** [comment]
#74

**Comment by dabhattimsft** [comment]
Hi, please see our [Frequently Asked Questions](https://github.com/microsoft/WSA/discussions/51) which address this topic.

**Comment by bolandnick18** [comment]
I would like to see this option available and I don’t like Amazon AppStore at all! 

Why did you choose Amazon App Store at the beginning of the released?

**Comment by bolandnick18** [comment]
I am requesting this feature two
