### ISSUE TITLE
Not working with Nvidia gpus

### ISSUE THREAD

**Issue by MikiTime** [microsoft/WSA#202]
### Steps to reproduce

Doesnt launch apps with nvidia gpu's 

### ✔️ Expected Behavior

The app to launch

### ❌ Actual Behavior

It didnt launch and i had to switch to intel gpu 

### Other Software

Windows 11, Nvidia rtx 3060 gpu, CPU   Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   

### Please specify the version of Windows Subsystem for Android

2210.40000.7.0

**Comment by nieubank** [comment]
If this is your app that you're developing, could you please provide additional details, e.g. what app, error messages in logcat, bugreport, etc.  

Otherwise, please file a feedback hub report.

**Comment by jaholme** [comment]
@MikiTime Can you upgrade to 2211.40000.7.0 which is publicly available and let us know if this resolves the issues you are seeing with the Nvidia GPU

**Comment by jaholme** [comment]
@rp1231 Can you file a Feedback Hub report (Windows Key + F) under the category Apps > Windows Subsystem for Android.
If you can also click "Start recording" and attempt to launch an app with the Nvidia GPU
<img width="643" alt="image" src="https://user-images.githubusercontent.com/27746781/215534787-72c86e43-af5e-424e-aa64-85c9ac4fbe26.png">
Please share a link to your feedback report and this will provide us with the necessary logs to be able to determine why WSA is unable to start.

**Comment by jaholme** [comment]
Also, I misquoted the version number above, it should have been 2211.40000.11.0. If you're able to try on this build it would be helpful as we believe we have a change to address some of these startup issues.

**Comment by MustardChef** [comment]
This is still a huge problem for users with Nvidia RTX and GTX GPUs + Windows Subsystem For Android 2211.40000.11.0
The only solution to this problem being switching to Microsoft Basic Renderer or another GPU/iGPU.

**Comment by nieubank** [comment]
> This is still a huge problem for users with Nvidia RTX and GTX GPUs + Windows Subsystem For Android v2211.40000.11.0
> The only solution to this problem for the time being, is switching to Microsoft Basic Renderer or another GPU/iGPU.

To confirm, it still doesn't launch if you explicitly select the Nvidia GPU in settings (and not leaving it on dynamic)?

We still haven't received a feedback hub report link here for this issue so we're limited in the ability to help resolve it since we haven't been able to repro on our Nvidia devices.

**Comment by MustardChef** [comment]
> > This is still a huge problem for users with Nvidia RTX and GTX GPUs + Windows Subsystem For Android v2211.40000.11.0
> > The only solution to this problem for the time being, is switching to Microsoft Basic Renderer or another GPU/iGPU.
> 
> To confirm, it still doesn't launch if you explicitly select the Nvidia GPU in settings (and not leaving it on dynamic)?
> 
> We still haven't received a feedback hub report link here for this issue so we're limited in the ability to help resolve it since we haven't been able to repro on our Nvidia devices.

Yes, when dynamic is selected (which reads "Dynamic (currently NVIDIA GeForce RTX 3060)") or the GPU is explicitly selected: it does not launch and immediately crashes. Initially, I suspected it was an error with a corrupted installation. I will file a feedback hub report.

**Comment by martin-honnen** [comment]
Here is my link to a feedback report https://aka.ms/AAjsnsj. On my Windows 11 laptop WSA apps don't start if the NVIDIA graphics card GeForce RTX 3060 is used.

**Comment by jaholme** [comment]
> Here is my link to a feedback report https://aka.ms/AAjsnsj. On my Windows 11 laptop WSA apps don't start if the NVIDIA graphics card GeForce RTX 3060 is used.

Does it work if you explicitly select the RTX 3060 driver, or are you using the basic render driver when WSA is able to work?

**Comment by martin-honnen** [comment]
I have tested in more detail now, after the requests and looking in more detail at the various options: 

The default WSA graphics rendering setting seems to be `dynamic (with listing a GPU, which on this system is the Nvidia GeForce RTX 3060)`, with that setting WSA application don't come up, if you have reset it for the first app you are trying to start a window appears saying e.g. "Windows Subsystem for Android is being started" (my translation of the German message my German version of Windows shows) but that Window then vanishes and nothing more happens, any further attempts to start the same app or another don't show any window; task manager indeed show at least two entries related to WSA (VmmemWSA and Windows Subsystem for Android).

Any other remaining option, which here are using the Nvidia card explicitly or the Intel Iris Xe explicitly or that Microsoft Basic Render Driver explicitly, do make WSA apps show up.

I will next try to find the Windows setting that currently makes Nvidia the preferred card showing up under dynamic and test again and report back.

**Comment by martin-honnen** [comment]
I had to change a setting in Nvidia system control to make the internal GPU the preferred one, that way in WSA under the default "dynamic" setting the Intel Iris Xe graphics shows up and with that setting all four WSA graphics options (i.e. dynamic (currently Intel Iris Xe), Intel Iris Xe, Nvidia GeForce RTX 3060, Microsoft Basic Render Driver) do let WSA apps show up and run.

**Comment by jaholme** [comment]
@martin-honnen @MustardChef @rp1231 We've released the 2302 WSA build which should address some of these issues. Can you report back if the default settings of "High Performance" works correctly for you?

**Comment by MustardChef** [comment]
> @martin-honnen @MustardChef @rp1231 We've released the 2302 WSA build which should address some of these issues. Can you report back if the default settings of "High Performance" works correctly for you?

It has indeed been fixed.
Thank you to the WSA team for their hard work!

**Comment by martin-honnen** [comment]
> We've released the 2302 WSA build which should address some of these issues.

@jaholme, would Windows update or updating my Windows/Microsoft app store apps install that WSA 2302 build? I looked for updates both ways but none were installed and my WSA settings show 2301.40000.7.0. Or is there a difference between US versions of WSA and international (in my case German) ones?

**Comment by nieubank** [comment]
> Also just out of curiosity would like to know what the problem was,
> If it's not overly technical or difficult to explain.

Without going into too many details here, WSA issues multiple process for graphics rendering, one in a protected process that handles all the virtualization coming from Android and another for presentation on Windows. In multi-gpu configurations there was one D3D device that was default initialized rather than using the explicit adapter which could get users into this state.

**Comment by jaholme** [comment]
> > We've released the 2302 WSA build which should address some of these issues.
> 
> @jaholme, would Windows update or updating my Windows/Microsoft app store apps install that WSA 2302 build? I looked for updates both ways but none were installed and my WSA settings show 2301.40000.7.0. Or is there a difference between US versions of WSA and international (in my case German) ones?

We typically roll out updates to the Windows Insider Program and [WSA Preview Program](https://learn.microsoft.com/en-us/windows/android/wsa/preview-program) first prior to releasing them to the general audience.  If you're not in one of those preview programs the update will start being available over the next few weeks.
