### ISSUE TITLE
Location Timestamp Number Format

### ISSUE THREAD

**Issue by jake-brown-maps** [microsoft/WSA#204]
### Steps to reproduce

We are seeing an error with the getTime method for location: 

https://developer.android.com/reference/android/location/Location#getTime()

It should be a unix epoch formatted number but it looks like it's actually a Windows NT formatted number.

### ✔️ Expected Behavior

android.location.Location.getTime() unix epoch formatted number

### ❌ Actual Behavior

android.location.Location.getTime() returns a Windows NT formatted number

### Please specify the version of Windows Subsystem for Android

2211.40000.7.0

**Comment by jaholme** [comment]
We'll investigate and follow up on this. Thank you for bringing this to our attention.
