### ISSUE TITLE
WSA always reporting that virtualization is disabled

### ISSUE THREAD

**Issue by solomoncyj** [microsoft/WSA#208]
### Steps to reproduce

enable virtualization in bios and windows feature.
I also tried to see if it was the hypervisor platform option that was enabled as well, but disabling them/ enabling them in any order did not help.

### ✔️ Expected Behavior

the app to start 

### ❌ Actual Behavior

![image](https://user-images.githubusercontent.com/74647769/212539494-d1c19fb1-bd64-40ba-bb95-7b75c5ac0dab.png)

### Please specify the version of Windows Subsystem for Android

2211.40000.11.0

**Comment by MustardChef** [comment]
I also have encountered this problem, but it seems to be an issue not of Windows System for Android, but with the PC.

Check if Virualization is properly enabled in the BIOS and in Windows following the [guide provided by Microsoft ](https://support.microsoft.com/en-us/windows/enable-virtualization-on-windows-11-pcs-c5578302-6e43-4b4b-a449-8ced115f58e1). 

If you have confimed that everything is enabled and you still encounter the problem, the solution I found to this exact problem was to: Disable Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, then restart. After re-enabling these features and restarting a second time.
Hope this help!

**Comment by jaholme** [comment]
Hi, could you provide more logs by submitting a Feedback Hub report (Windows key + F) under Apps > Windows Subsystem for Android, including a repro of launching WSA?

Also, ensure that you have Virtual Machine Platform enabled in Windows Optional Features and do not have Control Flow Guard disabled.

**Comment by solomoncyj** [comment]
Ok I got it to work. I had to use bcedit for some reason

**Comment by jaholme** [comment]
What did you need to change using bcdedit?  I would like to ensure our documentation is updated to cover this case for future users who hit this error.

**Comment by MustardChef** [comment]
> What did you need to change using bcdedit? I would like to ensure our documentation is updated to cover this case for future users who hit this error.



> What did you need to change using bcdedit? I would like to ensure our documentation is updated to cover this case for future users who hit this error.

It seems, for some unknown reason, that the command: 
```cmd
bcdedit /set hypervisorlaunchtype auto
```
seems to fix the problem

**Comment by solomoncyj** [comment]
yeah that command

**Comment by solomoncyj** [comment]
it think i had to resort to that command as I had to turn off hyper-v when an application need it to be really off

**Comment by solomoncyj** [comment]
Documentation updated?

**Comment by Alferro909** [comment]
> > What did you need to change using bcdedit? I would like to ensure our documentation is updated to cover this case for future users who hit this error.
> 
> > What did you need to change using bcdedit? I would like to ensure our documentation is updated to cover this case for future users who hit this error.
> 
> It seems, for some unknown reason, that the command:
> 
> ```batchfile
> bcdedit /set hypervisorlaunchtype auto
> ```
> 
> seems to fix this problem for some people.

can confirm this works.

**Comment by terax6669** [comment]
I had to reboot after executing the `bcdedit` command, but it helped.

Where is the "official documentation" for this?
