### ISSUE TITLE
Comic Book Mime Types

### ISSUE THREAD

**Issue by hgourvest** [microsoft/WSA#209]
### Is your feature request related to a problem? Please describe

As it is expected to be able to open files located on the host system in the next release, I anticipate and ask you to be careful to manage two Type Mimes currently managed by ChromeOS and which are specific to Comic Books.

### Describe the solution you'd like

The new mime types to support are:
application/vnd.comicbook+zip
application/vnd.comicbook-rar

They correspond to the file extensions cbz and cbr

```
<intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="content" />

                <data android:mimeType="application/vnd.comicbook+zip"/>
                <data android:mimeType="application/vnd.comicbook-rar"/>
</intent-filter>
```

### Describe alternatives you've considered

These are the old historical mime types that are supported by all comic reader apps:
application/x-cbr
application/x-cbz

These two are quite rare and have no official alternatives, they are 7zip and Tar archives.
application/x-cb7
application/x-cbt

### Please specify the version of Windows Subsystem for Android

2211.40000.11.0

**Comment by bansalsushant** [comment]
We are not restricting any mime type, and the mime type is decided by Android framework by looking into the file extension.
If Android identifies the file as specific mimetype and the application support that mimetype, it will work on WSA.

**Comment by hgourvest** [comment]
Thank you!
