### ISSUE TITLE
Display over other apps working intermittently.

### ISSUE THREAD

**Issue by Bananz0** [microsoft/WSA#216]
### Steps to reproduce

When using an app like shazam, The display over other apps works for some time then becomes unclickable and immovable. Moving it is also glitchy.

### ❌ Actual Behavior

The onscreen widget moves unpredictably

### Other Software

Shazam 13.14.0-230119-4d61f09

### Please specify the version of Windows Subsystem for Android

2211.40000.11.0

**Comment by Bananz0** [comment]
https://user-images.githubusercontent.com/31777541/214726156-30ac7dfa-2faa-47b9-8767-7231b6d349fa.mp4

**Comment by Quinxxxx** [comment]
> 

how did you get shazam to work, it can never identify music for me (the app itself works on WSA)

**Comment by nieubank** [comment]
This should be fixed in 2304, please file a feedback hub report if you're still seeing it (Win+F)
