### ISSUE TITLE
Command to start WSA from cmd/powershell?

### ISSUE THREAD

**Issue by 7gxycn08** [microsoft/WSA#218]
### Is your feature request related to a problem? Please describe

WSA will hang if i start it from a 3rd party app it requires WSA to be running to open normally and not hang.

### Describe the solution you'd like

Would like to start WSA from the command line before starting the third party apk.

### Describe alternatives you've considered

Running the Amazon Store starts WSA normally then i can run the third party app with no issues.

### Please specify the version of Windows Subsystem for Android

22010.40000.7.0

**Comment by infinitepower18** [comment]
`WsaClient /launch wsa://system`

**Comment by 7gxycn08** [comment]
> 

Exactly what i was looking for Thanks.

**Comment by jaholme** [comment]
Please file a feedback hub report under category (Apps > Windows Subsystem for Android) including recreating the problem with recording enabled as a third party app launch should not cause Windows Subsystem for Android to hang.

**Comment by 7gxycn08** [comment]
> Please file a feedback hub report under category (Apps > Windows Subsystem for Android) including recreating the problem with recording enabled as a third party app launch should not cause Windows Subsystem for Android to hang.

Updating to 2211.40000.11.0 Solved the issue WSA no longer hangs. Works flawlessly.
It even fixed the flickering issue from the previous version. My screen no longer flickers when running an app in WSA.
Consider the issue solved.

Should i close this issue or leave it to a mod to close?

**Comment by jaholme** [comment]
Happy to hear the latest version fixed your issue.

**Comment by maddevjose** [comment]
anyway to close the opened app from command line

**Comment by Turtlepaw** [comment]
> WsaClient /launch wsa://system

@infinitepower18, can the `wsa://system` parameter be any [deep link](https://developer.android.com/training/app-links/deep-linking)?

**Comment by notatestuser** [comment]
@Turtlepaw did you ever find out? Apologies for the old thread necro.

**Comment by Turtlepaw** [comment]
> @Turtlepaw did you ever find out? Apologies for the old thread necro.

@notatestuser, yes, you can directly launch apps by running this in PowerShell:

```ps
$env:LOCALAPPDATA\Microsoft\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\WsaClient.exe /launch wsa://com.google.android.apps.youtube.music
```

You can replace `com.google.android.apps.youtube.music` with any package name you want to launch. The exact directory where `WsaClient.exe` may differ too.
