### ISSUE TITLE
Reset to defaults button should have a confirmation dialog

### ISSUE THREAD

**Issue by rp1231** [microsoft/WSA#220]
### Is your feature request related to a problem? Please describe

It's very easy to hit it by mistake

### Describe the solution you'd like

A confirmation dialog after hitting the reset button asking to confirm your decision

### Describe alternatives you've considered

Hitting the button by mistake and then re-doing all the settings

### Please specify the version of Windows Subsystem for Android

2211.40000.11.0

**Comment by nieubank** [comment]
Resolved in an upcoming release.
