### ISSUE TITLE
WSA crashes upon launch and fails to start

### ISSUE THREAD

**Issue by UhOhAdam** [microsoft/WSA#222]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/109830422/216856971-69ae7b18-f827-4f82-8ca2-cc88bb1bdbf6.png)

Upon installation of WSA, it starts up and then crashes after a few seconds. Not sure why this is occurring, also the Amazon Appstore doesn't install. I have tried multiple times of deleting, resetting and reinstalling WSA with no success. It was working fine on versions up to 2208.

### ✔️ Expected Behavior

I was expecting to be able to open my Android apps and the Amazon appstore on the newest WSA version with Android 13 (2211).

### ❌ Actual Behavior

It starts the subsystem for a few seconds and then crashes with the error above.

### Please specify the version of Windows Subsystem for Android

2211.40000.11.0

**Comment by nieubank** [comment]
Can you file a feedback hub report with the repro and paste the link here so we can see what's going on?

**Comment by 7gxycn08** [comment]
Here is Some even viewer crash logs.

`Fault bucket , type 0
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: MicrosoftCorporationII.WindowsSubsystemForAndroid_2211.40000.11.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 10.0.22621.1
P4: 05e70ed3
P5: KERNELBASE.dll
P6: 10.0.22621.1194
P7: faa44dd0
P8: 80000003
P9: 00000000001084d2
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7b81c4fa-1aab-4565-9036-0f1577d2052d.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_MicrosoftCorpora_9f63aeba153ecdd18669979679bb53d2e49ed_34e198da_9246afd5-4163-4c50-9fb5-1afb0d4e52f4

Analysis symbol: 
Rechecking for solution: 0
Report Id: 49bc40ea-ba87-4764-849d-bd8c8ea9dba5
Report Status: 100
Hashed bucket: 
Cab Guid: 0`

`Fault bucket , type 0
Event Name: MoBEX
Response: Not available
Cab Id: 0

Problem signature:
P1: MicrosoftCorporationII.WindowsSubsystemForAndroid_2211.40000.11.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 2211.40000.11.0
P4: 63b5f0a6
P5: ucrtbase.dll
P6: 10.0.22621.608
P7: f5fc15a3
P8: 000000000007f61e
P9: c0000409
P10: 0000000000000007

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d2bf765a-8613-4d4a-94ba-11099217e822.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_MicrosoftCorpora_5af3aa2837e8257a487296cceb2a33b3c56e0_34e198da_5c550b75-2e12-482b-abe1-3c9f1cdfa36e

Analysis symbol: 
Rechecking for solution: 0
Report Id: de02e059-90ca-4abf-a43e-39b0771d753a
Report Status: 100
Hashed bucket: 
Cab Guid: 0`

**Comment by UhOhAdam** [comment]
> Can you file a feedback hub report with the repro and paste the link here so we can see what's going on?

https://aka.ms/AAjjqiy

**Comment by gaiking-uk** [comment]
I have the same issue, please let me know if I can help investigate / replicate

**Comment by DaniLebredo** [comment]
It looks like it has been fixed, version 2302.40000.8.0.

I've just installed it again minutes ago and, while using WSATools to install an apk, I got a notification saying WSA had to update. After that, the Amazon appstore got installed. Then I installed Aurora Store via WSATools and everything works quite fine, even better than I remembered. _Seems faster!_
