### ISSUE TITLE
SIDELOADED APK'S WITH DEVELOPER MODE CRASH 

### ISSUE THREAD

**Issue by ShadowOfPripyat** [microsoft/WSA#225]
### Steps to reproduce

Hi, I tried sideloading some APK's in WSA but since now WSA is running Android 13, every installed APK crashes. Clearing app cache and storage doesn't solve anything. Neither resting nor restarting WSA does any change. Everything was running fine with Android 12.

### ✔️ Expected Behavior

**As i said, i expect the apps to run without any problem**, 
_or Have the hability to CHOOSE to INSTALL between Android 12  OR Android 13._

### ❌ Actual Behavior

Apps installed from apk's crash instantly when launched.

### Other Software

Instagram, Snapseed APK(s) as the tested apps.
WSA PacMan for installing the APKs.

### Please specify the version of Windows Subsystem for Android

2211.40000.11.0

**Comment by jaholme** [comment]
Please file a report in Feedback Hub (Windows key + F) under category Apps > Windows Subsystem for Android and include a recording of the apps failing to launch.

**Comment by ShadowOfPripyat** [comment]
Here's the recording. I show you the settings that i have in wsaconfig and how i sideload APK's. This time i tried with "Happymod" and "Edjing". Amazon appstore works fine and the apps installed from Amazon works fine, but since these are made for _older_ Android versions (Like Android 8) may not work properly in Android 13. I will file the report later.
https://user-images.githubusercontent.com/73404930/218054456-ac68b5f8-5f4c-4d69-87c2-b90944b85b24.mp4

Enjoy the Vivaldi's Four Stations in the Background music!

**Comment by jaholme** [comment]
Sorry, I should have been clearer. Feedback hub has a recording mode which captures log output that would contain the details of the crashes these apps are running into.

**Comment by nieubank** [comment]
Following up on feedback hub.
