### ISSUE TITLE
Support for Signature Spoofing

### ISSUE THREAD

**Issue by Ismail01Hub** [microsoft/WSA#226]
### Is your feature request related to a problem? Please describe

I tried to install Micro G, but it is not working because the Subsystem doesn't have native support for Signature Spoofing. 

### Describe the solution you'd like

It will be helpful if WSA ROM has support for Micro G.

### Please specify the version of Windows Subsystem for Android

2301.40000.4.0

**Comment by jaholme** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community!

**Comment by Genxster1998** [comment]
This isn't a custom ROM fork , what are you expecting with such dubious grey line features on official release

**Comment by nieubank** [comment]
Thanks for your feedback but this is not something on our roadmap.
