### ISSUE TITLE
USB

### ISSUE THREAD

**Issue by Asbreuker** [microsoft/WSA#227]
### Is your feature request related to a problem? Please describe

Yes I use WSA to run my square program USB intergration would mean i can use a cash drawer and scannerintegration

### Describe the solution you'd like

Be able to have WSA see usb or have a way to choose usb devices. Look at virtual box usb for android x86

### Please specify the version of Windows Subsystem for Android

2211.40000. 11.0

**Comment by jaholme** [comment]
Duplicate of #103
