### ISSUE TITLE
Android_apps cannot read the real capacity of battery of Laptop in mA·h

### ISSUE THREAD

**Issue by 1457384613gh** [microsoft/WSA#228]
### Steps to reproduce

The screenshot will be uploaded later.

### ✔️ Expected Behavior

Wish that
Developers could developed battery_driver of Java of Android to enrich `BatteryManager` of `BatteryService` of API of Android;
Android_apps could get and show the true capacity of battery of Laptop in mA·h.

### ❌ Actual Behavior

Android_apps always show 1000mA·h by mistakes.
WSA has battery_driver of Linux_Kernel,
but has no battery_driver of Java of Android.
So the `BatteryManager` of `BatteryService` of API of Android is not full.

### Other Software

Nothing

### Please specify the version of Windows Subsystem for Android

The newest

**Comment by jaholme** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community!

**Comment by kevinkieselbach** [comment]
This was a regression with the update to Android 13.  We'll fix it.

**Comment by kevinkieselbach** [comment]
Apparently, the regression was intentional because Android's performance is noticeably worse on battery than on AC power.  We'll have to carefully consider whether to bring it back.  Would your app take advantage of knowing the battery level, and if so, how?

**Comment by nieubank** [comment]
We're currently not planning anything in this space due to potential for app performance regressions and deferring to Windows' virtualization platform to better manage battery and power usage.
