### ISSUE TITLE
Change Device Type/Build.prop Settings.

### ISSUE THREAD

**Issue by 7gxycn08** [microsoft/WSA#230]
### Is your feature request related to a problem? Please describe

WSA Currently runs as a Pixel 5 Device which results in Apps being badly scaled/ Zoomed In on Windows. 

### Describe the solution you'd like

Ability to change to a Tablet device Such as the Samsung Tab S8 Ultra which would theoretically result in apps scaling better on Windows via editing the Build.prop file In the WSA file system.

Or a more user friendly approach by selecting the device type from Windows 11.

### Describe alternatives you've considered

Tried editing the Build.prop file however It is Read Only and requires the system partition to be mounted with write permissions. Upon remounting the system with write permissions It results in a system restart which then reverts the permissions to read only.

### Please specify the version of Windows Subsystem for Android

2301.40000.4.0

**Comment by nieubank** [comment]
Ensure you're acquiring WSA via the Microsoft Store. The official package reports as the Subsystem for Android device.
