### ISSUE TITLE
BSOD after enabling the "virtual machine platform" feature in windows 11

### ISSUE THREAD

**Issue by drenchedbanana** [microsoft/WSA#235]
### Steps to reproduce

Install WSA from microsoft store and enable virtual machine platform feature after windows restar's my pc starts bluescreening.

OS:Windows 11 22H2

"I have virtualization enbled in bios"

### ✔️ Expected Behavior

No Bluescreens

### ❌ Actual Behavior

Bluescreen every like 12-50 after restarting

### Please specify the version of Windows Subsystem for Android

2211.40000.11.0

**Comment by jaholme** [comment]
Hi, can you file a Feedback hub report (Windows Key + F)?  This will allow someone to investigate the crash further.

**Comment by nieubank** [comment]
Tracking under feedback hub.
