### ISSUE TITLE
WSA program window will refreshed automatically when switching monitors

### ISSUE THREAD

**Issue by song2daodao** [microsoft/WSA#236]
### Steps to reproduce

Dragging a program from one monitor to another
![屏幕截图 2023-02-16 000442](https://user-images.githubusercontent.com/99074946/219084620-86b0bcb0-81bb-40ce-a00b-61c212111acf.png)

### ✔️ Expected Behavior

Programs switch freely between monitors without automatic refreshing, especially on some video apps and game apps.

### ❌ Actual Behavior

Annoying auto-refresh, a bug that is a near disaster for multi-monitor users.

### Please specify the version of Windows Subsystem for Android

2301.40000.4.0

**Comment by nieubank** [comment]
This is something that will need to be addressed by app developers. We don't do anything special in WSA over the normal AOSP behavior for multi-display/external-display scenarios. For your app, you'll need to handle configuration changes related specifically to at least density, screenSize, screenLayout, smallestScreenSize, potentially fontScale or orientation. Without handling the proper configuration changes in the app, Android restarts the activity to ensure the correct resources are updated.

https://developer.android.com/guide/topics/resources/runtime-changes
