### ISSUE TITLE
WSA not starting

### ISSUE THREAD

**Issue by himanshu8443** [microsoft/WSA#238]
### Steps to reproduce

Open WSA 
virtualization is already enabled

The following features are already enabled and also tried disabling and enabling them. 
![image](https://user-images.githubusercontent.com/99420590/219371963-bcd12dfa-d11f-421e-9937-f63a04a2acc6.png)
control flow guard enabled (use default on)

Also tried reinstalling WSA
The beta program is also joined
I previously installed the Nox android emulator and it changed some settings and restarted the device which could also be the reason

### ✔️ Expected Behavior

All important settings are enabled it should run  and it was running when I previously installed

### ❌ Actual Behavior

It asks to enable virtualization even if it's already enabled 
amazon app store not showing in the apps.
![image](https://user-images.githubusercontent.com/99420590/219378676-bcafa65e-d149-41e1-8f23-dddbc518f3e1.png)

### Please specify the version of Windows Subsystem for Android

2301.40000.4.0

**Comment by jaholme** [comment]
How were you able to resolve this? Unfortunately, third emulator software can change many PC settings that can result in the underlying hypervisor platform not working correctly. We're looking to identify the top problems and add them to our troubleshooting documentation.

**Comment by himanshu8443** [comment]
1) The emulator disabled hyper v using Power Shell. I turned off hyper v then turned it on using Power shell. 
   https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

2)Completely uninstalled WSA using Revo uninstaller and then reinstalled WSA. Now Amazon app store is showing the start apps and WSA is working fine.

3) Also tried these methods but don't know if they actually helped turned on and off other window features control flow guard, hypervisor platform, virtual machine platform, and subsystem for Linux.

**Comment by jaholme** [comment]
Make sure you have "Virtual Machine Platform" enabled we rely on that feature and not Hyper-V directly.  Thanks for the response I'm going to work to get our troubleshooting documentation updated.

**Comment by himanshu8443** [comment]
yes, it's currently enabled. I just turned it off restarted the device then turned it on again and only
