### ISSUE TITLE
Communicate with host when using "Advanced Networking"

### ISSUE THREAD

**Issue by jerry-sands** [microsoft/WSA#239]
### Is your feature request related to a problem? Please describe

I want to access other devices in my LAN and also communicate with Windows programs through IP.
When using "Advanced Networking", WSA gets the same IP address as the Windows host, and therefore cannot communicate with it as if it was in its LAN.

### Describe the solution you'd like

As in VMWare, WSA should be able to communicate with the router and get assigned with an IP. This will provide WSA and Windows different IPs in the same LAN, which will then allow them to communicate with each other.

### Please specify the version of Windows Subsystem for Android

2211.40000.11.0

**Comment by jaholme** [comment]
Thanks for your feedback, we're of the limitation and are looking at improving the networking experience in future releases.  In the meanwhile, you may be able to unblock your scenarios by utilizing the following commands to open specific ports, below we have opened port 443. 

Set-NetFirewallHyperVVMSetting -VMCreatorId '{9E288F02-CE00-4D9E-BE2B-14CE463B0298}' -LoopbackEnabled True

New-NetFirewallHyperVRule -DisplayName LoopbackAllow -VMCreatorId '{9E288F02-CE00-4D9E-BE2B-14CE463B0298}' -Direction Inbound -Action Allow -LocalPorts 443

**Comment by nieubank** [comment]
Tracking this under #213
