### ISSUE TITLE
Advanced networking is not displayed and does not work

### ISSUE THREAD

**Issue by master255** [microsoft/WSA#240]
@hamza-usmani @nieubank ### Steps to reproduce

I installed the WSA and I don't have this option. Other than that my ip address is behind NAT. How do I get a network bridge?
![image](https://user-images.githubusercontent.com/5380115/220186715-b2923741-0184-41ae-994f-514a387d7001.png)
![image](https://user-images.githubusercontent.com/5380115/220187189-a13dc8b2-2258-4a0c-bbeb-e0347c97afde.png)
1 - my current ip address
2 - ip address of the virtual machine

### ✔️ Expected Behavior

I expect the Android ip address to be in my windows subnet. Or at least it will be the same.
Bridge.

### ❌ Actual Behavior

NAT

### Please specify the version of Windows Subsystem for Android

2301.40000.4.0

**Comment by bansalsushant** [comment]
Hi,

Thanks for reaching out, this behaviour is not expected. We will investigate and get back to you.

**Comment by bansalsushant** [comment]
Hi,

Can you specify which version of Windows 11 are you using? Can you update to the latest version and try this?

**Comment by master255** [comment]
@bansalsushant No I can't update Windows. It's installing some software that nobody knows about. I cannot risk the stability and security of the operating system.
![image](https://user-images.githubusercontent.com/5380115/221586304-3ca9e18d-b7d8-4de6-ae07-c339b8aeaa9a.png)

**Comment by jaholme** [comment]
Unfortunately, advanced networking functionality is only supported on Windows 11 22H2(22621+).

**Comment by master255** [comment]
Ok. Then you make it just for yourself.

**Comment by smhoma** [comment]
I have the same issue. i have installed Windows 11 23H2 build 22631.3007 and my WSA version is 2311.40000.5.0.

**Comment by jesvijonathan** [comment]
same here... installed WSA, i cant make use of devices in my local network  via wsa.. and it does not have na option for advanced networking options...

**Comment by jaholme** [comment]
Advanced networking was superceded by the Local Network Access feature which is located on the Advanced Settings > Experimental features section.
![image](https://github.com/microsoft/WSA/assets/27746781/4a4c70d6-cd33-4f9f-9f19-db1236624b2d)

**Comment by master255** [comment]
@jaholme This feature is available on Windows 10 21H1 build 19043???

**Comment by jesvijonathan** [comment]
@jaholme but does it work though ? I have it turned on but still can't get to connect with local devices on the same network

**Comment by fahri314** [comment]
Network settings so basic feature. Why only work in win 11. It is so ridiculous.
