### ISSUE TITLE
Background application with windows standby

### ISSUE THREAD

**Issue by Hozzu** [microsoft/WSA#241]
### Describe the solution you'd like

Background application like music player does not work when the windows is in modern standby state.
Since most of windows applications do not support modern standby, it is very nice if android application supports it.
Many windows tablet including surface series need the application that supports modern standby to use them as tablet devices.

### Please specify the version of Windows Subsystem for Android

2301.40000.4.0

**Comment by bansalsushant** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community!
