### ISSUE TITLE
LAN connections issue

### ISSUE THREAD

**Issue by matinmn87** [microsoft/WSA#248]
### Steps to reproduce

I was trying to play a LAN multiplayer game on WSL. But I can neither host a game (the LAN game won't be visible on the phone I'm trying to connect with) nor join the game made by phone.

### ❌ Actual Behavior

It seems that nothing is working. I'm not able to join the local game; & I can't host the game as well.

### Please specify the version of Windows Subsystem for Android

2301.40000.70

**Comment by kevinkieselbach** [comment]
Have you tried enabling the "advanced networking" toggle in the "Windows Subsystem for Android Settings" app?  That should make WSA visible on your PC's local network.  "Advanced networking" impacts WSA's performance and reliability, so we haven't enabled it by default until we address those issues, but it should unblock your scenario.

**Comment by matinmn87** [comment]
Hello again. I've looked for this option & searched for it, & I've found [this](https://www.elevenforum.com/t/enable-or-disable-advanced-networking-for-wsa-in-windows-11.12299/) link. But my WSA doesn't have this option. How can I enable it?
![image](https://user-images.githubusercontent.com/70327745/223810820-009dad4d-5fd8-4c62-961f-de99e7126611.png)


Thanks for your help.
By the way, my WSA version is 2301.40000.7.0

**Comment by kevinkieselbach** [comment]
"Advanced networking" requires OS features only present in the Windows 11 Fall 2022 release, so you probably haven't taken that update yet.  We're looking to get the same functionality without a dependency on newer OS features, but that won't be ready for a while.

**Comment by master255** [comment]
@matinmn87 I think it's better to use an emulator. [For example Memu](https://www.memuplay.com). It has a network bridge and it works on any version of the operating system. 
https://github.com/microsoft/WSA/issues/240

**Comment by matinmn87** [comment]
OK, I got 22H2. I will also check that.
Thanks.

**Comment by AJolly** [comment]
I'll confirm I'm on 22H2 with local network access turned on, and WSA can only see itself and my gateway router on the local network.
