### ISSUE TITLE
Update to2301，report errors

### ISSUE THREAD

**Issue by MemoryYiJun** [microsoft/WSA#255]
### Steps to reproduce

Update to 2301，WSA have a program failed to start correctly

### ❌ Actual Behavior

https://answers.microsoft.com/zh-hans/windows/forum/all/wsaclientexe%E6%8F%90%E7%A4%BA%E7%B3%BB%E7%BB%9F/7d371707-c88d-49f8-93a2-52f031f986c8

### Please specify the version of Windows Subsystem for Android

2301.40000.4.0

**Comment by jaholme** [comment]
Please file a Feedback Hub report (Windows key + F) and include a recording within Feedback Hub of launching WSA and it failing.
