### ISSUE TITLE
vmmemCmZygote process not exit after manual shutdown WSA

### ISSUE THREAD

**Issue by magsom** [microsoft/WSA#257]
### Steps to reproduce

Click the shutdown button on WSA setting page.

### ✔️ Expected Behavior

vmmemCmZygote process should end when you manually shutdown WSA.

### ❌ Actual Behavior

vmmemCmZygote process suspended and occupys about 500MB commit size.

### Please specify the version of Windows Subsystem for Android

2301.40000.7.0

**Comment by nieubank** [comment]
Is this WSA installed from the Microsoft Store? There shouldn't be a vmmemCmZygote process associated with WSA.

**Comment by magsom** [comment]
No. I installed WSA by developer mode loose file sideloading.

**Comment by nieubank** [comment]
We can make any guarantees on builds not officially acquired. If you reproduce the same on a production build from the Microsoft Store please file a feedback hub report.

**Comment by diehard88** [comment]
> ### Steps to reproduce
> Click the shutdown button on WSA setting page.
> 
> ### ✔️ Expected Behavior
> vmmemCmZygote process should end when you manually shutdown WSA.
> 
> ### ❌ Actual Behavior
> vmmemCmZygote process suspended and occupys about 500MB commit size.
> 
> ### Other Software
> _No response_
> 
> ### Please specify the version of Windows Subsystem for Android
> 2301.40000.7.0

the same here

**Comment by theAeon** [comment]
Welp, might want to re-open this because I'm getting this exact issue on an official store install.

**Comment by nieubank** [comment]
> Welp, might want to re-open this because I'm getting this exact issue on an official store install.

Thanks for your feedback, we are aware of this issue in recent Windows builds and will update when there is a resolution.

**Comment by Kryptos-FR** [comment]
I don't have WSA installed. However I have WSL and Sandbox, one of which is starting this process. So this issue seems to be widespread with all the virtualized envs.

**Comment by sagie-d** [comment]
I 

> > Welp, might want to re-open this because I'm getting this exact issue on an official store install.
> 
> Thanks for your feedback, we are aware of this issue in recent Windows builds and will update when there is a resolution.

Will you update here in this issue? I'm experiencing the same.

**Comment by sagie-d** [comment]
> > Welp, might want to re-open this because I'm getting this exact issue on an official store install.
> 
> Thanks for your feedback, we are aware of this issue in recent Windows builds and will update when there is a resolution.

Also, why is this issue marked is closed, is this fixed already?
