### ISSUE TITLE
display issue of dialog style activity

### ISSUE THREAD

**Issue by AyakaAgo** [microsoft/WSA#259]
### Steps to reproduce

start PackageInstaller from file manager

a brief display issue when launching a dialog-style activity, the window content is not displayed completely, but will back to normal soon

<img alt="display error for a short time" src="https://user-images.githubusercontent.com/20831549/224664346-ec03d8ca-28ef-4b96-b7d7-ca10c861a9f7.png" width=40% height=40%><img alt="normal display" src="https://user-images.githubusercontent.com/20831549/224664370-667f7b45-8a48-431d-987d-dfabd3220bf4.png" width=40% height=40%>

### ✔️ Expected Behavior

<img alt="normal display" src="https://user-images.githubusercontent.com/20831549/224664370-667f7b45-8a48-431d-987d-dfabd3220bf4.png" width=20% height=20%>

### ❌ Actual Behavior

<img alt="display error for a short time" src="https://user-images.githubusercontent.com/20831549/224664346-ec03d8ca-28ef-4b96-b7d7-ca10c861a9f7.png" width=20% height=20%>

After the window animation ended, it also returned to normal

### Please specify the version of Windows Subsystem for Android

2301.40000.7.0

**Comment by bansalsushant** [comment]
Hi!

Is this happening for all apps or some specific app?

**Comment by AyakaAgo** [comment]
I haven't seen this happen with other apps, not sure if it's just `Package installer(com.android.packageinstaller)` happens

**Comment by dabhattimsft** [comment]
Does it get stuck on unexpected state? or does it recover quickly?

**Comment by bansalsushant** [comment]
Since we don't see this with other apps - can this be something with the app itself?

**Comment by nieubank** [comment]
Animations can hitch like this during high system load, running many applications or on low end devices. We're constantly working to address performance issues and this would be better tracked under a feedback hub request (Win+F).
