### ISSUE TITLE
Why does "Ethernet" show up as a WiFi network? Why does a virtual ethernet connection need a WiFi password?

### ISSUE THREAD

**Issue by Warrentheo** [microsoft/WSA#265]
### Steps to reproduce

I am unable to get WSA to connect to the internet despite both ethernet and WiFi working fine on the host machine.  Listing WiFi networks shows "Ethernet" as a WiFi network inside of WSA which I assume is the correct connection, but it needs a WiFi password despite not being a WiFi connection.  What is this password?

### ✔️ Expected Behavior

Internet to work just like it does in WSL and Hyper-V.

### ❌ Actual Behavior

No internet connectivity in WSA despite internet working fine on the Host for both Ethernet and WiFi, as well as both WSL and Hyper-V working with both Ethernet and WiFi on the host machine.

### Other Software

Windows 11 22621.1413
WSA 2302.40000.6.0

### Please specify the version of Windows Subsystem for Android

2302.40000.6.0

**Comment by nieubank** [comment]
Are you using advanced networking? If so, do you have networking connectivity in WSA if you toggle that off and restart via the WSA settings app?

For some context, unfortunately many Android apps were written assuming a wifi or cellular connection for connectivity checks and will complain to the user about lack of network connectivity in the presence of only an Ethernet connection. For that reason, we have virtualization a wifi network on top of the virtual network for the VM which is represented as Ethernet. Advanced networking is a special case in the current builds where we reflect adapters from the Windows host into Android. It still has some rough edges as I suspect you're finding and we are working to resolve those in future builds.

**Comment by jaholme** [comment]
Please file a Feedback Hub report (Windows Key + F) under category Apps > Windows Subsystem for Android. Under part 4, include a recording of starting an Android app that doesn't have networking access..

**Comment by nieubank** [comment]
Following up on feedback hub.
