### ISSUE TITLE
MediaProjection records only the Android part of the screen, not the entire Windows screen

### ISSUE THREAD

**Issue by 2kit** [microsoft/WSA#270]
### Steps to reproduce

Android offers the MediaProjection API to record the system screen: https://developer.android.com/guide/topics/large-screens/media-projection

This API can be triggered by calling
startActivityForResult(mediaProjectionManager.createScreenCaptureIntent(), REQUEST_MEDIA_PROJECTION);

When the API is used, Android phones and tablets normally record the whole device screen. On Chromebooks, which use ChromeOS with Android inside a VM, the whole Chromebook screen is recorded, not just the Android part. 

In WAS, only the Android part of the screen including the amazon App store is recorded while the rest of the Windows screen is rendered black. This makes apps that are based on the MediaProjection API practically useless, for example screen recording, screen sharing and mirroring apps.

You can reproduce this issue for example with the "Screen Mirroring App" on the Amazon Apps Store: https://www.amazon.com/-/de/dp/B099KKC54B

### ✔️ Expected Behavior

MediaProjection records the entire Windows screen with all application windows that are visible on the screen. If Windows is attached to multiple screens, the user should be able to select a screen for the recording when the MediaProjection is called. 

### ❌ Actual Behavior

MediaProjection records only the Android part of the screen.

### Other Software

Screen Mirroring App v1.42: https://www.amazon.com/-/de/dp/B099KKC54B 

### Please specify the version of Windows Subsystem for Android

2301.40000.7.0

**Comment by dabhattimsft** [comment]
Thanks for the feedback. This is by design since Android does not have access to Windows buffers. This is not currently on our roadmap, but we will continue to reevaluate.
