### ISSUE TITLE
add some shortcut keys

### ISSUE THREAD

**Issue by internettrollwatt** [microsoft/WSA#274]
### Is your feature request related to a problem? Please describe

I hope to add some shortcut keys, which can improve my work efficiency

### Describe the solution you'd like

For example: ctrl+M：rename ；Alt+space: file properties

### Please specify the version of Windows Subsystem for Android

2302.40000.8.0

**Comment by xhan65** [comment]
Thanks for creating a feature request. Can you explain more about what Android app you are referring to? i.e. Do you need shortcut keys for file system operations?

**Comment by internettrollwatt** [comment]
The file management interface provided by WSA

**Comment by xhan65** [comment]
This is something on our radar already for new feature requests, we appreciate the feedback here!
