### ISSUE TITLE
Icon indicator to distinguish WSA apps

### ISSUE THREAD

**Issue by rp1231** [microsoft/WSA#276]
### Is your feature request related to a problem? Please describe

It gets hard to distinguish between win32 and wsa apps,
Some kind of indicator would reduce the confusion and help identify wsa apps better.

### Describe the solution you'd like

Some kind of indicator on the icons to reduce the confusion and help identify wsa apps better.

### Please specify the version of Windows Subsystem for Android

2302.40000.9.0

**Comment by matinmn87** [comment]
Actually, personally, I disagree with you. This feature makes WSA look much better. But if there were an option to enable/disable it, it would be so perfect.

**Comment by bansalsushant** [comment]
Hi,

Our aims is that user should not need to differentiate between Win32 and WSA apps - both should run seamlessly. Considering that, this feature isn't on our immediate roadmap, but we're always listening to the community!

**Comment by upintheairsheep** [comment]
> Actually, personally, I disagree with you. This feature makes WSA look much better. But if there were an option to enable/disable it, it would be so perfect.

Agree, I don’t want some sort of flag, but I’d like one for PWA apps
