### ISSUE TITLE
can't start WSA

### ISSUE THREAD

**Issue by likertuban** [microsoft/WSA#278]
### Steps to reproduce

WSA doesn't launch on HIGH performance (NVIDIA GeForce RTX 3050)/power saving (Intel(R) Iris(R) Xe Graphics and only launching when I use Microsoft Basic Render Driver.
I can't even open Files/Developer Setting, nothing happened when I click on Files from WSA Setting when I use NVIDIA, when I use Internal Graphic/power saving there's windows saying starting WSA but then disappeared and nothing opened, only Microsoft Basic Render Driver works,
the problem is similar to https://github.com/microsoft/WSA/issues/202
but the problem persist even when using 2302.40000.9.0 version

### ✔️ Expected Behavior

The APP Launching

### ❌ Actual Behavior

WSA Crash Crash

### Other Software

Windows 11, Nvidia rtx 3050 gpu, CPU Intel(R) Core(TM) i7-12700H CPU @ 2.3GHz

### Please specify the version of Windows Subsystem for Android

2302.40000.9.0

**Comment by jaholme** [comment]
Please file a Windows Feedback Hub Report (Windows Key + F), under category Apps > Windows Subsystem for Android.
<img width="547" alt="image" src="https://user-images.githubusercontent.com/27746781/230924935-4f7eb4cb-6df8-4f60-b4d1-2008dec096f5.png">
Please select the option to start a recording of WSA not launching.  
<img width="522" alt="image" src="https://user-images.githubusercontent.com/27746781/230925121-55731fb6-e224-4469-b56e-285ed214d7b7.png">

**Comment by likertuban** [comment]
> Please file a Windows Feedback Hub Report (Windows Key + F), under category Apps > Windows Subsystem for Android. <img alt="image" width="547" src="https://user-images.githubusercontent.com/27746781/230924935-4f7eb4cb-6df8-4f60-b4d1-2008dec096f5.png"> Please select the option to start a recording of WSA not launching. <img alt="image" width="522" src="https://user-images.githubusercontent.com/27746781/230925121-55731fb6-e224-4469-b56e-285ed214d7b7.png">

it seems that I can't record it, there's no option for it, when I open feedback hub, there's a screenshot already and if I remove the screenshot, there's no option for attachment
