### ISSUE TITLE
HDR videos available even on SDR displays/panels

### ISSUE THREAD

**Issue by ryslavyvaclav** [microsoft/WSA#283]
### Steps to reproduce

Open any video playback capable app and play some HDR content on it.. It will have "greyish" accent indicating HDR being applied on SDR videos And weird color mixture when HDR is played on non-HDR display (example: YouTube)

I have HDR off in Windows settings obv.

It should be auto-detecting my display I guess? But thats not happening.
I should not be having options to play HDR at all.
I cant even disable it nowhere.

### ✔️ Expected Behavior

Being able to play SDR content in apps on my SDR display

### ❌ Actual Behavior

Any HDR videos is being played as HDR and not SDR.. And non-HDR videos are having HDR effects applied (example: YouTube)

### Other Software

Mainly:
YouTube app (any version)
VLC (any version)
and:
Any other HDR playback capable app (any version)

### Please specify the version of Windows Subsystem for Android

2303.40000.4.0

**Comment by jaholme** [comment]
Thanks for raising this do you have a Nvidia GPU?

**Comment by ryslavyvaclav** [comment]
> Thanks for raising this do you have a Nvidia GPU?

No I have AMD and latest drivers

**Comment by nieubank** [comment]
Tracking this on #171
