### ISSUE TITLE
Video in WSA is washed out and blacks are gray 

### ISSUE THREAD

**Issue by MustardChef** [microsoft/WSA#284]
### Steps to reproduce

1. Open any video up on any app installed on WSA 
2. Compare with the same video on Windows 11
3. Darks/blacks are grayed out heavily and there are no true blacks (compared to video playback on Windows 11)

### ✔️ Expected Behavior

Expected behaviour: Video playback on WSA would look the same as video playback on Windows 11

### ❌ Actual Behavior

However, actual behavior was that the WSA video playback was washed out and gray with no true blacks. The UI of the apps are pure black still but anywhere the video is will be gray

---

***Issue sent behalf of someone else***

This issue is not a duplicate of the previous issue (https://github.com/microsoft/WSA/issues/171), pertaining to Nvidia GPUs

### System Specifications:
- CPU: Intel® Core™ i9 13900k, 
- GPU: AMD RX 7900 XTX,
- RAM: 124 GB DDR5,
- OS: Windows 11 22H2 (OS Build 22621.1555)

### Source of WSA

Microsoft Store

### Feedback Hub Report:

Sent with the title: "Video in WSA is washed out and blacks are gray" (same as this issue.) 
Submitted 08:21 UTC
However since a Microsoft account was not signed into at the time, they cannot provide a link.

### Images of the issue: 

<img src="https://cdn.discordapp.com/attachments/1099594242751475742/1099600502850854962/image.png" />

<img src="https://cdn.discordapp.com/attachments/1099594242751475742/1099599579164446820/image.png" />

<img src="https://cdn.discordapp.com/attachments/1099594242751475742/1099601311076462642/image.png" />

### Additional Information:

- Issue occurs with HDR on or off

### Please specify the version of Windows Subsystem for Android

2303.40000.5.0

**Comment by nieubank** [comment]
This is the same issue. #171 is not specific to Nvidia, though those GPUs more commonly reproduce this issue.

**Comment by MustardChef** [comment]
> This is the same issue. #171 is not specific to Nvidia, though those GPUs more commonly reproduce this issue.

Ah, I see, thanks a lot for the clarification

**Comment by 7gxycn08** [comment]
They are clueless about this issue they closed and ignored countless threads no point in reporting it anymore. #171 was closed and marked as fixed when in reality it's not.

**Comment by nieubank** [comment]
> They are clueless about this issue they closed and ignored countless threads no point in reporting it anymore. #171 was closed and marked as fixed when in reality it's not.

We fixed a class issue causing washed out color in video playback but that's doesn't mean there aren't still other similar bugs. Feel free to file a new issue with specifics about how you are able to repro (what app, gpu, scenario, etc.) and we're happy to take a look.
