### ISSUE TITLE
can't get adb working

### ISSUE THREAD

**Issue by usr-canis** [microsoft/WSA#287]
### Steps to reproduce

run `adb connect 127.0.0.1:58526`

Turning on  wireless debugging toggle in settings 

### ✔️ Expected Behavior

adb should get connected to wsa 

wireless debugging must get turned on

### ❌ Actual Behavior

returns `cannot connect to 127.0.0.1:58526: No connection could be made because the target machine actively refused it. (10061)`

momentarily flashes to the on color and momentarily the toggles to the on position. Then the switch immediately switches back to the off position and off color. All other toggles in the developer settings work as intended. This is the only one that fails.

### Please specify the version of Windows Subsystem for Android

2303.40000.5.0

**Comment by MustardChef** [comment]
> ### Steps to reproduce
> 
> run `adb connect 127.0.0.1:58526`
> 
> Turning on wireless debugging toggle in settings
> ### ✔️ Expected Behavior
> 
> adb should get connected to wsa
> 
> wireless debugging must get turned on
> ### ❌ Actual Behavior
> 
> returns `cannot connect to 127.0.0.1:58526: No connection could be made because the target machine actively refused it. (10061)`
> 
> momentarily flashes to the on color and momentarily the toggles to the on position. Then the switch immediately switches back to the off position and off color. All other toggles in the developer settings work as intended. This is the only one that fails.
> ### Other Software
> 
> _No response_
> ### Please specify the version of Windows Subsystem for Android
> 
> 2303.40000.5.0

Follow this:
https://github.com/MustardChef/WSABuilds/blob/master/Fixes/TargetMachineActivelyRefusedConnection.md
