### ISSUE TITLE
Feature Request: Reverse Shortcuts

### ISSUE THREAD

**Issue by upintheairsheep** [microsoft/WSA#288]
### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

Make a system for making shortcuts for all Windows programs installed, with their icons, and adding each of them as spoof apps, for both Android launchers that go full screen (in the future, when windows supports adding launchers for different devices), to apps that list all other apps and launch them.

### Describe alternatives you've considered

no

### Please specify the version of Windows Subsystem for Android

latest

**Comment by jaholme** [comment]
This forum is intended for addressing developer specific problems. Please file end-user feature requests in Feedback Hub (Windows Key  + F).
