### ISSUE TITLE
Logitech Options plus software can't detect wsa apps.

### ISSUE THREAD

**Issue by rp1231** [microsoft/WSA#289]
### Steps to reproduce

Open logitech options plus software which has the ability to customize keybindings on a per app basis.
The WSA apps wont show up in the list of apps.

### ✔️ Expected Behavior

The WSA apps should be detected along with the normal windows apps.

### ❌ Actual Behavior

The WSA android apps don't appear in the list.

### Other Software

Logi Options+ version 1.38.397153

### Please specify the version of Windows Subsystem for Android

2303.4000.5.0

**Comment by jaholme** [comment]
This forum is intended for addressing developer specific problems. Please file end-user feature requests in Feedback Hub (Windows Key  + F).
