### ISSUE TITLE
Allow Android Apps to invoke native Windows APIs

### ISSUE THREAD

**Issue by analitiLLC** [microsoft/WSA#290]
### Is your feature request related to a problem? Please describe

The problem - WSA does not provide correct WiFiInfo due to a bug (https://github.com/microsoft/WSA/issues/57)
However, this bug is not high on Microsoft's priority list to fix.

### Describe the solution you'd like

It would be beneficial to developers to have an API bridge/RPC mechanism for Android apps to invoke native Windows APIs.
Or, as a poor man's alternative, have some way to execute Windows shell commands from within Android apps (similar to Java Runtime.exec() or ProcessBuilder API).

### Describe alternatives you've considered

A possible alternative - the Android App developer could develop a Windows App to perform Windows API requests at the behest of an Android App on the same host. However - it would require the Android App to ask the end user to install the Windows App, manually.

This alternative is not very intuitive for users or attractive to developers trying to overcome bugs in WSA's own implementation.

Developers willing to spend the time & effort to adapt Android Apps to WSA may prefer to extend their code to call native Windows API or execute Windows shell command, when they have no suitable WSA build-in alternative.

(And, maybe it's not needless to say: if the idea is to develop a Windows App - why bother with WSA at the first place?)

### Please specify the version of Windows Subsystem for Android

2303.40000.5.0

**Comment by SteveWorkshop** [comment]
What are you thinking? VMs are always VMs, they are two individual operating systems...
However, wsa can provide some special apis for apps to collaborate better with Windows. After all, many 3rd party ROMs have thier own SDKs

**Comment by nieubank** [comment]
There are no plans at this time to support this level of integration, it is a goal to make user experiences seamless via protocol activations associated with intents and similar functionality. For cases like device emluation like you mentioned above, WSA is not intended to support hardware management features, like wifi scanning and performance apps but if something about the data presented results in an issue in your app, we'd like to know specifics so we can plan to address those.
