### ISSUE TITLE
Get real IP from Android application

### ISSUE THREAD

**Issue by ShkurtiA** [microsoft/WSA#291]
### Is your feature request related to a problem? Please describe

I run my Android app in Windows with Windows Subsystem for Android. In my app I need to get the IP address that the network assigns to the Windows Wi-Fi.

When I run ipconfig in Windows, the address that I get from Android NetworkInterface doesn't match the one from Wi-Fi Ipv4 address.

Android on Windows: 172.24.59.44
Windows Wi-Fi: 192.168.25.217 (the one assigned from router)

I know this issue is also for ChromeOS and there it is solved like this:

>         fun getChromeOsIpAddress() : String {
>            val process = ProcessBuilder().command("/system/bin/getprop", "arc.net.ipv4.host_address").start()
>            val ipAddress = readInput(process.inputStream)
>            return ipAddress
>         }

I have enabled the advanced networking in settings. 

### Describe the solution you'd like

Either fix that the NetworkInterface returns the correct IP or make a solution similar to ChromeOS

### Please specify the version of Windows Subsystem for Android

2303.40000.5.0

**Comment by ShkurtiA** [comment]
@jaholme how do you know that I dont have that windows version? why do you close the ticket

**Comment by jaholme** [comment]
If you can file a Feedback Hub report (Windows Key + F) reproing the problem and link it here that will help us investigate the issue.

It is unexpected that with advanced networking enabled your app would see a different IP address from the Windows adapter.

**Comment by ShkurtiA** [comment]
somehow it works now, thanks for your support
