### ISSUE TITLE
parpadeos blancos cuando la aplicación está en modo de ventana (tipos de tamaño de windows) 

### ISSUE THREAD

**Issue by pietro0202** [microsoft/WSA#294]
### Steps to reproduce

![Captura de pantalla (13)](https://user-images.githubusercontent.com/74553771/236601928-cd5e30b6-52fa-4d51-8bbf-b43613cdfc46.png)

con ese tamaño o otro tamaño de modo ventana aveces parpadea

### ✔️ Expected Behavior

el comportamiento esperado es que la pantalla no de parpadeos blancos cuando la aplicación android está en cualquier tamaño,  **de los tamaños que brinda el botón maximizar**

### ❌ Actual Behavior

el comportamiento real es que las apps android están dando parpadeos blancos cuando están en tamaños de **los tamaños que brinda el botón maximizar**

### Please specify the version of Windows Subsystem for Android

2303.40000.5.0

**Comment by jaholme** [comment]
Please file this in feedback hub(Windows Key + F) https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332, this forum is intended for developer issues only.
