### ISSUE TITLE
arreglo de unas apps android. fix some android apps.

### ISSUE THREAD

**Issue by pietro0202** [microsoft/WSA#295]
### Is your feature request related to a problem? Please describe

la aplicación BANRESERVAS se cierra al abrirla y ALIEXPRESS tiene un error en su interfaz que no muestra su contenido
The BANRESERVAS application closes when opening it and ALIEXPRESS has an error in its interface that does not show its content
![Captura de pantalla (27)1](https://user-images.githubusercontent.com/74553771/236602735-576f79f0-cf1b-4a43-94f9-bc5f93d7af76.png)

### Describe the solution you'd like

quisiera que esas dos aplicaciones funcionen
I would like those two applications to work

### Please specify the version of Windows Subsystem for Android

2303.40000.5.0

**Comment by jaholme** [comment]
This forum is intended for addressing developer specific problems. Please file end-user feature requests in Feedback Hub (Windows Key  + F).
