### ISSUE TITLE
WSA restarts/shows loading screen after waking the computer up from sleep

### ISSUE THREAD

**Issue by rp1231** [microsoft/WSA#298]
### Steps to reproduce

Have WSA apps open.
Put the laptop to sleep.
Wake up and log in to your account.

### ✔️ Expected Behavior

WSA should also wake up from sleep instantly along with the pc

### ❌ Actual Behavior

It starts loading after the laptop has woken up losing the previous app state in the process.
Would it be possible to have WSA store the app state like android does when you click the power button?
Thanks

### Please specify the version of Windows Subsystem for Android

2303.4000.5.0

**Comment by jaholme** [comment]
What version of Windows are you running?
Please file feedback via Windows Feedback Hub(Windows Key + F).
