### ISSUE TITLE
Access to the port listened by Android Application

### ISSUE THREAD

**Issue by 1552980358** [microsoft/WSA#301]
### Is your feature request related to a problem? Please describe

Maybe not? Because it is related to an update of `VM IP address removed from Settings app. With Advanced Networking, now the IP address of the VM is the same as the host/computer IP` of Build 2205.40000.14.0

### Describe the solution you'd like

With enabled of Advanced Networking, the IP of VM is hidden, but I have a requirement of accessing port listened by my developing app using Ktor server, which for debug, I need to access that from external, i.e. host PC browser. I tried using `http://localhost:<PORT_LISTENED>/<API>`, but responsed `ERR_CONNECTION_REFUSED`.

However, if I obtain the IP of VM using `NetworkInterface`, i.e.
```kotlin
NetworkInterface.getNetworkInterfaces().toList().forEach { networkInterface ->
    networkInterface.inetAddresses.toList().forEach { inetAddress ->
        if (!inetAddress.isLoopbackAddress) {
            if (inetAddress is Inet4Address) {
                Log.d("Android-ip", inetAddress.hostAddress.toString())
            }
        }
    }
 }
```
The output `Android-ip: 172.20.177.118` is workable for accessing my API, i.e. `http://172.20.177.118:<PORT_LISTENED>/<API>`

### Describe alternatives you've considered

Show IP address of VM again, or allow accessing port using `localhost` of host PC

### Please specify the version of Windows Subsystem for Android

2303.40000.5.0

**Comment by kevinkieselbach** [comment]
We're working on networking improvements that should allow connecting from Windows to your Android app's port using localhost (or the Windows IP address).  Right now, that's only supported for ADB's port.  The networking improvements are on our roadmap for this year, but we don't have a precise schedule to share.

**Comment by 1552980358** [comment]
> We're working on networking improvements that should allow connecting from Windows to your Android app's port using localhost (or the Windows IP address). Right now, that's only supported for ADB's port. The networking improvements are on our roadmap for this year, but we don't have a precise schedule to share.

Maybe adding back the IP showing right now for transition before your team's completion of networking improvements for any requirement of network debugging for application developer? Because Google official AVD provides util for network debugging.

**Comment by nieubank** [comment]
Tracking this under #213
