### ISSUE TITLE
Using a virtual camera in WSA to scan QR codes on the screen

### ISSUE THREAD

**Issue by WiseAnswer** [microsoft/WSA#302]
### Is your feature request related to a problem? Please describe

Some applications require the use of Android apps to scan QR codes to log in to an account, which is easy to achieve on some other Android emulators (such as dnplayer). But in WSA, this is very difficult, as WSA cannot use virtual cameras.

### Describe the solution you'd like

When the Android system attempts to call the camera, the user chooses to capture the screen in real-time or use a real camera

### Describe alternatives you've considered

Create a virtual camera using virtual camera software on Windows, but this camera cannot be called in WSA

### Please specify the version of Windows Subsystem for Android

2211.40000.11.0

**Comment by kevinkieselbach** [comment]
We are aware of the missing support for OBS virtual cameras.  This is a limitation in the Windows Media Foundation APIs.  Please file end-user feature requests via Feedback Hub so we can prioritize this against other feature requests.
