### ISSUE TITLE
Add system-level rotation to the camera.

### ISSUE THREAD

**Issue by Danjuanlab** [microsoft/WSA#304]
### Is your feature request related to a problem? Please describe

The current 2303.40000.5.0 version already supports access to some USB webcam devices on the computer. However, most of the webcams on the computer are horizontal screen video, mostly with a resolution of 1920X1080. But when the APP in the Android subsystem to call this webcam, The app is called under the state of the vertical screen. At this time, its behavior is to fill in a 607X1080 9:16 screen from the middle of the 1920X1080 screen. It doesn't make sense and doesn't work well.

### Describe the solution you'd like

Add the camera rotation attribute at the system level, and then the Android subsystem inherits this orientation value when calling the hardware camera. In this way, the APP in the subsystem can use the camera correctly. In reality, we only need to rotate the camera of the hardware device to the correct picture.

### Describe alternatives you've considered

If this cannot be supported, the alternative solution should be to enable the Android subsystem to support virtual cameras, such as OBS virtual cameras, so that we can rotate the screen through OBS and output a vertical 1080X1920 camera screen to make the subsystem app correct. transfer. The best thing is to add a setting in the system to let the front camera and the rear camera in the user-defined subsystem call which device respectively.

### Please specify the version of Windows Subsystem for Android

2303.40000.5.0

**Comment by kevinkieselbach** [comment]
If an app in vertical orientation doesn't work well with a horizontal orientation camera, that is an app bug and would occur on other Android systems with free form windowing, including ChromeOS.  It is not possible for the system to fix this for buggy apps without breaking apps that correctly handle camera orientation.

We are aware of the missing support for OBS virtual cameras.  Please file end-user feature requests via Feedback Hub so we can prioritize this against other feature requests.
