### ISSUE TITLE
fastboot

### ISSUE THREAD

**Issue by yonggamer** [microsoft/WSA#305]
### Is your feature request related to a problem? Please describe

I am missing fastboot

### Describe the solution you'd like

add fastboot

### Please specify the version of Windows Subsystem for Android

2304.40000.5.0

**Comment by mattkopec** [comment]
We currently don't have plans to support fastboot. Can you further detail what development scenarios this is blocking for you?

**Comment by yonggamer** [comment]
I want to install [twrp](https://twrp.me/) for testing [Magisk](https://github.com/topjohnwu/Magisk)

**Comment by mattkopec** [comment]
Thanks for the details.

It appears your intention is to modify/replace the Android image provided with WSA. This is not something we currently plan to support.

The issue tracker is intended for developer issues/feedback related to development of Android applications on WSA.
