### ISSUE TITLE
Android integrated camera app crashing on ARM CPU devices

### ISSUE THREAD

**Issue by jake-brown-maps** [microsoft/WSA#306]
### Steps to reproduce

Our app (ArcGIS Field Maps) uses the Android integrated camera for map data collection workflows.  In the recent preview release (2303.40000.5.0) the workflow has been crashing on our Surface testing devices that utilize ARM processors.  (https://www.microsoft.com/en-us/surface/business/surface-pro-x/processor).  We haven't been able to reproduce the crash on Intel devices.  

We are using the following code the launch the camera app (no recent changes have been made to this approach)

fun Fragment.getCapturePhotoIntent(photoUri: Uri): Intent {
    val captureImageIntent = Intent(MediaStore.ACTION_IMAGE_CAPTURE)
    captureImageIntent.putExtra(MediaStore.EXTRA_OUTPUT, photoUri)
    return captureImageIntent
}

### ✔️ Expected Behavior

- The user taps a button in data collection form to launch the camera app 
- The camera app launches and user can capture photo
- The photo is pushed as a file attachment into the data collection form

### ❌ Actual Behavior

- The user taps a button in data collection form to launch the camera app 
- The camera app launches for a second or so and then disappears
- The parent app crashes, log details below

05-11 12:04:24.239  1459  1459 E AndroidRuntime: FATAL EXCEPTION: main
05-11 12:04:24.239  1459  1459 E AndroidRuntime: Process: com.android.camera2, PID: 1459
05-11 12:04:24.239  1459  1459 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
05-11 12:04:24.239  1459  1459 E AndroidRuntime: 	at com.android.camera.one.v2.OneCameraCharacteristicsImpl.getSupportedPictureSizes(OneCameraCharacteristicsImpl.java:72)
05-11 12:04:24.239  1459  1459 E AndroidRuntime: 	at com.android.camera.settings.ResolutionSetting.getPictureSize(ResolutionSetting.java:156)
05-11 12:04:24.239  1459  1459 E AndroidRuntime: 	at com.android.camera.captureintent.state.StateOpeningCamera.onEnter(StateOpeningCamera.java:189)
05-11 12:04:24.239  1459  1459 E AndroidRuntime: 	at com.android.camera.captureintent.stateful.StateMachineImpl.jumpToState(StateMachineImpl.java:67)

### Other Software

Field Maps - Amazon Appstore Version

### Please specify the version of Windows Subsystem for Android

2303.40000.5.0

**Comment by mattkopec** [comment]
Thanks for reporting this. I understand you're in direct contact with the WSA Team. We're currently investigating the issue.

**Comment by zadesai** [comment]
Thank you for your feedback!
We were able to repro this issue and have a fix for it. The fix will be available in 2306 release.

**Comment by jake-brown-maps** [comment]
Hello @zadesai I have updated to 2306 and the camera app is still not functional on my camera app.

<details>
<summary>Screenshot</summary>
<img src="https://github.com/microsoft/WSA/assets/118556669/dbb93e76-343b-45a9-b97e-93f808af4792" width="600">
</details>

Surface 9 (SQ3)
Windows 11 Pro:
Version: 22H2
OS Build: 22621.1702
WSA: 2306.40000.1.0

**Comment by zadesai** [comment]
@jake-brown-maps thank you for the confirmation. Closing this bug.

> Hello @zadesai I can confirm 2306.40000.3.0 includes fix
