### ISSUE TITLE
On-Screen volume controls in WSA apps

### ISSUE THREAD

**Issue by IzaacJ** [microsoft/WSA#308]
### Is your feature request related to a problem? Please describe

Using WSA on a foldable or tablet device makes it cumbersome, or even hard to adjust the volume without unfolding the device or leaving the app. 

### Describe the solution you'd like

Show on-screen volume controls in each WSA application, maybe something similar to the accessibility option on iOS (AssistiveTouch) or comparable feature in Android.

### Please specify the version of Windows Subsystem for Android

2303.40000.5.0

**Comment by nieubank** [comment]
Please file this request in feedback hub (Win+F) related to the Windows 11 audio mixer functionality.
