### ISSUE TITLE
WSA crash when sideloading apk with Kaspersky's AMSI protect enabled

### ISSUE THREAD

**Issue by Howard20181** [microsoft/WSA#309]
### Steps to reproduce

1. Install WSA
2. Install Kaspersky from https://www.kaspersky.com/downloads/standard-free-trial
3. AMSI protect will enable by default
4. connect via adb
5. sideload apk

### ✔️ Expected Behavior

APK install successfully.

### ❌ Actual Behavior

WSA crashes immediately without any error logs.

### Other Software

Kaspersky in Windows

### Please specify the version of Windows Subsystem for Android

2304.40000.5.0

**Comment by Howard20181** [comment]
Found another incompatible antivirus.
Avira

**Comment by kevinkieselbach** [comment]
Thanks for reporting this.  From crash dumps, it looks like multiple 3rd party AMSI providers incorrectly implement https://learn.microsoft.com/en-us/windows/win32/api/amsi/nf-amsi-iantimalwareprovider-displayname, so we're working on a work-around.

**Comment by Howard20181** [comment]
Fixed in 2304.40000.7.0

**Comment by jaholme** [comment]
> Fixed in 2304.40000.7.0

Thanks for confirming!
