### ISSUE TITLE
WSA marks every sideloaded APP as malware

### ISSUE THREAD

**Issue by Howard20181** [microsoft/WSA#310]
### Steps to reproduce

1. connect via adb
2. disable all anti-virus software installed by users
3. sideload apk using adb

### ✔️ Expected Behavior

APK install successfully.

### ❌ Actual Behavior

When did not disable prevent install malware in the subsystem, all apk sideload failed.

When disabled, all sideloaded app report as malware and pop up a notification.
![image](https://github.com/microsoft/WSA/assets/40033067/ca52228b-83d9-4d92-9c20-7ab845228007)
![image](https://github.com/microsoft/WSA/assets/40033067/5974bb19-894b-45c4-886e-083c76997ffe)

### Please specify the version of Windows Subsystem for Android

2304.40000.5.0

**Comment by MustardChef** [comment]
Also, the detail around how Package verification/ malicious application detection works for WSA is quite unclear.

**Comment by jaholme** [comment]
We believe we have fixed this issue in the next update to the 2304 build that we will be releasing over the next few days.  However, if you can file a feedback hub report with a recording of installing an app that is failing and share the link, we can confirm that we have fixed the issue.

**Comment by MustardChef** [comment]
> We believe we have fixed this issue in the next update to the 2304 build that we will be releasing over the next few days.  However, if you can file a feedback hub report with a recording of installing an app that is failing and share the link, we can confirm that we have fixed the issue.
> 
> 

Great to hear, since the issue was quite the headache.

**Comment by jaholme** [comment]
> Confirmed fixed in 2304.40000.6.0.

Thanks for the confirmation. Closing this out.
