### ISSUE TITLE
why I can't connect to internet?

### ISSUE THREAD

**Issue by U-DI-Page** [microsoft/WSA#312]
### Steps to reproduce

There is not internet when I open apps,

### ❌ Actual Behavior

There is not internet when I open apps,
I found the settings "manage developer settings > WALN" and it show can't access the network
I try to close my system proxy, it still doesn't work
what my android subsystem version is 2304.40000.5.0

![image](https://github.com/microsoft/WSA/assets/14305674/80fbf139-8e91-48c3-a534-23b309314985)

### Please specify the version of Windows Subsystem for Android

2304.40000.5.0

**Comment by nieubank** [comment]
Can you file a feedback hub report for this (Win+F). Is advanced networking turned on this repro? If so, does it also repro with advanced networking turned off?

**Comment by U-DI-Page** [comment]
> Can you file a feedback hub report for this (Win+F). Is advanced networking turned on this repro? If so, does it also repro with advanced networking turned off?

yes, I turned on the advanced networking,and now I think I have solved this problem, I reset the android subsystem software today,and reinstall all the apps, Now the network is fine.But I think there are some UI interaction issue in the manage setting page,feel like it doesn't fit well,or maybe juse I don't know how to use it.
