### ISSUE TITLE
WSAのroot化

### ISSUE THREAD

**Issue by 20101009** [microsoft/WSA#318]
### Describe the solution you'd like

WSAを標準でRoot化してください（Magisk）

### Please specify the version of Windows Subsystem for Android

2207.40000.8.0

**Comment by philnach** [comment]
@20101009, thank you for taking the time to provide feedback.  Can you provide more details as to the issue you seeing?

**Comment by s1204IT** [comment]
> WSAを標準でRoot化してください

それは無理だと思われます。

根底的な理由として、
- Amazonアプリストアがプリインストールされている
  一部のアプリが対策として動作しなくなったり、想定外の動作が発生する事が考えられます。
- `userdebug`ビルドではない
  Android エミュレーターである｢[Nox](https://jp.bignox.com/)｣は`userdebug`ビルドであり、設定１つ変えるだけで`su`バイナリが設置されますが、WSA は Amazon Fire の様に `user` ビルドです。
  https://source.android.com/docs/setup/build/building?hl=ja#choose-a-target

この様な事が原因と考えられます。

少なからず 標準で Magisk を搭載するのは確実にあり得ません。
[KernelSU](https://github.com/tiann/KernelSU) であれば、**Tools/kernel** を書き換えてマネージャーアプリをインストールするだけで済みますので、とりあえずRoot化したいと言う事であれば、KernelSU が楽だと思われます。

---

[MagiskOnWSALocal](https://github.com/LSPosed/MagiskOnWSALocal) や [WSA-Script](https://github.com/YT-Advanced/WSA-Script) の様に、自動で Magisk や KernelSU の変更を充てるツール(?)もあるので、それらを使うのが一番無難かと思います。

**Comment by jaholme** [comment]
Hello, we do not support rooting WSA or any third party scripts which modify WSA.  Thank you for your feedback.
