### ISSUE TITLE
cifs.ko in kernel modules

### ISSUE THREAD

**Issue by BenWaw** [microsoft/WSA#319]
### Is your feature request related to a problem? Please describe

Can somebody tell me where I can find cifs.ko module compatible with this kernel or implement it to core? I want to mount smb share directly into file system using cifsMenager but I need cifs.ko in kernel to do it.

### Describe the solution you'd like

Implement cifs.ko into a kernel

### Describe alternatives you've considered

Provide compatible cifs.ko file, so I can ismod it into kernel file myself

### Please specify the version of Windows Subsystem for Android

2303.40000.5.0

**Comment by kevinkieselbach** [comment]
We're working on a solution for file sharing, so you shouldn't need to mount an SMB share when that's ready.  We don't support modifying the kernel.

**Comment by BenWaw** [comment]
> We're working on a solution for file sharing, so you shouldn't need to mount an SMB share when that's ready. We don't support modifying the kernel.

But I need my app to think it has access to a normal folder when looking at smb share
