### ISSUE TITLE
WSA not working after official installation from microsoft Store

### ISSUE THREAD

**Issue by NervousOrange** [microsoft/WSA#320]
### Steps to reproduce

I have installed WSA from microsoft app store. and the installation is successfull with no issues. but when I try to run it, the `starting windows subsystem for android` appears and after a while it disappears.

I have checked the windows event log viewer and I see this:
`Faulting application name: WsaClient.exe, version: 2304.40000.7.0, time stamp: 0x646d7be3
Faulting module name: WsaClient.exe, version: 2304.40000.7.0, time stamp: 0x646d7be3
Exception code: 0xc0000409
Fault offset: 0x000000000002219e
Faulting process id: 0x0x35F8
Faulting application start time: 0x0x1D993A4517198BA
Faulting application path: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_2304.40000.7.0_x64__8wekyb3d8bbwe\WsaClient\WsaClient.exe
Faulting module path: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_2304.40000.7.0_x64__8wekyb3d8bbwe\WsaClient\WsaClient.exe
Report Id: 59bb6a66-3249-4ba8-b7e5-9d23c945b6e9
Faulting package full name: MicrosoftCorporationII.WindowsSubsystemForAndroid_2304.40000.7.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App`

And I also see an information log on the event viewer associated with wsaClient.exe:

`Fault bucket , type 0
Event Name: MoBEX
Response: Not available
Cab Id: 0

Problem signature:
P1: MicrosoftCorporationII.WindowsSubsystemForAndroid_2304.40000.7.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 2304.40000.7.0
P4: 646d7be3
P5: WsaClient.exe
P6: 2304.40000.7.0
P7: 646d7be3
P8: 000000000002219e
P9: c0000409
P10: 0000000000000007

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_MicrosoftCorpora_ad241b924675401dd34b254bd0825859e08539_5a463d0c_4aa9ea98-717f-4238-bb67-5109fcb5b15b

Analysis symbol: 
Rechecking for solution: 0
Report Id: 243940c8-778e-4353-b4b5-9f32324cc339
Report Status: 4100
Hashed bucket: 
Cab Guid: 0`

this is my laptop specifications if it helps:

**Device name	NervousOrange
Processor	Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor**

I have got some suggestions to change the graphics preference on windows subsystem for android settings to Microsoft Basic Driver but unfortunately it didn't work for me. also tried to uninstall the WSA and reinstall it some issue as above log.

### ✔️ Expected Behavior

To run the WSA smoothly after installation from the Microsoft Store.

### ❌ Actual Behavior

When I try to click manage developer settings on WSA settings the screen starting WSA appears and a progress bar and after a while it disappears. checking the event log viewer, there is a log corresponding to WSA as shared above.

### Please specify the version of Windows Subsystem for Android

2304.40000.7.0

**Comment by jaholme** [comment]
Please file this in feedback hub Windows Key + F under category Apps > Windows Subsystem for Android. If you can recreate your problem with a recording that will be most helpful to us to be able to figure out the underlying cause of the crash.  

I'm closing this issue as we track reliability issues not related to developer issues in feedback hub.
