### ISSUE TITLE
Shared folder appears slightly useless

### ISSUE THREAD

**Issue by internettrollwatt** [microsoft/WSA#323]
### Steps to reproduce

I have moved the locations of folders such as images, music, videos, desktop, and documents, but the feature of sharing user files may not recognize my changes and is still locating the default locations of these folders, resulting in the documents I need not being found in WSA

### ✔️ Expected Behavior

Able to recognize changes in folder location, preferably able to see all Windows files like WSL

### ❌ Actual Behavior

I have moved the locations of folders such as images, music, videos, desktop, and documents, but the feature of sharing user files may not recognize my changes and is still locating the default locations of these folders, resulting in the documents I need not being found in WSA

### Please specify the version of Windows Subsystem for Android

2305.40000.2.0

**Comment by jaholme** [comment]
Please file this feedback via Feedback Hub (Windows key + F), this GitHub is intended for Android app development issues on WSA.
