### ISSUE TITLE
App Links launch choice preference does not persist with Always option

### ISSUE THREAD

**Issue by jake-brown-maps** [microsoft/WSA#328]
### Steps to reproduce

1. Launch an app with app link (https://fieldmaps.arcgis.app/)
2. Observe choice prompt: `Select an app to open this website`
<details>
<summary>screenshot</summary>

<img src="https://github.com/microsoft/WSA/assets/118556669/50aadd12-1aa8-4052-b91b-621280aa6aa1" width="500">
</details>

3. Select `WSA` then `Always`
4. Observe app link open application correctly
5. Close application
6. Launch an app with app link (https://fieldmaps.arcgis.app/)
7. Observe choice prompt appears again

We do not see this prompt in `2304`

### ✔️ Expected Behavior

After selecting Always the link should be associated with WSA as the preferred application.

### ❌ Actual Behavior

Choice prompt appears each launch

### Please specify the version of Windows Subsystem for Android

2305.40000.2.0

**Comment by dabhattimsft** [comment]
Hi, can you share contents of this reg key: HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\AppUrlAssociations\fieldmaps.arcgis.app ?

**Comment by jake-brown-maps** [comment]
Here you are @dabhattimsft ![image](https://github.com/microsoft/WSA/assets/118556669/637396f9-9eb0-4ed0-a777-b65e5062ffa4)

**Comment by dabhattimsft** [comment]
It doesn't seem to repro on my end. Can you share Windows build number? And contents of this reg key?
HKEY_USERS\<user-sid>_Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\AppUriHandlers\fieldmaps.arcgis.app

**Comment by jake-brown-maps** [comment]
Hey @dabhattimsft  looks like it's working okay for me now - perhaps it was an isolated issue.  BTW, my preview build was upgraded to 2305.40000.4.0 

Including the registry info...
![image (11)](https://github.com/microsoft/WSA/assets/118556669/f4625bf6-dace-4cf5-97d9-970b0c13ed8b)

**Comment by dabhattimsft** [comment]
Thanks for the update. Registry values look fine. I'll close the issue now.
