### ISSUE TITLE
WSA crashes with overrun error

### ISSUE THREAD

**Issue by Aphexus** [microsoft/WSA#329]
### Steps to reproduce

Trying to run WSA gives the error:

WsaClient.exe - System Error

The system detected and overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.

IIRC it worked the first time I installed it but I haven't used it since(kinda forgot about it) but I went to use it and I can't get it to start up as this error prevents it from working.

I tried viewing the diagnostic data but nothing is created(this error pops up immediately on top of the "Windows Subsystem For Android" window.

### ❌ Actual Behavior

Crashes.

### Please specify the version of Windows Subsystem for Android

2301.40000.7.0

**Comment by MustardChef** [comment]
From what I have seen, running WSA on CPUs that are not officially supported (do not meet the requirements of WSA), specifically really old CPUs (2nd to 6th Gen Intel Core Processors), often results in this error.

**Comment by Aphexus** [comment]
> From what I have seen, running WSA on CPUs that are not officially supported (do not meet the requirements of WSA), specifically really old CPUs (2nd to 6th Gen Intel Core Processors), often results in this error.

As I said, it worked fine. Also, brand new top of the line comp. Has nothing to do with hardware specs and I did not change anything since then it was working except for software and windows updates.

**Comment by MustardChef** [comment]
> > From what I have seen, running WSA on CPUs that are not officially supported (do not meet the requirements of WSA), specifically really old CPUs (2nd to 6th Gen Intel Core Processors), often results in this error.
> 
> As I said, it worked fine. Also, brand new top of the line comp. Has nothing to do with hardware specs and I did not change anything since then it was working except for software and windows updates.

@Aphexus Please file a feedback hub report with as suggested.

**Comment by Aphexus** [comment]
So just now I went to remove WSA using add and remove programs in windows and in the process I came across the ability to reset the settings in it so I went ahead and tried that first the then WSA started right up. Not sure if that had anything to do with it or if something else in between then and now changed on my system that somehow effected it as I didn't try to run it before I went to remove it to see if it was going to work(I just assumed it wouldn't).
