### ISSUE TITLE
Start WSA minimized 

### ISSUE THREAD

**Issue by Mitia99** [microsoft/WSA#333]
### Is your feature request related to a problem? Please describe

 It's frustrating to always see this screen on windows start cause the app is launching on windows startup.
![Capture d’écran 2023-06-16 083059](https://github.com/microsoft/WSA/assets/56766778/102df1f9-3e1f-4ab5-9778-ebc70088b8c8)

### Describe the solution you'd like

Start the app minimized (on tray)

### Please specify the version of Windows Subsystem for Android

2305.40000.2.0

**Comment by kevinkieselbach** [comment]
The splash screen should only appear if you had an Android window open when Windows restarted.  On restart, Windows relaunches previously running apps, and many apps (e.g., Office) show splash screens to indicate progress.  If you don't want Android windows to reopen on restart, then make sure to close them before restarting Windows.  Unless you didn't have Android windows open before the restart, this behavior is intended.  As a reminder, our GitHub is for developers to report technical issues.  Please submit end user feature requests in Feedback Hub.
