### ISSUE TITLE
app quits unexpectedly

### ISSUE THREAD

**Issue by Cashew-wood** [microsoft/WSA#336]
### Steps to reproduce

open app
About 10 seconds later, the app will quits unexpectedly
log file:C:\Users\??\AppData\Local\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalState\diagnostics\logcat
[20230618051930.log](https://github.com/microsoft/WSA/files/11780719/20230618051930.log)

### ❌ Actual Behavior

app will quits unexpectedly

### Other Software

wsa:2305.40000.5.0
windows 11: 23H2 25381.1200

### Please specify the version of Windows Subsystem for Android

2305.40000.5.0

**Comment by jaholme** [comment]
Please file this bug in Windows Feedback Hub (Windows Key + F) under category Apps > Windows Subsystem for Android. In Step4 include a recording of WSA failing to launch.  

Our Github repository is primarily for developer related feedback and end-user problems are not actionable without Feedback hub logs.
