### ISSUE TITLE
fix (make sure that virtualization is enabled in bios and virtual machine platform is turned on for your pc)

### ISSUE THREAD

**Issue by sherifHS** [microsoft/WSA#340]
### Provide a description of requested docs changes

i have virtualization enabled and virtual machine platform enabled and i have same error

**Comment by zadesai** [comment]
Can you file a feedback hub report with the repro and paste the link here so we can see what's going on?

**Comment by hamza-usmani** [comment]
A screenshot of the issue would be useful as well!
