### ISSUE TITLE
Too long time the WSA runtime process quit after I quit the Android App at setting as Needed mode

### ISSUE THREAD

**Issue by wormwang** [microsoft/WSA#341]
### Is your feature request related to a problem? Please describe

WSA runtime quit time  ,at  as Needed mode

### Describe the solution you'd like

about 15 min , it is too long time the WSA runtime process quit after I quit the Android App at setting as Needed mode

### Describe alternatives you've considered

I want 1 or 2 min the WSA runtime process quit and release the memory and cpu used by WSA runtiime,  after I quit the Andriod App at as Needed mode

### Please specify the version of Windows Subsystem for Android

2305.40000.6

**Comment by zadesai** [comment]
Thanks for the feedback. This is by design and the current timeout is set to 10 minutes. This is not currently on our roadmap, but we will continue to reevaluate.
