### ISSUE TITLE
某些基于Unity引擎的游戏运行出现问题

### ISSUE THREAD

**Issue by oupanyu** [microsoft/WSA#351]
### Steps to reproduce

![屏幕截图 2023-06-27 110736](https://github.com/microsoft/WSA/assets/60055803/0806fdd7-bf26-412a-9f75-967a2854597e)
![屏幕截图 2023-07-04 103411](https://github.com/microsoft/WSA/assets/60055803/27ad9607-ad53-4abe-8e8f-2bf44e7f117d)
如图，游戏Orzmic在显示"Made with Unity"后黑屏无法进入游戏

使用任意版本的Project Sekai:Colorful Stage在进行3D渲染(新手教程、演出（音游开始）)前均会黑屏，此时点击操作仍能识别，黑屏时间为6-10分钟，查看任务管理器发现该游戏下子系统进程内存申请缓慢

同为Unity引擎的Sonolus可以快速进入并游玩游戏

### ✔️ Expected Behavior

两款游戏均能迅速加载进入游戏

### ❌ Actual Behavior

两款游戏开始游戏前黑屏，难以进入

### Other Software

Orzmic (version 2.18.21)
Project Sekai:Colorful Stage (任意区服，version2.3.1)
Sonolus (version0.7.0)

### Please specify the version of Windows Subsystem for Android

2305.40000.5.0

**Comment by xhan65** [comment]
Thanks for your feedback. I was not able to repro this with Orzmic 2.18.21 on WSA 2305.40000.6.0. The game rendered fine and I was able to play though a song. 

If this still repros for you on latest WSA, could you please report this via Feedback Hub instead so we can gather the logs from your WSA instance?
