### ISSUE TITLE
设置中修改显示大小和字体大小，重启后不会保留

### ISSUE THREAD

**Issue by bzkmsjy** [microsoft/WSA#354]
### Steps to reproduce

打开wsa://com.android.settings
进入显示——显示大小和文字——修改字体大小和显示大小
重启WSA

### ✔️ Expected Behavior

修改显示大小和字体大小

### ❌ Actual Behavior

修改失效，重启WSA后显示大小和字体大小恢复默认状态

### Please specify the version of Windows Subsystem for Android

2305.40000.6.0

**Comment by xhan65** [comment]
Thanks for the feedback. Changing scale factors in Android Settings is not a supported scenario. Users should go to Windows Settings to update the scale factors, which will be respected by WSA.
