### ISSUE TITLE
The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.

### ISSUE THREAD

**Issue by SunnyLeu** [microsoft/WSA#366]
### Steps to reproduce

It happens everytime when I try to start WSA.

### ✔️ Expected Behavior

WSA start normaly, no error message.

### ❌ Actual Behavior

![image](https://github.com/microsoft/WSA/assets/51817348/10c435e2-3b0a-48a7-8e88-a987d33267d1)
The error is `The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.`

### Please specify the version of Windows Subsystem for Android

2305.40000.6.0

**Comment by jaholme** [comment]
Please file a feedback hub report (Windows Key + F) under category Apps > Windows Subsystem for Android. Without this we cannot diagnose why WSA is running into an issue.

**Comment by ajfpay** [comment]
you can type on CMD Administrator 

```
sfc /scannow
```

After finish scan, you can look the information on CMD, yeah this windows corrupt, and reboot for fixed.
