### ISSUE TITLE
汽水音乐闪退

### ISSUE THREAD

**Issue by MOldtime** [microsoft/WSA#372]
### Steps to reproduce

在首次打开汽水音乐后播放一段时间 再次打开就会触发闪退

### ✔️ Expected Behavior

不闪退 正确使用

### ❌ Actual Behavior

打开过一两秒就闪退

### Other Software

无 没有其它软件交互 

### Please specify the version of Windows Subsystem for Android

2306.4000.4

**Comment by MOldtime** [comment]
该问题也通过 反馈中文反馈

**Comment by jaholme** [comment]
Please file feedback via Windows Feedback Hub under category Apps > Windows Subsystem for Android. That will collect more logs and allow us to further diagnose the problem. This forum is intended for app developer feedback.
