### ISSUE TITLE
Full Screen Control

### ISSUE THREAD

**Issue by malikamir2647** [microsoft/WSA#373]
### Is your feature request related to a problem? Please describe

It is the improvement in apps full screen feature

### Describe the solution you'd like

I like this way of controlling full screen apps 

https://github.com/microsoft/WSA/assets/105973744/c1eb9ae7-1837-47e4-a6a5-a2b92c1eb04d

### Please specify the version of Windows Subsystem for Android

2306.40000.4

**Comment by jaholme** [comment]
Please file end-user feature requests via Windows feedback hub (Windows key + F) under category Apps > Windows Subsystem for Android. This forum is intended to address Android app developer feedback.
