### ISSUE TITLE
WSA Loads For a Few Seconds Then Disappears

### ISSUE THREAD

**Issue by Orski174** [microsoft/WSA#379]
### Steps to reproduce

- Install WSA, wether from store sideloading or custom builds.
- Open WSA and try launching an app

This of course should usually work for anyone. Reproducing what I have isn't possible at the moment because I'm not sure what's happening.

### ✔️ Expected Behavior

App runs Normally.

### ❌ Actual Behavior

WSA loading screen appears and loads for a few seconds then disappears.

### Please specify the version of Windows Subsystem for Android

2307.40000.2.0, 2306.40000.4.0, 2305.40000.6.0

**Comment by Orski174** [comment]
I've installed WSA using the store, sideloading and custom builds. I've tried manually installing missing modules, uninstalled and reinstalled disabling windows services and reenabling them. But it just won't work, but after installing the missing vcredis modules no more error dialog boxes appeared but it still wouldn't launch, so I checked event viewer and they all returned the same error for all three builds. ([Event viewer report](https://pastebin.com/TKidPrBZ)).

Your help will be greatly appreciated.

Thank you.

**Comment by internettrollwatt** [comment]
I have also encountered a similar problem, and after downloading WSA again, the problem has been resolved. I hope it can help you

**Comment by Orski174** [comment]
I've tried redownloading many times, it didn't work.

**Comment by MustardChef** [comment]
> I've tried redownloading many times, it didn't work.

Can you check if its the same issue on 2307.40000.3.0, https://github.com/MustardChef/WSAPackages/releases/tag/WSA_2307.40000.3.0

**Comment by MustardChef** [comment]
> Same issue here. Event log shows ucrtbase.dll being the culprit. @MustardChef @Orski174 I was able to downgrade to a 2304 build with success, a working workaround for me for now.

@Jon-edge I would also recommend filing a Feedback Hub report and pasting the link here.

<details>     
   <summary>How to file a Feedback Hub report for WSA: (Click Here)</summary>


### Filing a Feedback Hub Report 

I would very much recommend you to file a Feedback Hub report. Make sure you are logged into a Microsoft Account when filing a report. (You can only file a report using the official version)

</br>

Instructions: (As shown by one of devs in WSA Development team at Microsoft)

</br>

![image](https://github.com/MustardChef/WSABuilds/assets/68516357/1969caa3-2f1d-4967-9166-6833e7509ba5)
![image](https://github.com/MustardChef/WSABuilds/assets/68516357/3a343513-896c-4f7d-b425-3e6ad9aac1a8)
![image](https://github.com/MustardChef/WSABuilds/assets/68516357/52cd8033-b8a9-4de0-a71e-d03e851a4736)
![image](https://github.com/MustardChef/WSABuilds/assets/68516357/dca7b5cb-887a-4436-a760-b65b2ba6b096)

### After Filing a Feedback Hub Report:

![image](https://github.com/MustardChef/WSABuilds/assets/68516357/14cd3785-8630-4368-b1b4-95edb08ed53e)

</details>

**Comment by Orski174** [comment]
I'm so sorry for the late replies, I had exams.

Thanks @MCDeltaT, I will try the new version.

**Comment by philnach** [comment]
@Orski174, thank you for taking the time to file feedback. As @MustardChef mentioned, can you please file feedback via Windows Feedback Hub (Windows key + F) under category Apps > Windows Subsystem for Android and include a recording of your issue. This forum is intended for app developer feedback.
