### ISSUE TITLE
android application does not receive UDP (broadcast and unicast)

### ISSUE THREAD

**Issue by kpx1894** [microsoft/WSA#383]
### Steps to reproduce

The SkyDemon Android application is not receiving UDP messages from the local network. I am broadcasting UDP messages from the same host where the SkyDemon app is running. This setup used to work approximately a month ago. I have verified that UDP messages are still being broadcasted by ensuring the SkyDemon app can receive them when running on a physical Android device within the same network.

### ✔️ Expected Behavior

The Android app (SkyDemon) running under WSA should receive UDP multicast messages from the local area network.

### ❌ Actual Behavior

The Android app (SkyDemon) running under WSA is not receiving UDP multicast messages from the local area network.

### Other Software

tested on:
[SkyDemon for Android 3.16.9](https://www.skydemon.aero/extras/android/aero.skydemon.skydemonandroid.3.16.9.apk)
[SkyDemon for Android 3.16.6](https://www.skydemon.aero/extras/android/aero.skydemon.skydemonandroid.3.16.6.apk)

### Please specify the version of Windows Subsystem for Android

2306.40000.4.0

**Comment by kpx1894** [comment]
UDP works as expected with WSA 2303.40000.3.0 (my best guess when it was still working). So it appears to be some regression.

**Comment by bubbleguuum** [comment]
Yes Multicast is broken since the the "Local network access" replaced "Advanced networking" option and the refactor of networking that went with it. Also see #378

**Comment by kpx1894** [comment]
How can I prevent WSA from updating automatically to a broken version? I disabled autoupdate for Windows Store apps but it does not seem to stop WSA from updating. Every day I have to reinstall WSA and Android apps.

**Comment by philnach** [comment]
@kpx1894, thank you for taking the time to provide feedback.  Unfortunately, there is no way to prevent WSA from updating. As @bubbleguuum indicated we are working on improving the local network access feature.  Let's use #378, to track UDP support.
