### ISSUE TITLE
QQ compatibility issues MSF process keeps crashing repeatedly

### ISSUE THREAD

**Issue by callng** [microsoft/WSA#384]
### Steps to reproduce

This problem occurs in the current latest version 8.9.73, while the older version 8.9.71 does not have the problem

[new version download 8.9.73](https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_8.9.73_64.apk)

[old version download 8.9.71](https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_8.9.71_64.apk)

After opening the app and entering the account password and clicking on the login button and waiting for a response, about 40 seconds later there was an error window "com.tencent.mobileqq.msf.service.MsfService timeout".

--------- beginning of crash
08-06 05:49:07.286   878  1145 F libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x72b7229f9230 in tid 1145 (logWriteThread), pid 878 (nt.mobileqq:MSF)
08-06 05:49:07.671  3265  3265 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-06 05:49:07.671  3265  3265 F DEBUG   : Build fingerprint: 'google/raven/raven:13/TQ3A.230705.001/2307.40000.2.0:user/release-keys'
08-06 05:49:07.671  3265  3265 F DEBUG   : Revision: '0'
08-06 05:49:07.671  3265  3265 F DEBUG   : ABI: 'x86_64'
08-06 05:49:07.671  3265  3265 F DEBUG   : Timestamp: 2023-08-06 05:49:07.330176300+0800
08-06 05:49:07.671  3265  3265 F DEBUG   : Process uptime: 8s
08-06 05:49:07.671  3265  3265 F DEBUG   : Cmdline: com.tencent.mobileqq:MSF
08-06 05:49:07.671  3265  3265 F DEBUG   : pid: 878, tid: 1145, name: logWriteThread  >>> com.tencent.mobileqq:MSF <<<
08-06 05:49:07.671  3265  3265 F DEBUG   : uid: 10071
08-06 05:49:07.671  3265  3265 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x000072b7229f9230
08-06 05:49:07.671  3265  3265 F DEBUG   :     rax 0000000000000000  rbx 000072b9c6d05bf0  rcx 0000000000000001  rdx 000072b9c6d05ac0
08-06 05:49:07.671  3265  3265 F DEBUG   :     r8  0000000000000000  r9  0000000000000008  r10 0000000000000008  r11 0000000000000246
08-06 05:49:07.671  3265  3265 F DEBUG   :     r12 000072b9befd3c60  r13 0000000000000001  r14 000072b9c6d05ac0  r15 000072b9d6585750
08-06 05:49:07.671  3265  3265 F DEBUG   :     rdi 000072b744dfae10  rsi 000072b894e1f030
08-06 05:49:07.671  3265  3265 F DEBUG   :     rbp 000072b723355168  rsp 000072b9c6d05848  rip 000072b7229f9230
08-06 05:49:07.671  3265  3265 F DEBUG   : backtrace:
08-06 05:49:07.671  3265  3265 F DEBUG   :       #00 pc 00000000003f9230  /apex/com.android.art/lib64/libart.so (art::ReaderWriterMutex::IsSharedHeld(art::Thread const*) const+0) (BuildId: a5a11e17ddeb3fe4395528da1842c05c)
08-06 05:49:07.671  3265  3265 F DEBUG   :       #01 pc 0000000000493915  /apex/com.android.art/lib64/libart.so (art::FaultManager::IsInGeneratedCode(siginfo*, void*, bool)+117) (BuildId: a5a11e17ddeb3fe4395528da1842c05c)
08-06 05:49:07.671  3265  3265 F DEBUG   :       #02 pc 0000000000493382  /apex/com.android.art/lib64/libart.so (art::FaultManager::HandleFault(int, siginfo*, void*)+82) (BuildId: a5a11e17ddeb3fe4395528da1842c05c)
08-06 05:49:07.671  3265  3265 F DEBUG   :       #03 pc 0000000000002fcb  /apex/com.android.art/lib64/libsigchain.so (art::SignalChain::Handler(int, siginfo*, void*)+603) (BuildId: e4120e0a5f6b7cc84b8bc4c24e4b1ff3)
08-06 05:49:07.671  3265  3265 F DEBUG   :       #04 pc 000000000005b8c0  /apex/com.android.runtime/lib64/bionic/libc.so (__restore_rt+0) (BuildId: 76cb658c499bceaab85932d1254e26df)
08-06 05:49:07.671  3265  3265 F DEBUG   :       #05 pc 000000000037b07f  /apex/com.android.art/lib64/libart.so (BuildId: a5a11e17ddeb3fe4395528da1842c05c)
08-06 05:49:07.671  3265  3265 F DEBUG   :       #06 pc 0000000000526a55  /system/framework/x86_64/boot-framework.oat (android.os.MessageQueue.next+325) (BuildId: b695725ca34e3afad9ec6e0318a8dc6f3ed59144)
08-06 05:49:07.671  3265  3265 F DEBUG   :       #07 pc 00000000005000b7  [anon:dalvik-main space (region space)]
08-06 05:49:07.671  3265  3265 F DEBUG   :       #08 pc 0000000000523df6  /system/framework/x86_64/boot-framework.oat (android.os.Looper.loopOnce+150) (BuildId: b695725ca34e3afad9ec6e0318a8dc6f3ed59144)
08-06 05:49:07.671  3265  3265 F DEBUG   :       #09 pc 00000000005000b7  [anon:dalvik-main space (region space)]
08-06 05:49:07.671  3265  3265 F DEBUG   :       #10 pc 0000000000523c8e  /system/framework/x86_64/boot-framework.oat (android.os.Looper.loop+478) (BuildId: b695725ca34e3afad9ec6e0318a8dc6f3ed59144)
08-06 05:49:07.671  3265  3265 F DEBUG   :       #11 pc 0000000000500087  [anon:dalvik-main space (region space)]
08-06 05:49:07.671  3265  3265 F DEBUG   :       #12 pc 0000000000522ece  /system/framework/x86_64/boot-framework.oat (android.os.HandlerThread.run+526) (BuildId: b695725ca34e3afad9ec6e0318a8dc6f3ed59144)
08-06 05:49:07.671  3265  3265 F DEBUG   :       #13 pc 000000000079d07f  [anon:dalvik-/system/framework/boot-framework.art]
08-06 05:49:07.671  3265  3265 F DEBUG   :       #14 pc 0000000000372144  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+756) (BuildId: a5a11e17ddeb3fe4395528da1842c05c)
08-06 05:49:07.689   381  3271 I DropBoxManagerService: add tag=data_app_native_crash isTagEnabled=true flags=0x2
08-06 05:49:07.776   381   703 I ActivityManager: Process com.tencent.mobileqq:MSF (pid 878) has died: svc SVC 
08-06 05:49:07.777   381   703 W ActivityManager: Scheduling restart of crashed service com.tencent.mobileqq/.msf.service.MsfService in 1000ms for start-requested
08-06 05:49:08.162   381   703 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10071; state: DISABLED
08-06 05:49:08.162   381   703 D CompatibilityChangeReporter: Compat change id reported: 177438394; UID 10071; state: DISABLED
08-06 05:49:08.162   381   703 D CompatibilityChangeReporter: Compat change id reported: 135772972; UID 10071; state: DISABLED
08-06 05:49:08.162   381   703 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10071; state: DISABLED
08-06 05:49:08.162   381   417 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10071; state: DISABLED
08-06 05:49:08.166   381   417 I ActivityManager: Start proc 3301:com.tencent.mobileqq:MSF/u0a71 for service {com.tencent.mobileqq/com.tencent.mobileqq.msf.service.MsfService}
08-06 05:49:08.822   381   707 W OverlayManager: service 'idmap' died
08-06 05:49:10.332   381   704 D OomAdjuster: Not killing cached processes
08-06 05:49:10.489   381   708 D CompatibilityChangeReporter: Compat change id reported: 161145287; UID 10071; state: DISABLED
08-06 05:49:10.491    52    69 I keystore2: keystore2::watchdog: Watchdog thread idle -> terminating. Have a great day.
08-06 05:49:10.764   381   704 D CompatibilityChangeReporter: Compat change id reported: 168419799; UID 10034; state: DISABLED
08-06 05:49:10.764   381   704 D CompatibilityChangeReporter: Compat change id reported: 273564678; UID 10034; state: DISABLED
08-06 05:49:10.765   381   813 D CompatibilityChangeReporter: Compat change id reported: 194532703; UID 10034; state: ENABLED
08-06 05:49:11.613   381   416 W BroadcastQueue: Permission Denial: broadcasting Intent { act=android.intent.action.MEDIA_SCANNER_FINISHED dat=file:///... flg=0x10 } from com.android.providers.media.module (pid=840, uid=10055) to com.tencent.mobileqq/.msf.core.NetConnInfoCenter is not exported from uid 10071
08-06 05:49:11.614   864   864 I FileSystemRedirectionHandler: Media scan of primary external storage completed.
08-06 05:49:11.924   381   433 I DisplayPowerController[0]: BrightnessEvent: disp=0, physDisp=local:100, brt=0.05, initBrt=0.39763778, rcmdBrt=NaN, preBrt=NaN, lux=0.0, preLux=0.0, hbmMax=1.0, hbmMode=off, rbcStrength=0, powerFactor=1.0, thrmMax=1.0, wasShortTermModelActive=false, flags=, reason=manual [ dim ], autoBrightness=false

### ✔️ Expected Behavior

The CAPTCHA loading page appears normally, instead of staying stuck at login and then timing out.

### ❌ Actual Behavior

Wait after clicking the login button and then "com.tencent.mobileqq.msf.service.MsfService timeout" appears.

### Other Software

No other

### Please specify the version of Windows Subsystem for Android

2307.40000.2.0

**Comment by philnach** [comment]
@callng, thank you for taking the time to provide feedback.  Can you please file feedback via Windows Feedback Hub (Windows key + F) under category Apps > Windows Subsystem for Android and include a recording of your issue. This forum is intended for app developer feedback.

**Comment by callng** [comment]
I gave feedback on the issue in the feedback center, this is the URL address https://aka.ms/AAm2qsi
