### ISSUE TITLE
Local network access enabled, cannot connect to VPN

### ISSUE THREAD

**Issue by jake-brown-maps** [microsoft/WSA#390]
### Steps to reproduce

After establishing a connection to VPN (Global Protect client) on my Windows machine.  If I have `Local network access` toggled `ON`, my app is not able to connect to a server on VPN.  If i toggle `OFF` `Local network access` my app can connect okay.  I see from the 2306 update there were some updates:

> Local networking (under Advanced settings - Experimental features) now replacing "Advanced networking". Android apps can connect to devices on the same network, on all versions of Windows, respect Windows firewall rules, and work with VPNs

### ✔️ Expected Behavior

When `Local network access` is toggled `ON` and hosting Windows machine has an active VPN connection - WSA apps can access resources using the VPN connection

### ❌ Actual Behavior

When `Local network access` is toggled `ON` and hosting Windows machine has an active VPN connection - WSA apps CANNOT access resources using the VPN connection

### Please specify the version of Windows Subsystem for Android

2306

**Comment by yk00365** [comment]
Not only this same as you, but also the ipv6 connection is not well supported.
https://github.com/microsoft/WSA/issues/389

**Comment by philnach** [comment]
@yk00365, can you please file feedback via Windows Feedback Hub (Windows key + F) under category Apps > Windows Subsystem for Android and include a recording of your issue. The additional logs will help us understand what's going on.

**Comment by jake-brown-maps** [comment]
@philnach I see the comment is closed, do you have any recommendation on how I should proceed with this issue?  

cc @timkur
