### ISSUE TITLE
WSA-Discord Rich Presence

### ISSUE THREAD

**Issue by grandma77** [microsoft/WSA#392]
### Describe the solution you'd like

ability for games to show up in discord individually

### Please specify the version of Windows Subsystem for Android

all

**Comment by grandma77** [comment]
this thing could work without too much work by telling samsung to make the game launcher and those game thingys work on x64, and mybe some apps that game plugins rely on

**Comment by philnach** [comment]
@grandma77, thank you for your feedback. This forum is intended for app developer feedback.  Searching on the internet it looks like you can provide feedback to Discord here: [https://support.discord.com/hc/en-us/articles/213490807-Where-can-I-submit-Feature-Requests-Feedback-and-Suggestions-](https://support.discord.com/hc/en-us/articles/213490807-Where-can-I-submit-Feature-Requests-Feedback-and-Suggestions-)
