### ISSUE TITLE
贪婪洞窟4.0.25无法启动

### ISSUE THREAD

**Issue by Autumn0039** [microsoft/WSA#398]
### Steps to reproduce

安装贪婪洞窟4.0.25无法打开，打开无响应
![wsaapp管理界面](https://github.com/microsoft/WSA/assets/37785430/b124939d-a6c2-4d51-8a2c-34e8428e35dd)

### ✔️ Expected Behavior

open

### ❌ Actual Behavior

No response

### Other Software

WSA 版本2307.40000.5.0
贪婪洞窟版本 4.0.25

### Please specify the version of Windows Subsystem for Android

2307.40000.5.0

**Comment by philnach** [comment]
@Autumn0039. Can you please file feedback via Windows Feedback Hub (Windows key + F) under category Apps > Windows Subsystem for Android and include a recording of your issue. This forum is intended for app developer feedback.  The game also doesn't appear to be available in the Microsoft Store.  Can you also include information as to where to install it from?
