### ISSUE TITLE
Asus instant guard not connecting to local network

### ISSUE THREAD

**Issue by zany130** [microsoft/WSA#399]
### Steps to reproduce

1. Install https://play.google.com/store/apps/details?id=com.asus.asusinstantguard
2. Connect your PC to same the same network as your ASUS router with instant guard
3. enable local network option in WSA setting -> advanced options
4. launch instant guard and try to pair it with your router
5. notice the error about no Asus router detected on the devices network

### ✔️ Expected Behavior

Detects ASUS router and pairs it.

### ❌ Actual Behavior

Does not detect the ASUS router and pair it.

### Please specify the version of Windows Subsystem for Android

2306.40000.4.0

```
Processor	11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   3.00 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points
```
```
Edition	Windows 11 Home
Version	22H2
Installed on	‎7/‎28/‎2023
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0
```

**Comment by philnach** [comment]
@zany130 , thank you for taking the time to file a bug.  Unfortunately, since Instant Guard isn't available through the Microsoft Store the app might not work well with WSA.  We'll add it to the backlog.

**Comment by philnach** [comment]
@zany130, on second thought. Can you please file feedback via Windows Feedback Hub (Windows key + F) under category Apps > Windows Subsystem for Android and include a recording of your issue.  This forum is intended for app developer feedback.
