### ISSUE TITLE
Autorun a command after WSA starts

### ISSUE THREAD

**Issue by lasersPew** [microsoft/WSA#400]
### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

I would like to have a settings entry that has placeholder of which will be run after (preferably) WSA starts. it would be useful specifically since some apps people use are extension-based(small apks that work like a library but can't be incorporated in the app since they get updated quite frequently), it is preferable if there's a way to implement this since some of the apps that do have that^^ are compatible with [Shizuku](https://shizuku.rikka.app/), which needs to be triggered with this command: `adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh`. It would be kinda great if this gets automated.

### Describe alternatives you've considered

Manually connecting to device using adb and running the command.

### Please specify the version of Windows Subsystem for Android

2306.40000.4.0

**Comment by philnach** [comment]
@laserspew, thank you for the feedback request and interesting scenario.  Unfortunately, that's not a feature that's part of the Android platform.  There are many ways you could accomplish that using Windows such as the [Windows Task Scheduler](https://learn.microsoft.com/en-us/windows/win32/taskschd/about-the-task-scheduler) or with a simple program that watches for WSA using some sort of [process monitoring](https://stackoverflow.com/a/1986856) to start and then runs the adb command.
