### ISSUE TITLE
OpenGLES 3.1 Extension Pack

### ISSUE THREAD

**Issue by mio-19** [microsoft/WSA#403]
### Is your feature request related to a problem? Please describe

A certain game requires GLES3.1 to run

![Screenshot 2023-08-17 220511](https://github.com/microsoft/WSA/assets/57285379/4f248b8c-456f-480f-9b46-0ada0b87089f)

### Describe the solution you'd like

Support OpenGLES 3.1 Extension Pack

### Please specify the version of Windows Subsystem for Android

2307.40000.3.0

**Comment by nieubank** [comment]
This is being tracked under #211
