### ISSUE TITLE
Can't control brightness and audio in app

### ISSUE THREAD

**Issue by Mitia99** [microsoft/WSA#424]
### Steps to reproduce

1. Download [VLC for Android](https://play.google.com/store/apps/details?id=org.videolan.vlc&hl=fr&gl=US)
2. Play a video
3. Use swipe gestures to control brightness
![image](https://github.com/microsoft/WSA/assets/56766778/5a32d132-57e5-4517-9e73-c182edf4f92b)

### ✔️ Expected Behavior

VLC for Android should be able to control Windows brightness

### ❌ Actual Behavior

Nothing happens

### Please specify the version of Windows Subsystem for Android

2308.40000.1.0

**Comment by Mitia99** [comment]
There's the same issue when trying to control audio with in-app controls like in [Musicolet](https://play.google.com/store/apps/details?id=in.krosbits.musicolet&hl=fr&gl=US)
![image](https://github.com/microsoft/WSA/assets/56766778/2c9fe00e-991e-41e9-95f5-c44531159478)

**Comment by xhan65** [comment]
Thanks for the feedback. We don't allow an Android app to adjust the screen brightness. Users can always go to Action Center /Windows Settings to adjust the brightness. Per-app volume control is also not supported in WSA. Users should adjust windows volume instead.
