### ISSUE TITLE
Only one computer, unable to build dns,53 port is occupied

### ISSUE THREAD

**Issue by aogg** [microsoft/WSA#426]
### Is your feature request related to a problem? Please describe

Only one computer, unable to build dns,53 port is occupied

### Describe the solution you'd like

There is a place to customize the dns server

### Please specify the version of Windows Subsystem for Android

MicrosoftCorporationII.WindowsSubsystemForAndroid_2306.40000.4.0_neutral_~_8wekyb3d8bbwe

**Comment by xhan65** [comment]
Thank you for the feature request. Windows Subsystem for Android (WSA) shares Windows network connection, so you need to change your Windows 11 DNS settings ([instructions](https://support.microsoft.com/en-us/windows/change-tcp-ip-settings-bd0a07af-15f5-cd6a-363f-ca2b6f391ace)).
