### ISSUE TITLE
WSA fails to wake up from partially running state

### ISSUE THREAD

**Issue by bpsib** [microsoft/WSA#427]
### Steps to reproduce

1. Open an app so WSA starts.
2. Close the app.
3. Wait for some minutes so WSA closes down to the partially running state.
4. Open an app again.

### ✔️ Expected Behavior

WSA should start again within a few seconds

### ❌ Actual Behavior

WSA hangs with "Starting Windows Subsystem for Android" for a couple of minutes then fails to start. I then need to kill the WsaService.exe process to get it working again.

### Please specify the version of Windows Subsystem for Android

2307.40000.6.0

**Comment by xhan65** [comment]
Please file a Feedback hub report (Windows key + F) under category Apps > Windows Subsystem for Android. On step 4 "Add more details" please add a recording recreating the problem of WSA not waking up from partially running state.
