### ISSUE TITLE
Support .cer files in Windows file sharing tool

### ISSUE THREAD

**Issue by jake-brown-maps** [microsoft/WSA#428]
### Is your feature request related to a problem? Please describe

When trying to install a root certificate (.cer) file using Windows file sharing experimental capability.  I am unable to select a .cer file in my Windows share folders.  Installing a user defined root certificate is handy for trusting self-signed certs or utilizing debugging tools such as fiddler.

<details>
  <summary>screenshot</summary>

![image (5)](https://github.com/microsoft/WSA/assets/118556669/aad3529a-a441-4a10-8c67-5fbdc55adb3e)
</details>

### Describe the solution you'd like

Simpler workflow for selected .cer file that exists on the Windows 11 device.  It would also be preferred not to have to invoke the settings UI with a command as shown in alternatives below

### Describe alternatives you've considered

I have included some steps to installing a User CA cert.  WSA hides “.cer” files in the Windows file sharing tool.  In order to install a user root certificate, you will need to rename, move and rename the certificate file.  

Prepare the certificate file:
1.      Download your CA certificate (it should be in your c:\users\{login}\Downloads folder)
2.      Rename the file from <cert_name>.cer to <cert_name>.txt 

Configure WSA for Windows file access and stage certificate:
1.      Open the Windows Subsystem for Android app
2.      Advanced settings tab -> Experimental features -> Toggle ON “Share user folders”
3.      System tab -> Select “Turn off Windows Subsystem for Android”  
4.      System tab -> Files pop-out
5.      Navigate to with Subsystem for Android(TM) -> Windows -> Downloads 
6.      Long click on the <cert_name>.txt file so it’s selected with a blue check
7.      Click on the upper right overflow (…) menu -> select “Move to”
8.      Move file to “Downloads” folder (note this is the “Android devices” download folder) 
9.   Navigate to the new file location in the download folder -> Long click on the <cert_name>.txt 
10.   Click on the upper right overflow (…) menu -> select “Rename”
11.   Change file extension to .cer

Install Certificate:
1.      Windows Start -> run -> wsa://com.android.settings 
2.      Search “CA certificate” —> Select “CA certificate” -> Select “CA certificate” -> Install Anyway 
3.      Select the upper left overflow / 3 bar menu button -> choose Subsystem for Android(TM) option
4.      Scroll down to the bottom of the list and choose “Windows” -> then “Downloads”
5.      Choose <cert_name>.cer 
6.      Certificate is installed

### Please specify the version of Windows Subsystem for Android

2308.40000.2.0

**Comment by jaholme** [comment]
Thanks for the feedback. We'll investigate if this is something we can implement in the future.

**Comment by kevinkieselbach** [comment]
We'll remove the block for ".cer" files.  Our block list was copied from the Outlook attachment block list, and the purpose is to prevent users from accidentally running malicious code by double-clicking files.  Since certificate files aren't automatically installed on double-click (users have to work through a multi-step dialog), we can allow certificate files.

**Comment by jake-brown-maps** [comment]
Good deal - should we look for that in 2309?

**Comment by jaholme** [comment]
This functionality was released in the preview build we announced yesterday.
