### ISSUE TITLE
Add proper cursor support

### ISSUE THREAD

**Issue by dch82** [microsoft/WSA#429]
### Is your feature request related to a problem? Please describe

When I play some games with mouse support (e.g. Minecraft), it stays on touchscreen mode because of the touchscreen emulation.

### Describe the solution you'd like

Add an option to disable touchscreen emulation, or downright disable touchscreen emulation because android supports mouse+keyboard natively.

### Please specify the version of Windows Subsystem for Android

2307.40000.6.0

**Comment by kevinkieselbach** [comment]
Most Android apps don't support mouse, so we have to provide touch emulation by default.  Apps can opt out of the touch emulation by declaring that they support PC input modalities in their manifest as follows (this is the same approach used by ChromeOS):

<manifest ...>
  <uses-feature
      android:name="android.hardware.type.pc"
      android:required="false" />
  ...
</manifest>

We can consider providing users a setting to override the default, but this GitHub is for developer requests.  Please submit end user requests in Feedback Hub.

**Comment by dch82** [comment]
Ok, noted.
Thanks anyway 👍
