### ISSUE TITLE
需要适配OpenGL ES 3.1+

### ISSUE THREAD

**Issue by XuanXue2008** [microsoft/WSA#441]
### Steps to reproduce

我在运行sky时无法启动
![image](https://github.com/microsoft/WSA/assets/138149926/a5374f8c-068c-4854-bdab-c4a3b41b66d8)

### ✔️ Expected Behavior

我希望能够运行sky

### ❌ Actual Behavior

运行sky时提示缺失OpenGLES 3.1+

### Other Software

magsik
MT管理器
Google apps
APKMirror installer

### Please specify the version of Windows Subsystem for Android

2307.40000.6.0

**Comment by dabhattimsft** [comment]
This is being tracked under #211
