### ISSUE TITLE
Play/pause button on the headphone doesn't work on WSA apps

### ISSUE THREAD

**Issue by mio-19** [microsoft/WSA#445]
### Steps to reproduce

+ Open a youtube page in Chrome in background. Play a short and pause it
+ Play a podcast on [some app](https://www.xiaoyuzhoufm.com/) on WSA
+ Press the play/pause button - Actual Behavior: the short plays and the podcast continues to play
+ Close Chrome
+ Press the play/pause button - Actual Behavior: Nothing

### ✔️ Expected Behavior

Controls the WSA app

### ❌ Actual Behavior

X

### Please specify the version of Windows Subsystem for Android

2308.40000.3.0

**Comment by dabhattimsft** [comment]
Hi, it doesn't seem to repro for me in the app. Chrome scenario will need more investigation.

**Comment by mio-19** [comment]
2309 and latest windows 11 doesn't have this issue anymore
