### ISSUE TITLE
An app reported split screen when fullscreen

### ISSUE THREAD

**Issue by mio-19** [microsoft/WSA#446]
### Steps to reproduce

1. Install bilibili or bilibili hd from some source such as https://www.bilibili.com
2. Open the app in fullscreen
3. Play some random video
4. Click the fullscreen button

### ✔️ Expected Behavior

Go fullscreen

### ❌ Actual Behavior

The app reported that fullscreen is not possible in split-screen mode

### Please specify the version of Windows Subsystem for Android

2309

**Comment by dabhattimsft** [comment]
Hi, Android apps on WSA are launched in multi-window mode and not in full screen. Hence, this is by design. To make app full-screen, you can use F11 key.

**Comment by mio-19** [comment]
> Hi, Android apps on WSA are launched in multi-window mode and not in full screen. Hence, this is by design. To make app full-screen, you can use F11 key.

The app was full-screen but it doesn't think it is fullscreen so refused to play video fullscreen

**Comment by mio-19** [comment]
> Hi, Android apps on WSA are launched in multi-window mode and not in full screen. Hence, this is by design. To make app full-screen, you can use F11 key.

I made it fullscreen
