### ISSUE TITLE
Windows Subsystem for Android (WSA) version(s) 2309.40000.4.0, v2309.40000.5.0 and v2309.40000.7.0 - missing scrollbar for the Apps tab on right side on Windows Subsystem for Android app

### ISSUE THREAD

**Issue by Almighty188** [microsoft/WSA#451]
### Steps to reproduce

In Windows 11, opening the Windows Subsystem for Android™ app for Windows Subsystem for Android (WSA) version(s) 2309.40000.4.0, v2309.40000.5.0 and v2309.40000.7.0, the app is missing the scrollbars on the right side for the Apps section so there is no way to show apps other than what is directly shown on the screen which is needed for some apps that don't directly show up from the Start menu as it also allows Force stopping apps.
The scrollbars do show up for System, Advanced settings and About when those don't even need it.

### ✔️ Expected Behavior

The scrollbars would be there so one can see installed apps beyond what is displayed on the screen.

### ❌ Actual Behavior

The scrollbars are missing in the Apps tab so one cannot see installed apps beyond what is shown on the screen as there is no way to scroll past the displayed apps. 

### Please specify the version of Windows Subsystem for Android

2309.40000.4.0, v2309.40000.5.0 and v2309.40000.7.0

**Comment by mattkopec** [comment]
Thanks for reporting this and apologies for the inconvenience. We've fixed this internally today. The fix will be available in a newer v2309 version. Will provide an update when that occurs.

A workaround to access the hidden UI is possible using Windows Narrator combined with keyboard navigation. Happy to provide details if needed.

**Comment by Almighty188** [comment]
Thanks for the response and atleast acknowledging the problem as I tried Feedback Hub since 2309.40000.4.0 was out originally and also reported it when 5.0 and 7.0 came out but it seems like there was no response from the Microsoft side so didn't even know if the WSA team was even aware of it and then I remembered there was also github. 

It would be great if the details for the workaround to access the hidden UI using Windows Narrator combined with keyboard navigation can be provided as there is a issue with Windows Terminal where when running in elevated/admin mode, the tabs cannot be dragged which is something in Windows 10/11 itself and the workaround was accessing the command pallette using ctrl+shift+P and then using the keyboard to perform the task by moving forward, moving back the tabs.

**Comment by mattkopec** [comment]
We happened to look at the GitHub issues first but did find your Feedback Hub entries.

For the workaround, start by launching the Windows Narrator app (more details here: https://support.microsoft.com/en-us/windows/complete-guide-to-narrator-e4397a0d-ef4f-b386-d8ae-c172f109bdb1#WindowsVersion=Windows_11). You'll need output audio for Narrator to help you.

Next, launch/switch to the Windows Subsystem for Android™ app and use tab key to navigate/change focus between the controls on the page. Once you navigate to the list of apps, you can use up/down arrow keys to navigate between the apps. On each control focus change, Narrator should announce what control currently has focus, which tells you where you are. You can then use enter or space keys to activate the control with focus. If you activate the app flyout menu (three dots button), the menu options can be navigated with up/down arrow keys and the selected option activated with space or enter keys.

Hope that helps.

**Comment by jaholme** [comment]
This fix is available in 2309.40000.8.0

**Comment by Almighty188** [comment]
> We happened to look at the GitHub issues first but did find your Feedback Hub entries.
> 
> For the workaround, start by launching the Windows Narrator app (more details here: https://support.microsoft.com/en-us/windows/complete-guide-to-narrator-e4397a0d-ef4f-b386-d8ae-c172f109bdb1#WindowsVersion=Windows_11). You'll need output audio for Narrator to help you.
> 
> Next, launch/switch to the Windows Subsystem for Android™ app and use tab key to navigate/change focus between the controls on the page. Once you navigate to the list of apps, you can use up/down arrow keys to navigate between the apps. On each control focus change, Narrator should announce what control currently has focus, which tells you where you are. You can then use enter or space keys to activate the control with focus. If you activate the app flyout menu (three dots button), the menu options can be navigated with up/down arrow keys and the selected option activated with space or enter keys.
> 
> Hope that helps.

Thanks for the workaround, will keep it in mind should I ever need to use it.
