### ISSUE TITLE
In Windows Subsystem for Android, the LT and RT of the gamepad are recognized as reversed.

### ISSUE THREAD

**Issue by kdaek21** [microsoft/WSA#452]
### Steps to reproduce

1. Register after connecting the gamepad
2. Install and run apps or games that support gamepad in Windows Subsystem for Android
3. gamepad operation
4. When you press the LT (Left Trigger) key, it is recognized as pressing the RT (Right Trigger) key.
5. When you press the RT (Right Trigger) key, it is recognized as pressing the LT (Left Trigger) key.
6. LT and RT of the gamepad are recognized correctly in regular Windows apps, game console emulators, and Android devices, not Android apps run on WSA. Also, even if it is an Android app run on WSA, keys other than LT and RT are recognized normally. .

### ✔️ Expected Behavior

Pressing LT should be recognized as pressing LT, and pressing RT should be recognized as pressing RT.

### ❌ Actual Behavior

Pressing LT is recognized as pressing RT, and pressing RT is recognized as pressing LT.

### Other Software

- Testing at WSA
Android app or gamepad tester app that supports gamepad (internal to WSA, for testing gamepad key behavior in WSA)

- Testing on Windows as a control
Windows games or apps that support gamepads
Game console emulator that supports gamepads (Cemu, Dolphin, etc.)

- Other software
BetterJoy (required if you use the Nintendo Switch Joy-Con as a gamepad rather than an Xbox controller)
* When using Nintendo Joy-Con, you must swap A/B and X/Y.
When directly connected and used on Android, the Joy-Con's ZL and ZR are output as L2 and R2, and when used on Windows through BetterJoy, the Joy-Con's ZL and ZR are converted to the Xbox controller's LT and RT for output.

### Please specify the version of Windows Subsystem for Android

2308.40000.3.0 (If it has not been discovered yet, the same symptoms are expected to exist in previous and future versions.)

**Comment by philnach** [comment]
@kdaek21, thank you for taking the time to provide feedback.  We'll take a look and update this issue with any findings.

**Comment by philnach** [comment]
@kdaek21, we took a look, and the triggers were indeed flipped.  Triggers should not be properly reported LT as LT and RT as RT.  I'll close this issue when the update has been made available.

**Comment by jaholme** [comment]
The fix for this bug has been released to the preview program audience in build 2310.40000.0.0. It will be released to a broader audience in the coming weeks.
