### ISSUE TITLE
Unable to copy CJK characters from WSA

### ISSUE THREAD

**Issue by AnYiEE** [microsoft/WSA#454]
### Steps to reproduce

1. Open any WSA application (e.g., "File").
2. Enter CJK characters in any input box within the application.
3. Select the text and copy/cut.
4. Paste in Windows.

### ✔️ Expected Behavior

Copy "测试文本" in WSA, the pasted text in Windows should be the same as the copied one, not "æµè".

### ❌ Actual Behavior

Copy "测试文本" in WSA and paste it in Windows to get "æµè".

### Please specify the version of Windows Subsystem for Android

2308.40000.3.0

**Comment by jaholme** [comment]
Thanks for raising this issue. We plan to address this in an upcoming update to WSA.
