### ISSUE TITLE
My app is shown as incompatible on PlayStore

### ISSUE THREAD

**Issue by pranshuchittora** [microsoft/WSA#458]
### Provide a description of requested docs changes

Hey there, I am a app developer and my app is published on Play Store. But the app is not showing on the PlayStore on WSA. When I navigate to the app via playstore URL It says your device is not compatible.

Can you help me with the steps to make any android app compatible with WSA. Also a public doc would be helpful for others. 

Good Day

**Comment by jaholme** [comment]
Hello, unfortunately we cannot provide support for the Google Play Store
