### ISSUE TITLE
Deep linking of apps not working on WSA

### ISSUE THREAD

**Issue by n-kumari** [microsoft/WSA#465]
### Steps to reproduce

Create an Android app with activity TestActivity which has an intent filter of `BROWSABLE`.

```
    <activity android:name=".ui.TestActivity"
              android:exported="true"
              android:label="@string/app_name">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="test" />
        <data android:host="*" />
      </intent-filter>
    </activity>
```

Create a link in browser using href as follows:

`<a href="test://simple">TestApp</a>`

### ✔️ Expected Behavior

Clicking on the link should open the app regardless of it is running or not.

### ❌ Actual Behavior

Clicking on the link only opens the app is it is not already running. If the app is in background, the app is not opened when link is clicked.

NOTE: The same sample app works as expected when running outside of WSA environment (i.e., on Android physical device or simulator)

### Please specify the version of Windows Subsystem for Android

2309.40000.10.0

Windows OS build: 22000.2538

**Comment by n-kumari** [comment]
On doing further investigation looks like this could be related to deep linking of apps running on WSA.

For my use case, the user is initially on activity A and then leaves the app to perform authentication via browser. After successful authentication, the user is redirected back to the app using deep links. The redirection, however, is not happening when the app runs on WSA. 

If the user goes back to app manually after authentication, a new instance of activity A is being created on WSA. When the app runs on regular Android device/simulator, the redirection after authentication works as expected and `onNewIntent` is called.

**Comment by parveen-bhatia** [comment]
Any update on this @microsoftopensource ?

**Comment by n-kumari** [comment]
We don’t see this issue on a different profile on the same laptop and are no longer able to reproduce this. Closing the issue
