### ISSUE TITLE
Android's OneDrive app in WSA seems to conflict with OneDriveSetup.exe's version checking

### ISSUE THREAD

**Issue by DandelionSprout** [microsoft/WSA#473]
### Steps to reproduce

This is a somewhat complex case: I had recently installed Windows 11 23H2, and all of a sudden the desktop OneDrive app was gone. So I decided to download OneDriveSetup.exe to reinstall, but since I had the Android OneDrive app (v6.91.2) installed in WSA, OneDriveSetup incorrectly complained about a "newer version" already being installed.

I had problems accessing WSA itself at the same time (though that isn't the focus of this report), but after using Geekuninstaller to do a forced uninstall of the Android OneDrive app, the desktop OneDriveSetup proceeded correctly and normally.

### ✔️ Expected Behavior

The desktop Windows OneDriveSetup installer wizard does not take into regard any Android WSA OneDrive apps when determining which OneDrive versions are installed on the PC.

### ❌ Actual Behavior

The desktop Windows OneDriveSetup installer wizard seems to confuse Android WSA OneDrive apps for the Windows desktop OneDrive app, when determining which OneDrive versions are installed on the PC, leading to the OneDriveSetup wizard failing.

### Other Software

OneDrive Android 6.91.2 (inside WSA)
OneDriveSetup.exe for build 23.221.1024.0002 x64

### Please specify the version of Windows Subsystem for Android

2309.40000.2.0

**Comment by xhan65** [comment]
Thanks for your feedback. This should be an issue with OneDrive, so please create a feedback in Feedback Hub under category Files, Folders and Online Storage > OneDrive.
