### ISSUE TITLE
Prevent WSA automatic starts

### ISSUE THREAD

**Issue by 3119369616** [microsoft/WSA#506]
### Is your feature request related to a problem? Please describe

WSA starts automatically every time when the computer is turned on. I can see a process named `vmmem` in Task Manager.

### Describe the solution you'd like

Don't automatically start WSA when I turn on my computer.

### Please specify the version of Windows Subsystem for Android

2311.40000.4.0

**Comment by 3119369616** [comment]
1. Press hotkey Ctrl+Shift+Esc to open Task Manager.
2. Click “Startup” tab and you can see an item “Windows Subsystem for Android™”.
3. Right-click this item and click “Disable”.

**Comment by aircoolbro21** [comment]
> 1. Press hotkey Ctrl+Shift+Esc to open Task Manager.
> 2. Click “Startup” tab and you can see an item “Windows Subsystem for Android™”.
> 3. Right-click this item and click “Disable”.

theres nothing in startup called "windows subsystem for android" and nothing in autoruns that has anything to do with "subsystem" or "android", just WSL, yet wsa still starts in the background
