### ISSUE TITLE
Will this project continue to be maintained and updated after March 5, 2025?

### ISSUE THREAD

**Issue by liyuhaolol** [microsoft/WSA#538]
### Describe the solution you'd like

I saw Microsoft's official announcement, but it doesn't clearly explain the specific reasons for discontinuing WSA. I also saw Amazon's announcement, which suggests that they will no longer maintain the apps available for download, but it doesn't seem directly related to WSA itself. Because WSA can still install APK files through other methods. So, I couldn't understand why WSA is being discontinued along with those apps.

Therefore, is this project only being delisted from the Microsoft Store but will continue to be maintained and updated with installation packages available on GitHub? Or will the WSA project be discontinued after the expiration date? I was quite shocked to see Microsoft's announcement and would like to inquire about the outcome.

### Please specify the version of Windows Subsystem for Android

2207

**Comment by KJZH001** [comment]
I also want to know the answer to this question, and there are some self-compiled Android images and wsa branches for side loading on github, will the side loading installation of wsa be affected? thank you.

**Comment by Morrigan-Ship** [comment]
dont stop WSA project please

**Comment by NiffirgkcaJ** [comment]
Dear Microsoft,

If you're going to discontinue this software, at least open-source it please.

**Comment by AndnixSH** [comment]
> Dear Microsoft,
> 
> If you're going to discontinue this software, at least open-source it please.

It would be great if they did

**Comment by Naitrate** [comment]
> If you're going to discontinue this software, at least open-source it please.

Yeah, I hope that they open source it, because as far as I can tell, this is the only decent Android emulator on Windows that isn't ripe with spyware.

**Comment by MeowLove** [comment]
I suggest that Microsoft should reconsider this decision to stop WSA support. I gave some suggestions.
#https://github.com/microsoft/WSA/issues/539#issuecomment-1982283837

As of March 7, 2024, WSA is still the best Android emulator on Windows. It supports independent application windows and has great compatibility with common Android apps (except for games with strong detection). Other simulators can't display each application independent window on windows system.

**Comment by Morrigan-Ship** [comment]
> I suggest that Microsoft should reconsider this decision to stop WSA support. I gave some suggestions.

thank you i readed it very good
are you sure about WSL3 ?

**Comment by Slion** [comment]
This should be moved to discussions. It is a good question though but I'm afraid you won't like the answer.

**Comment by Morrigan-Ship** [comment]
> but I'm afraid you won't like the answer

what you mean?

**Comment by Slion** [comment]
Well they just made an announcement to say it will be discontinued. I don't see why they would keep developing if it is discontinued. What I'm saying is that you are in denial and so am I quite frankly.

**Comment by KJZH001** [comment]
I feel very regretful about stopping this project

As I mentioned in the issue, I would like to know if the WSA installed on the side load and the Android images compiled by third-party branches will be affected?

And since Microsoft plans to stop this project, will it consider opening it up for community maintenance?

The above are some of my personal thoughts. WSA is indeed very useful, which is why we all are so reluctant to part with it
I hope Microsoft can give us all a response. Thank you

===
我对于停止这个项目感到十分的可惜

正如我在issue那边所说的，我希望能够知道侧载安装的WSA和第三方分支编译的安卓镜像是否会受到影响？

并且，微软既然打算停止这个项目，是否会考虑将它开源由社区维护呢？

以上是我个人的一些想法，WSA确实很好用，所以我们大家才会如此舍不得它

希望微软能够给我们大家一个答复，谢谢

**Comment by GitHub-Creeper** [comment]
I dont know if they "break" the project or "discontinue" the project. They didn't make it completely clear.

**Comment by GitHub-Creeper** [comment]
I don't know what will they "do" when they end support, "break" or "discontinue" the project
