### ISSUE TITLE
When I was registering for WSA Preview Program it said the form was closed

### ISSUE THREAD

**Issue by skanda890** [microsoft/WSA#550]
### Steps to reproduce

Go to this
![image](https://github.com/microsoft/WSA/assets/99239826/dfcdb637-eb65-455e-b4e8-705bb4cdf856)
then click on 
![image](https://github.com/microsoft/WSA/assets/99239826/90ae47ab-77ae-4ba8-9095-b23d7a0bcf21)
then the link will redirect you to
![image](https://github.com/microsoft/WSA/assets/99239826/2e119b8a-985b-46ed-86df-ea3f8749ff4a)
then click on the register option
![image](https://github.com/microsoft/WSA/assets/99239826/d9dcfb1a-9db5-4833-92bc-df42bc307e5f)

### ✔️ Expected Behavior

The form to register should be open.

### ❌ Actual Behavior

It was closed.

### Please specify the version of Windows Subsystem for Android

2311.40000.5.0

**Comment by Slion** [comment]
That might be because WSA is now discontinued. They actually stopped working on it months ago I believe.

**Comment by skanda890** [comment]
Okay, but why is the option still in the WSA app?

**Comment by Slion** [comment]
Cause there is nobody at the wheel. Staff working on the project have been told to stop all activities and nobody is in charge anymore.

**Comment by skanda890** [comment]
But users don't know that at least tell them that the WSA preview is closed.
