### ISSUE TITLE
WifiInfo - wrong and missing data (link speeds)

### ISSUE THREAD

**Issue by analitiLLC** [microsoft/WSA#57]
### Steps to reproduce

dumpsys wifi | grep mWifiInfo

### ✔️ Expected Behavior

mWifiInfo SSID: "My Network", BSSID: fc:34:97:3b:46:94, MAC: <none>, Security type: 2, Supplicant state: COMPLETED, Wi-Fi standard: 6, RSSI: -27, Link speed: 1020Mbps, Tx Link speed: 1020Mbps, Max Supported Tx Link speed: 1200Mbps, Rx Link speed: 360Mbps, Max Supported Rx Link speed: 1200Mbps, Frequency: 5745MHz, Net ID: 44, Metered hint: false, score: 60, CarrierMerged: false, SubscriptionId: -1, IsPrimary: 1

(from a Google Pixel device)

### ❌ Actual Behavior

mWifiInfo SSID: "My Network", BSSID: fc:34:97:3b:46:94, MAC: <none>, Security type: 2, Supplicant state: COMPLETED, Wi-Fi standard: 0, RSSI: -50, Link speed: 500Mbps, Tx Link speed: 500Mbps, Max Supported Tx Link speed: -1Mbps, Rx Link speed: -1Mbps, Max Supported Rx Link speed: -1Mbps, Frequency: 5745MHz, Net ID: 1, Metered hint: false, score: 60, CarrierMerged: false, SubscriptionId: -1, IsPrimary: 1

### Have you specified the version of Windows Subsystem for Android under Milestone?

- [X] I have set this issue's milestone

**Comment by nieubank** [comment]
This is a known issue that we'll look into for a future release. If there are any specific bugs associated with this that affect app compatibility, please let us know to help prioritize.

**Comment by analitiLLC** [comment]
Hi Nick,

Thanks for your quick response.

The issue impacts our app - "Speed Test WiFi Analyzer"
(com.analiti.fastest.android) - the #1 app in Amazon
Appstore's Utilities/Speed Testing category.
We use WiFi link speeds (also called phy speeds or phy rates)
extensively in analyzing wifi networks' performance.
Right now we get an invalid 500K link speed (without any bearing to
reality, naturally) - and we only get it for the TxLinkSpeed.

Please let us know what we can do further to expedite a resolution to this
issue.

Thanks again,
Eran

**Comment by analitiLLC** [comment]
It seems that the Windows API WlanQueryInterface can fetch a WLAN_CONNECTION_ATTRIBUTES structure that contains WLAN_ASSOCIATION_ATTRIBUTES structure with the most important factors: dot11PhyType, ulRxRate and ulTxRate.

**Comment by analitiLLC** [comment]
2208.40000.5.0

**Comment by analitiLLC** [comment]
Also note that if you use WLAN_ASSOCIATION_ATTRIBUTES  for RSSI - you'll get quality value translatable to only -50dBm or lower (even if actual RSSI value is higher than -50dBm)
For correct RSSI use wlan_intf_opcode_rssi with WlanQueryInterface (and use WLAN_ASSOCIATION_ATTRIBUTES  for phy speeds)

**Comment by analitiLLC** [comment]
It's been 7 months and this bug still persists even in the latest release.
ETA for resolution?

**Comment by nieubank** [comment]
This isn't on the immediate roadmap. Since our networking stack is virtualized and not a native solution supporting network utilities is not a target area at the moment, even if we could replicate network details and topology perfectly, the performance analysis achieved by an Android application would only apply to Android apps and not necessarily the end user's physical device.

That's not say we don't want to support high fidelity in emulation here. It's just not a priority at the moment.

**Comment by analitiLLC** [comment]
In closing issue #290 Nick say "_if something about the data presented results in an issue in your app, we'd like to know specifics so we can plan to address those_".
Please have a look at the first message on this issue #57.
It's not about doing any manipulation on hardware - it's about showing information to the user, which is critical to our app.
WSA already provides this information (as an existing feature or behavior of WSA) - but **some** of it is incorrect. We are not asking to implement new features, just asking to fix a bug in the WSA implementation that shows the incorrect data (most of the rest of the data is correct).

**Comment by analitiLLC** [comment]
Indeed - the information in question (mostly correct, part incorrect) is presented when WSA is using Advanced Networking.
So the bug scope can be narrowed to that feature.

The conversation about virtualized vs (something else) is something most app users we know could not care less about. It's either they get the what they need from the app or not.

We can tell them "switch Advanced Networking ON in WSA" (like we suggest to them to configure other settings in the Android environment) - it's their choice, not ours. And if they choose to use our app, with WSA's Advanced Networking feature - they are currently presented with mostly correct but partly incorrect information - due to a bug in the Advanced Networking feature implementation.

On the one hand "the value of the app is not questioned" yet on the other hand the value of the WSA's own "Advanced Networking" feature is discounted.

We are not asking to develop a feature to support our app.
We hope the bug in the WSA feature feature already developed and delivered to users (even if as experimental) - is fixed.
This issue has nothing to do with virtualization - just using a wrong WIN API method to get a specific information piece (the call is already made by WSA Advanced Networking - it's just not the right one for the intended information).
