### ISSUE TITLE
Hope to improve winui2 library version

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/WSA#60]
### Is your feature request related to a problem? Please describe

The current version of Microsoft .ui.xaml used by the WSA setup is 2.6, but Microsoft .ui.xaml has released 2.8, when can I upgrade to Microsoft.ui.xaml 2.8?

### Describe the solution you'd like

Home to improve microsoft.ui.xaml 2.6 to microsoft.ui.xaml 2.8

### Describe alternatives you've considered

No

### Have you set this feature request's Milestone field to Future Release?

- [X] I have set this issue's milestone to Future Release

**Comment by hamza-usmani** [comment]
Hi, while the XAML framework is a dependancy for the subsystem, it does not affect any applications running within the subsystem and the version should not have an impact in any way.

**Comment by Gaoyifei1011** [comment]
> Hi, while the XAML framework is a dependancy for the subsystem, it does not affect any applications running within the subsystem and the version should not have an impact in any way.

On this issue, I know that XAML is a dependency of the subsystem setup interface, and that the Winui2.6 currently used does not affect any applications. But compared to the winui2 XAML version of your company's other programs (most of your apps are based on Winui2.7 and Winui2.8), this version may be a little outdated, and isn't it convenient to update the Winui library in Visual Studio?
