### ISSUE TITLE
Is there a chance to link APK files and install them quickly in the future?

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/WSA#61]
### Is your feature request related to a problem? Please describe

Is there a chance to link APK files and install them quickly in the future?
Currently, WSA app installations can only be installed through the Amazon Appstore, but compared to Google Play App Store software, it is only rare. Even the mainstream Android mobile app stores also provide side-loading installation of APK applications. At present, WSA wants to install sideloaded applications need to use ADB tools and some commands (these things WSA does not support), can only be through some third-party tools provided by the Microsoft Store to fool sideloading. Will there be a chance for WSA or App Installer to add APK, APKS, and ABB file associations to quickly install Android apps in the future?    

### Describe the solution you'd like

Hope to provide a solution for quick side-loading of applications (your Microsoft Store applications (MSIX) are not fully limited) 

### Describe alternatives you've considered

No

### Have you set this feature request's Milestone field to Future Release?

- [X] I have set this issue's milestone to Future Release

**Comment by hamza-usmani** [comment]
Hi, which commands specifically are you referring to which the subsystem doesn't support? If you're looking to test and debug your APKs, this can be done easily by sideloading your APK as outlined in our [developer documentation](https://learn.microsoft.com/en-us/windows/android/wsa/#debug-your-app)!

**Comment by Gaoyifei1011** [comment]
> Hi, which commands specifically are you referring to which the subsystem doesn't support? If you're looking to test and debug your APKs, this can be done easily by sideloading your APK as outlined in our [developer documentation](https://learn.microsoft.com/en-us/windows/android/wsa/#debug-your-app)!

I know how to use the command to install the APK program quickly.
In your Microsoft Store, there are two ways to install the installed MSIX/APPX package. One is to open the Powershell command and input the Add-appxpackage "file path" command to install the msix/Appx package. The other is to install the Msix/Appx package directly using the GUI provided by you. Compared with the former, the second scheme is more convenient and user-friendly for ordinary users.
This is not to say that the subsystem does not support any commands, but that it would be easier for WSA to install side-loads.

**Comment by yonggamer** [comment]
please link .apk to the WSA app

**Comment by TAMSHUI** [comment]
Our customer's LOB is based Android. in this scenario link .apk to the WSA can allow our customers easily deploy they Android LOB app on our Surface Pro. or is there any other way to massively deploy Android LOB App to the WSA.
