### ISSUE TITLE
Amazon Appstore will not connect

### ISSUE THREAD

**Issue by jimrome** [microsoft/WSA#63]
### Steps to reproduce

I Open the Amazon Appstore (it says it updated to latest version), and it always gives a connection error. My Internet connect is fine.

### ✔️ Expected Behavior

Should connect

### ❌ Actual Behavior

Connection error

### Other Software

WSA 1.7.32815.0

### Have you specified the version of Windows Subsystem for Android under Milestone?

- [X] I have set this issue's milestone

**Comment by hamza-usmani** [comment]
Hi, it looks like you're running a much older version of WSA and the Amazon Appstore that might be leading to some networking issues. Have you tried updating to the latest version through the Microsoft Store (we've resolved many of these issues in our newer releases)?

**Comment by jimrome** [comment]
That's why I am trying to run the app store. I can't seem to update WSA. How do I get the latest WSA?

**Comment by hamza-usmani** [comment]
Please uninstall the Amazon Appstore (which will uninstall the subsystem), and then follow the [steps here to install the latest version](https://support.microsoft.com/en-us/windows/install-mobile-apps-and-the-amazon-appstore-on-windows-f8d0abb5-44ad-47d8-b9fb-ad6b1459ff6c).

**Comment by jimrome** [comment]
That worked. Thanks
