### ISSUE TITLE
It is recommended to add the keyboard mapping function

### ISSUE THREAD

**Issue by levkanm** [microsoft/WSA#66]
### Describe the solution you'd like

It is recommended to add a custom keyboard mapping function to play mobile games that do not support gamepad
![IMG_20221021_115413](https://user-images.githubusercontent.com/105607530/197109512-3ac2b878-9836-4d0b-84f3-7965a3dbc9a5.png)

### Have you set this feature request's Milestone field to Future Release?

- [x] I have set this issue's milestone to Future Release

**Comment by hamza-usmani** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community!

**Comment by xAffan** [comment]
You guys are missing out on gamers! Literally everyone would use WSA and ditch all the emulators if you do this. Please give this a higher priority.

**Comment by nieubank** [comment]
Tracking under #82

**Comment by FlippantDev** [comment]
> You guys are missing out on gamers! Literally everyone would use WSA and ditch all the emulators if you do this. Please give this a higher priority.

here, an app I'm working on that allows keymapping all across windows.
it uses a cordinate system so thats that
https://github.com/flippantdev/wmapperkeymapper
