### ISSUE TITLE
Video not playing after long time use

### ISSUE THREAD

**Issue by Boing57** [microsoft/WSA#70]
### Steps to reproduce

Using android apps more than 1-2 hours and the video will not play.

### ✔️ Expected Behavior

Video can play even using the apps too long.

### ❌ Actual Behavior

I tried using WSA all day, and I got a problem when using it for too long where the video wouldn't play on all the apps I downloaded. I need to turn off wsa and open the apps, then the video can play.
![image](https://user-images.githubusercontent.com/78803559/197201199-82cbe7ab-d457-4653-891a-f4d8d4b186f8.png)

### Have you specified the version of Windows Subsystem for Android under Milestone?

- [ ] I have set this issue's milestone

**Comment by hamza-usmani** [comment]
Hi, please specify the version/build of the subsystem you're running to help us investigate.

**Comment by Boing57** [comment]
Hi, I'm using Windows Subsystem Version 2209.40000.26.0. The latest version.

**Comment by Boing57** [comment]
> 

I think I got the same problem when using iGPU Intel UHD Graphics 620 😅

**Comment by Boing57** [comment]
> Using dGPU doesn't seem to be able to reclaim VRAM, if it runs out it can cause such issues

Is that normal? or it only on WSA only?
I try to use all the apps until my dGPU memory about 2GB and the apps start not playing the video, also the dGPU keep 1.6GB until I turn off WSA. 
![image](https://user-images.githubusercontent.com/78803559/197326464-5aaf58be-d995-417e-96c1-e2a2cdfeaf26.png)

**Comment by Boing57** [comment]
> > > Using dGPU doesn't seem to be able to reclaim VRAM, if it runs out it can cause such issues
> > 
> > 
> > Is that normal? or it only on WSA only? I try to use all the apps until my dGPU memory about 2GB and the apps start not playing the video, also the dGPU keep 1.6GB until I turn off WSA.
> 
> Apparently not expected behavior, if you use an iGPU, the VRAM will be freed as soon as the Android app is closed

As you say, I try to use iGPU and the VRAM freed as soon the Android apps is closed. Is this can be GPU driver issue or WSA issue?

**Comment by Boing57** [comment]
> > > > > Using dGPU doesn't seem to be able to reclaim VRAM, if it runs out it can cause such issues
> > > > 
> > > > 
> > > > Is that normal? or it only on WSA only? I try to use all the apps until my dGPU memory about 2GB and the apps start not playing the video, also the dGPU keep 1.6GB until I turn off WSA.
> > > 
> > > 
> > > Apparently not expected behavior, if you use an iGPU, the VRAM will be freed as soon as the Android app is closed
> > 
> > 
> > As you say, I try to use iGPU and the VRAM freed as soon the Android apps is closed. Is this can be GPU driver issue or WSA issue?
> 
> I don't know, may need to test with Intel/AMD's dGPU, I don't have these

Thank you for the information. I don't have either both too, already sold my amd setup so can't test 😂

**Comment by Boing57** [comment]
After test & and check, as per Arm64-v9a mention, when using dGPU the VRAM not freed after 3-minute minimizing the apps. I try with iGPU, after 3-minute the memory drop from 1.1GB to 0.4GB and after that I can keep playing the video. If using dGPU and minimize, the memory does not drop even I left it more than 5-minute. After that I continue to use the apps and the memory keep raise and the video start show playback error. I don't know the problem with driver or its common or the WSA itself.    
![WSA](https://user-images.githubusercontent.com/78803559/197353446-61b38776-79a9-445f-a91e-098287dbe62a.png)

**Comment by Boing57** [comment]
I try with iGPU and I figure out the problem happen after GPU memory use more than 2GB and it the video start not playing and GPU memory drop from 2GB to 0.6GB. I don't know if that happen to other people or only me or my spec is not to power to use Android apps on Windows 11.

**Comment by nieubank** [comment]
Thanks for the very helpful analysis. Based on these details, I understand what's going on here. We'll take a more detailed look and get started on a resolution.

**Comment by Boing57** [comment]
> Thanks for the very helpful analysis. Based on these details, I understand what's going on here. We'll take a more detailed look and get started on a resolution.

I hope it will help. Hope for the best for WSA.

**Comment by Boing57** [comment]
Can we know actually, WSA require how much VRAM? Everytime WSA using more than 1.6GB or 2GB VRAM, WSA start have problem with video playback.

**Comment by Boing57** [comment]
I don't think 2GB vram dgpu is enough for windows subsystem for android. Every time use dgpu to open especially 2-3 apps, dgpu always full. Also, vram not freed even minimize or close the apps, but require to shutdown wsa.
![image](https://user-images.githubusercontent.com/78803559/209466971-0fd819d1-905b-4608-ae51-c044853c9750.png)

**Comment by nieubank** [comment]
Tracking under feedback hub.

**Comment by Aphexus** [comment]
Similar problem. Everything was working before. Songsterr and SmartTube could play videos. Now they are just in perpetual loading. Only thing I really did was install android studio and debug an app on one of it's emulators and disable some windows services(which I re-enabled and it didn't fix the problem).

I'm wondering if the "Delete permissions after a month of not being used" has anything to do with it? Maybe it is deleting too much?

**Comment by rafabra988** [comment]
any update on this?

**Comment by weebawop** [comment]
> any update on this?

looking for the same. for me the issue triggers after a few minutes of WSA use, when I open Instagram for example it works fine for a bit and then the videos no longer play, they just freeze
