### ISSUE TITLE
Google Services Integration

### ISSUE THREAD

**Issue by Iceflow420** [microsoft/WSA#74]
### Is your feature request related to a problem? Please describe

Other than lack of common Android ecosystem, no.

### Describe the solution you'd like

I'd like to see Google Service integrated into WSA because every Android user uses Google Services on their phones. Amazon is a great store if you don't really want to offer anything mainstream. This store exists to support Kindle/ Fire products and that is it. Most major developers don't even offer their products on Amazon. This severely limits the usage by most for the people that would actually use. 

### Describe alternatives you've considered

I sideload most of the apps I need because they don't exist on the Amazon App store. It sad that I have to sideload android apps that have millions of downloads on my phone but aren't available through the provide store for WSA.

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by boontham33345** [comment]
Good

**Comment by Boing57** [comment]
The good idea, because totally frust when try to use apps all need Google Service 😅

**Comment by infinitepower18** [comment]
Very unlikely this is gonna happen since Google and Microsoft don't really get along based on past events. Though Google is working on bringing Google Play Games to PC soon.

**Comment by hamza-usmani** [comment]
Hi, please see our [Frequently Asked Questions](https://github.com/microsoft/WSA/discussions/51) which address this topic.

**Comment by Boing57** [comment]
> Very unlikely this is gonna happen since Google and Microsoft don't really get along based on past events. Though Google is working on bringing [Google Play Games](https://play.google.com/googleplaygames) to PC soon.

Google Play games only can play android games only. But the problem here is when using normal apps like food delivery apps and it can't use without google play services.
![image](https://user-images.githubusercontent.com/78803559/199945929-d958de1c-b71d-44ad-96c4-92bb74822a2e.png)

**Comment by ShadowEO** [comment]
> I only use WSA for Apps, Never games. on PC, There is plenty of games on Steam, Xbox app, Xbox xCloud etc.
> 
> I think [since:](https://github.com/microsoft/WSA/discussions/51)
> 
> > Windows Subsystem for Android is based on [Android Open Source Project](https://source.android.com/), which does not include proprietary Google Play Services. Google governs the licenses for Google Play Services.
> 
> then WSA should at least provide an easier way for us to install [OpenGApps](https://github.com/opengapps/opengapps) and easily root the WSA for that purpose to have full control over it.
> 
> I think this is a more reasonable ask.

This is exactly why, Android ROMs or devices have to pass Google's CTS and more to be eligible for Google Play to come built in. Though due to this, they still can't include ANY Gapps package, or explicitly make it installable (other than providing some way to install recovery ZIPs).

**Comment by pixiekat** [comment]
Can Microsoft/WSA just not implement the microG open source project?

**Comment by infinitepower18** [comment]
No, they would get in trouble for this, they have to get a license from Google in order to incorporate Google Play Services

**Comment by s1204IT** [comment]
> Can Microsoft/WSA just not implement the microG open source project?

microG is not desired figure.

**Comment by Ismail01Hub** [comment]
has anyone found a Perfect Solution yet?

**Comment by Boing57** [comment]
> has anyone found a Perfect Solution yet?

No other way, either use Magisk on WSA or just use apps that no require Google Play services 🫠

**Comment by SteveWorkshop** [comment]
If you do think it's by design, please remove GMS from your surface duo...
Both of them are MS products

**Comment by ShadowEO** [comment]
> If you do think it's by design, please remove GMS from your surface duo... Both of them are MS products

That's not the problem and to my knowledge, no one thinks this is by design, simply necessity. Google has to certify devices in order for them to include GMS in their devices. The Surface Duo is certified, but a virtual machine is (iirc) not eligible. Since they are unable to be certified by Google's CTS requirements (at least as they stand now). It could put Microsoft in a legal bind to attempt to include GMS without certification since Google mandates that devices have this CTS certification before they ship with their suite on the system image. 

That said, Google has NO problem with end users installing GMS themselves if they are able to do so.
