### ISSUE TITLE
More customization options

### ISSUE THREAD

**Issue by arm64-v9a** [microsoft/WSA#79]
### Is your feature request related to a problem? Please describe

Allow users to adjust memory size, processors number, localhostForwarding, swap

### Describe the solution you'd like

Control the memory size, number of processors, SWAP(ZRAM), VRAM(Prevent OOM, like #70) of WSA through the .wsaconfig file

### Describe alternatives you've considered

It would be even better if there was a nice GUI to modify

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by hamza-usmani** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community!
