### ISSUE TITLE
Support Key Mapping in WSA like any 3rd party emulators like BlueStacks

### ISSUE THREAD

**Issue by muhammadbahaa2001** [microsoft/WSA#82]
### Is your feature request related to a problem? Please describe

Some landscape games cannot be played with WASD keys, it need to key mapping as BlueStacks and any other emulators

### Describe the solution you'd like

We want key mapping like any other Android Emulators such as: BlueStacks, Memu Player, Nox Player, Mumu Player, LD Player and other.

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by nieubank** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community.

**Comment by Boing57** [comment]
> Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community.

I already try Google Play Games for PC. It totally great and with key mapping and easy to play game with it. I hope Key mapping will come to WSA and make WSA is better.
![Screenshot_20221103_082006](https://user-images.githubusercontent.com/78803559/199723246-e10d0227-8732-4cb6-8b9b-4bdd79ced16a.png)
![Screenshot_20221103_083446](https://user-images.githubusercontent.com/78803559/199723267-7f96f7c0-266e-4760-9acd-c064ba6f17bc.png)

**Comment by nieubank** [comment]
Thanks for you feedback in this space, we currently have no plans to support keyboard remapping on our roadmap. It's recommend to follow Android guidelines here for keyboard compatibility. If you are not a developer of an application that does not support keyboard controls please follow up with those developers.

**Comment by Mitia99** [comment]
@Boing57 @natsumerinchan @muhammadbahaa2001 @rtanabe999 @Sendevia @massimobio @Void48 @Nox-emulator @BarnMTB @lucifer202850D @jokopoppo @levkanm @ScottRFrost @Void48 @AyakaAgo @xAffan

Please upvote [this related suggestion](https://aka.ms/AAmzamt) on Feedback Hub. Ty

**Comment by FlippantDev** [comment]
i made a program that can somehow replicate the behaviour 
not the best tho
https://github.com/flippantdev/wmapper

**Comment by Mitia99** [comment]
> i made a program that can somehow replicate the behaviour 
> not the best tho
> https://github.com/flippantdev/wmapper

Thank you. I'll leave a star and share it so that people can leave a PR.

**Comment by FlippantDev** [comment]
> > i made a program that can somehow replicate the behaviour
> > not the best tho
> > https://github.com/flippantdev/wmapper
> 
> Thank you. I'll leave a star and share it so that people can leave a PR.

aright thanks, just hoping I don't get loads of people begging for it to be like bluestacks or nox Keymapping
