### ISSUE TITLE
Windows/Android File System Communication

### ISSUE THREAD

**Issue by Iceflow420** [microsoft/WSA#85]
### Is your feature request related to a problem? Please describe

No file communication between Windows and WSA

### Describe the solution you'd like

It would be beneficial to have Windows drives show up as SDCARD(s) in the Android file system and have the Android DOWNLOADS folder show up as a Windows drive. This would allow movement of files from one system to the other in a simple/easy process.

### Describe alternatives you've considered

I've seen some work arounds on Youtube on how to accomplish this but they require the sideloading of an FTP app. This isn't very end user friendly.

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by jaholme** [comment]
Hi, this is something on our radar already for new feature requests, we appreciate the feedback here!
