### ISSUE TITLE
Add support for Activity embedding

### ISSUE THREAD

**Issue by xuanmi666** [microsoft/WSA#92]
### Is your feature request related to a problem? Please describe

Hope to support the new features of Android 12l, introduce activity embedding in the extra area of the large screen

### Describe the solution you'd like

https://developer.android.com/guide/topics/large-screens/activity-embedding

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by jaholme** [comment]
Activity embedding should work without issue in WSA.  Are there any problems that are preventing you from using it?

**Comment by xuanmi666** [comment]
> Activity embedding should work without issue in WSA.  Are there any problems that are preventing you from using it?

Nowadays, many brands of tablet computers, such as Samsung and Lenovo, forcefully enable "Activity Embedding" for specified applications in the system settings to improve the experience of large-screen devices, even if the applications are not specially adapted for the new features of Android12l. There are many versions of this feature, "App Multiplier" or "split screen left and right", similar to this new Android12l feature, but it is optional and mandatory. Hope WSA can follow up.
![331acfb14e24b59df201274147d4bdfc.jpeg](https://user-images.githubusercontent.com/79401279/198698903-a5ac023f-760b-4523-a05e-49e76868b03a.jpeg)

**Comment by nieubank** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community.
