### ISSUE TITLE
Unsupported features

### ISSUE THREAD

**Issue by upintheairsheep** [microsoft/WSA#99]
### Is your feature request related to a problem? Please describe

These features are currently not supported. Will they be added in the near future?
❌ Android Widgets
❌ Direct Bluetooth access (and BLE)
❌ File Backup/restore
❌ File transfer
❌ Hardware DRM
❌ Picture-in-picture
❌ Quick tiles
❌ USB

### Describe the solution you'd like

see up

### Please specify the version of Windows Subsystem for Android

1.0

**Comment by nieubank** [comment]
These are not on our immediate roadmap but we're always listening to the community to prioritize.
